### PR TITLE
fix: run-tests link in README.md

### LINKED ISSUE #784: Fix the links for "Run tests" under "Setup and Run" in the Table of Contents of the Readme.
**Description**
The "Table of Contents" section in the Readme has the "Run Tests" link not working. It shows error 404.
As a contributor I want you to fix this issue.

**Acceptance Criteria**

- [ ] Update required

**Definition of Done**

- [ ] All of the required items are completed.

- [ ] Approval by 1 mentor.

**Estimation**
   atmost 30 minutes

**Note**
This issue will be assigned  September 1st, 2020 onwards.

### PR DESCRIPTION
**Pull request by Abjcodes**
### Description

Fixed run tests link error in Readme.me and updated the file as part of the OSH.

Fixes #784 

### Type of Change:

- Documentation

### How Has This Been Tested?

Found out run tests were not linked (missing # sign) in the readme file.
Fixed it by adding # before runtests and tested it by previewing it.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by yashasvimisra2798 — APPROVED** [review]

**Comment by yashasvimisra2798** [comment]
Good work @Abjcodes :)

**Review by PrashanthPuneriya — APPROVED** [review]
LGTM :)

**Comment by Abjcodes** [comment]
@yashasvimisra2798 @PrashanthPuneriya Thank you for the quick response and review

**Comment by Abjcodes** [comment]
@yashasvimisra2798 @PrashanthPuneriya Can this PR be merged or should I change anything before the final review?

**Comment by yashasvimisra2798** [comment]
@Abjcodes the PR gets merged after OSH ends. Your PR does not require any changes.

**Review by vj-codes — APPROVED** [review]
@Abjcodes Tested this PR , run tests link works great  🎉 
Thus label updated to `Status ready to merge`

**Review by isabelcosta — APPROVED** [review]
Great change @Abjcodes !
Thank you for your contribution 🎉

**Pull request merged**
