### PR TITLE
Add support to read environment variables

### LINKED ISSUE #21: Add support for using environment variables
## Description
As a developer,
I need load environment variables,
so that I can protect sensitive app data and load app configuration.

In this way, we can avoid hardcoded app configurations.

### Update [Required]
- [x] Remove configuration selection inside of run.py file
- [x] Define environment file and base variables (e.g.: APP_SETTINGS, SECRET_KEY, ...)

## Definition of Done
- [x] All of the required items are completed.
- [x] PR should be sent to the `gsoc18-code` branch.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description

- Currently reading `SECRET_KEY` and `ENVIRONMENT_CONFIGURATION` from environment variables;
- Updated README to inform of what variables to use on `.env` file;
- Raising error with environment configuration is not in these values: `dev`, `test` or `prod`;
- Updated `test_app_config.py` according to changes.

With these changes, we can set sensitive data on the `.env` file and import them without hardcoding it on the code

Fixes #21 

### Type of Change:
- Code
- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

- Ran unittest `test_config_app.py` (fixed tests according to this change)
- created `.env` file with exported with different types of configurations, to test if the app only accepted `dev`, `test` and `prod` how it should

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Dilu9218 — APPROVED** [review]

**Review by m-murad — CHANGES_REQUESTED** [review]
@isabelcosta 
please include a sample `.env` file in the repo. 
In `readme.md` write the steps that the user will need to follow to update the `.env` file.
Lastly, include the .env file in the `.gitignore` file.

**Comment by m-murad** [comment]
Also, remove the sample `.env` file from `readme.md`

**Comment by isabelcosta** [comment]
@m-murad 

the `.env` file is already on README, so I should remove from it, add the template and then add it again to .gitignore? Won't that create an extra step everytime we want to add a new environment variable to the template?

Instead, should I create a file such as `.env_template`, that is updated everytime a new env variable is needed?

**Comment by m-murad** [comment]
Will explain this in the 1:1

**Comment by isabelcosta** [comment]
@m-murad changes to the README.md file done

**Review by m-murad — APPROVED** [review]

**Pull request merged**
