### PR TITLE
feat: use python-dotenv to automatically load env vars from .env file

### LINKED ISSUE #281: Use python_dotenv to load environment variables
This is a small feature suggestion, one of those that require minimal effort but greatly increase out productivity and happinees :)

### Currently
In `requirements.txt` we already have `python-dotenv` listed, but...we're not using it. Environmental variables have to be exported manually from `.env` file.

### What I suggest?
Adding a few lines of code (look #282) and make life easier

Together with this issue I'm submitting a PR (look below)
If it gets merged, it will let us all benefit from it :)

### PR DESCRIPTION
**Pull request by bartekpacia**
### Description
Added a few lines that automatically load .env file. Simple but saves a lot of time!

fixes #281

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Manually. It's very simple and *just works*.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by bartekpacia** [comment]
@isabelcosta  @xprilion I think this is very small yet useful change. What do you think?

**Comment by SanketDG** [comment]
@bartekpacia This is definitely something we need, I was thinking this already happened because of how it's mentioned in the docs.

So right now, changing `.env` does nothing essentially?

**Comment by isabelcosta** [comment]
@SanketDG I only work with `.env` and it works fine. I haven't seen anyone else saying it does not work, without this change. But if you say we need it 🤷‍♀️ we have 2 people then saying that cc @bartekpacia

**Comment by bartekpacia** [comment]
I need to fix my local install of mentorship-backend and then will test this.

**Comment by SanketDG** [comment]
> I only work with `.env` and it works fine. I haven't seen anyone else saying it does not work, without this change.

@isabelcosta @bartekpacia https://flask.palletsprojects.com/en/1.1.x/cli/#environment-variables-from-dotenv

Guess this already happens when using `run`

**Comment by vj-codes** [comment]
Closing as python_dotenv works as expected

**Pull request closed without merging**
