### PR TITLE
Enforce PEP8 standards in codebase

### LINKED ISSUE #178: Refactor codebase according to PEP8 standards
## Description
As a developer,
I need the codebase to follow PEP8 standards,
so that I can read and maintain it with less effort.

### Update [Required]
- [ ] Refactor entire codebase to pass flake8 checks

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by iulianav**
### Description
Refactor entire codebase to follow PEP8 standards except for a few checks(missing-docstring and cyclic-import which I added in `.pylintrc` for now because due to some bugs in Pylint they cannot be skipped in the codebase directly via comments; I also explicitly omit `duplicate-code` checks (R0801) when invoking Pylint because this should be dealt with more urgently and because of the same bugs it cannot be skipped in the codebase where it UNREASONABLY appears). Reformat code using autopep8.

Fixes #178

### Type of Change:

- Quality Assurance

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by iulianav** [comment]
@isabelcosta please have a look if you can and let me know if you agree of this code layout style before I refactor any further. Thank you! :D

**Comment by isabelcosta** [comment]
Cool @iulianav ! And thank you on working to improve the code quality :)

Please create an issue so that you can link it to this PR (e.g.: `Fixes ####`), using the "User Story" template. I already left a note to relate to the automated liniting issue (to keep history).

I read a bit about [PEP 8 -- Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/#code-lay-out), to understand your changes, as soon as I take some time to review PRs I'll check this one ;)

**Review by isabelcosta — COMMENTED** [review]
@iulianav Just took a look and for me this is fine, feel free to continue improving the code :)
Thank you so much for your contribution 🎉

**Comment by iulianav** [comment]
@isabelcosta I tried to run [yapf](https://github.com/google/yapf#can-i-use-yapf-in-my-program) formatter ( owned by Google open-source ), but I did not like how it made it look even with the 'google' style option and for some reason it never reformatted the long lines to less than 80 characters despite the code clearly showing that it should... so i will stick to manual refactoring :(

**Comment by isabelcosta** [comment]
@iulianav Oh, I didn't even know about that tool. I was already thinking that this would be a lot of manual work. If you want, first take your time first for your other commitments, and then we can talk about this again.

**Comment by iulianav** [comment]
@isabelcosta there is another tool called black that looks promising. I will give it a try too :)

**Comment by ramitsawhney27** [comment]
Hi, good work on this PR. @isabelcosta, I feel we should enforce flake8 checks for the PRs and existing code. That rates the code out of 10 and suggests changes to make our code more readable and compliant with PEP8.

**Comment by isabelcosta** [comment]
@ramitsawhney27 sure I agree too! So should we approve and merge this https://github.com/systers/mentorship-backend/pull/174 already even if it takes time for @iulianav to refactor? If you think thats appropriate just say it and I'll merge it. You can leave a review there. 
This is "in progress" because @iulianav is doing a big refactoring already compliant with PEP8.

**Comment by ramitsawhney27** [comment]
We can merge @iulianav's code once it passes all the tests and has a rating > 7.5 on flake8 for all python modules. @iulianav can check the same and push when we're at that stage, this way we won't have to replicate the effort over and over.

**Comment by isabelcosta** [comment]
Ok @ramitsawhney27 ! Thank you so much for your input 🎉

**Review by ramitsawhney27 — COMMENTED** [review]
Great work! Could you run pylint on all the files and fix any files that have a score of less than 8? The files with lower scores would have the reasons for deducting the score.

**Comment by iulianav** [comment]
@ramitsawhney27 sure! But isn't flake8 enough? It's just a different linter
?

**Comment by iulianav** [comment]
@isabelcosta I saw some PRs that try to add Pylint as main linter. So should I delete the other PR that adds flake8?

**Comment by isabelcosta** [comment]
@iulianav you are working on this, if the decision is to go with pylint instead of flake8 I think you should do it, because you were already working on this. @ramitsawhney27 can you help here, deciding about the flake8 VS pylint thing?

**Comment by iulianav** [comment]
@isabelcosta yes, I would like an update because when I run pylint on the files that I checked with flake8 they seem to get a low score. Both linters follow PEP8, but they seem to compute the scores differently so I would have to redo all the work.

**Comment by ramitsawhney27** [comment]
pylint is better. To avoid redoing the work, you can use autopep8 (https://pypi.org/project/autopep8/).

**Comment by iulianav** [comment]
@ramitsawhney27 ok thanks!

**Comment by iulianav** [comment]
@ramitsawhney27 even after I run autopep8, the app folder for example and all its content get a 3.25/10 score. This will take a while to fix.

**Comment by ramitsawhney27** [comment]
Yes, that is there. You can try the aggressive mode, but some of the fixes will have to be manual. I've done that as well. An IDE like PyCharm can also help with the linting.

**Comment by iulianav** [comment]
@ramitsawhney27 i used double and triple aggressive mode but it was the same. I will focus on manual fixes as i was dissatisfied on how pylint plugins work so far with yapf and other code formaters.

**Comment by iulianav** [comment]
@ramitsawhney27 @isabelcosta this should be ready. If `missing-docstring`, `duplicate-code` and `cyclic-import` checks are disabled for now (until fixed) when running Pylint, the score is 10.

**Comment by iulianav** [comment]
@ramitsawhney27 @isabelcosta also, I am not sure why codacy checks are not passing for places in the code that I did not change, but seems to pass for other PRs.

**Comment by isabelcosta** [comment]
@iulianav those checks are fixed through configuration Codacy. Don't worry about that, its something from other commits.

**Comment by isabelcosta** [comment]
@iulianav I merged two PRs that generated merge conflicts in your PR, can you please solve them so that I can review and merge your PR again? and squash commits in the end

**Comment by iulianav** [comment]
@isabelcosta right away!

**Comment by iulianav** [comment]
@isabelcosta done.

**Comment by isabelcosta** [comment]
@iulianav thank you for all this work. There's another PR that would have conflicts with this one and would replace hardcoded messages for constants #186 . Would you mind that I merge the other PR, before yours, and then you would fix the merge conflicts? Because that PR would undo some of your refactorings for example regarding the replacement of `'` or `"` on strings. What do you think?

**Comment by iulianav** [comment]
@isabelcosta sure, no problem!

**Comment by isabelcosta** [comment]
Thank you for your patience @iulianav

**Comment by isabelcosta** [comment]
@iulianav #186 was merged, you can continue your work here! Thank you so much for your patience :)

**Comment by isabelcosta** [comment]
Will close this due to inactivity. Thank you so much for your contribution @iulianav you helped us shining a light on this issue :) Feel free to re open, if you want to continue work here

**Pull request closed without merging**
