### PR TITLE
send mentorship relation request api fix

### LINKED ISSUE #487: http 500 when sending an request without containing the logged user
**Describe the bug**

When I tried sending a mentorship request, where the user was not involved not as a mentor nor as a mentee, I got the error 500.

**To Reproduce**

Have at least 3 users signed in.
Make User 1 send request with mentor and mentee id, of User 2 and User 3 (not including User 1)

1. Log in as User 1
2. Send request using IDs from existing users (except User 1)
3. See "Internal Server Error" error (error log below)

**Expected behavior**

Error should be returned with a message, saying the user was not involved in the request.

**Screenshots**

Error thrown:
```
172.17.0.1 - - [09/Mar/2020 00:37:33] "POST /mentorship_relation/send_request HTTP/1.1" 500 -
[2020-03-09 00:38:16,892] ERROR in app: Exception on /mentorship_relation/send_request [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 101, in wrapper
    return fn(*args, **kwargs)
  File "/dockerBuild/app/api/resources/mentorship_relation.py", line 106, in post
    send_email_new_request(user_sender, user_recipient, notes, sender_role)
  File "/dockerBuild/app/api/email_utils.py", line 145, in send_email_new_request
    user_recipient_name=user_recipient.name,
AttributeError: 'tuple' object has no attribute 'name'
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**

I used Docker to run the program.
The error seems to come from [this line in the code](https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/email_utils.py#L122), although the problem must come from previous lines in [this function](https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/resources/mentorship_relation.py#L103).

### PR DESCRIPTION
**Pull request by naveennvrgup**
### Description
Found out that the status 500 was caused due to not returning after finding out bad input. Added a check to fix the condition.

Fixes #487 

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
1. Test through
1. Added test cases

### Checklist:
**Delete irrelevant options.**

- [X] My PR follows the style guidelines of this project
- [X] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [X] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings 
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ramitsawhney27 — COMMENTED** [review]
Please squash your commits for easy maintenance of history.

**Comment by naveennvrgup** [comment]
> Please squash your commits for easy maintenance of history.

I hope with github having the feature of squash and merge it feels redundant to sqaush. Also if any changes are suggested then we have to add more commits, that means more squashing. So I think better to leave it like this for now.  :smiley_cat:

**Comment by isabelcosta** [comment]
@naveennvrgup I agree it is not completely necessary from your end to do it. If you do it great, if not, [we can do it](https://github.com/anitab-org/mentorship-backend/wiki/Maintainer-Guidelines) and still, we will have the git history here in your PR.

@ramitsawhney27 is this the only comment you have for this PR? If so can you approve it? I want to test it still, then I can approve.

**Review by ramitsawhney27 — APPROVED** [review]

**Review by isabelcosta — APPROVED** [review]
Great work @naveennvrgup 🎉 
Thank you for your contribution!

**Pull request merged**
