### PR TITLE
Correct setting up virtual env for bash users

### LINKED ISSUE #981: Problem in Readme Setup instructions for bash instructions
**Describe the bug**

The setup instructions in the readme file for Git bash users has an error.

**To Reproduce**
The steps to activate the virtual environment for Git Bash users says:
`source /venv/Scripts/activate`

**Expected behavior**
The given command should activate the virtual environment, however it doesn't do so.

**Screenshots**
mentorshipReadmeError

**Desktop (please complete the following information):**
 - OS: [Windows]

**Additional context**
I would like to add a PR for the correct command

### PR DESCRIPTION
**Pull request by Ayush23Dash**
### Description

Corrected Readme for virtual environment setup for bash users.

Fixes #981

### Type of Change:

- Documentation

**Code/Quality Assurance Only**

- This change requires a documentation update (software upgrade on readme file)

### Checklist:

- [ ✔️] I have performed a self-review of my own code or materials
- [ ✔️] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [✔️ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Ayush23Dash** [comment]
@Techno-Disaster  please have a look at it

**Review by vj-codes — APPROVED** [review]
@Ayush23Dash congrats on your first contribution , LGTM 🎉 

_The changes made in this PR were tested locally. Following are the results:_

1. Code review - Done 
2.  All possible responses (positive and negative tests) were tested as below:

- _Before_  - 
image
 **Expected Result:** The command should work
**Actual Result:** The command is not working
- _After_   -
image
 **Expected Result:** The command should work
**Actual Result:** The command is  working

**Comment by techno-disaster** [comment]
LGTM but I don't get how the test coverage increased? AFAIK we haven't touched the other files.

**Comment by Ayush23Dash** [comment]
> LGTM but I don't get how the test coverage increased? AFAIK we haven't touched the other files. 

Maybe it is due to the fact that I created a branch of my own other than the develop branch and PR'ed from that branch to the develop branch of mentorship-backend

**Review by techno-disaster — APPROVED** [review]

**Comment by vj-codes** [comment]
Adding label ready to merge since testing is done above

**Comment by devkapilbansal** [comment]
> LGTM but I don't get how the test coverage increased? AFAIK we haven't touched the other files.

@Techno-Disaster the coverage increased because in past some commits the coverage of this repository is decreased and and this branch is not up-to-date with this repository

**Comment by isabelcosta** [comment]
Thank you all for reviewing @Techno-Disaster @vj-codes and taking a look at the checks @devkapilbansal !

**Comment by isabelcosta** [comment]
Congrats on your first PR merged for this project @Ayush23Dash 🎉

**Pull request merged**
