### PR TITLE
Create script commands for flask

### LINKED ISSUE #78: Create script commands for flask
## Description
As a developer,
I need flask script commands,
so that I can configure the app before running it.

This can be used to create the first user `admin` without the need to use the full app and verify the email.

**Functions to create:**
- create admin
- run tests
- run test coverage
- run the app
- export swagger and postman json
- TBD

### Update
- [ ] Create manage.py script with the functions described above

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by LordGameleo**
### Description
Added a python script manage.py which can be used to do perform multiple commands using arguments given while running it.

Fixes #78 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- It adds easy access to make superuser (first user admin), running server, testing whole app or specific parts all through command-line.

### How Has This Been Tested?
'''python -m unittest dicover tests'''
- Tested it by using these features manually

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by LordGameleo** [comment]
@isabelcosta Please approve the issue and reopen it.

**Comment by LordGameleo** [comment]
@isabelcosta  please reopen this PR.

**Comment by agarwalrounak** [comment]
Hi @LordGameleo! I think you should squash the commits into one. 

Also, you don't need to commit every change separately. I see that you have performed a separate commit for almost every change made. You could make all the necessary changes and then perform a single commit.

**Comment by LordGameleo** [comment]
Please Review............ TIA :)

**Comment by CleverFool77** [comment]
@LordGameleo  @agarwalrounak has given review regarding squashing of commits. You can perform this first. Later whenever mentors will get time, they'll review your PR.

**Comment by LordGameleo** [comment]
@CleverFool77 I will :+1:

**Comment by LordGameleo** [comment]
@CleverFool77  @agarwalrounak  is it okay now ?

**Comment by CleverFool77** [comment]
why did you close the PR @LordGameleo ? I think everything was fine.

**Comment by LordGameleo** [comment]
@CleverFool77  I deleted the branch from my local as well as deleted my fork by mistake..... I can not make any changes to this PR..... so I have to make a new one. I will submit new PR with squashed commits and refer this PR to that one.

**Pull request closed without merging**
