### PR TITLE
style: F-strings on Mentorship Relation Resources file

### LINKED ISSUE #740: Use f-strings on Mentorship Relation Resources file
## Description

As a developer,
I need change strings interpolation in User Resources file,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `app/api/resources/mentorship_relation.py` file.

## Mocks

As an example, here:

https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/app/api/resources/mentorship_relation.py#L148-L152

We can use f-strings in this example.

### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for `app/api/resources/mentorship_relation.py` file

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by pavani-17**
### Description

Fixes #740 

Initially, the file contained % formatted strings. These have been modified to f-strings.

### Type of Change:

- Style

### How Has This Been Tested?

I ran the program at multiple instances during and after the change to ensure that it executes properly without errors.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Looks good @pavani-17 👏 thank you so much for your contribution 😄 
Now we just need another review 👐

**Review by SanketDG — CHANGES_REQUESTED** [review]
Ready to merge

**Review by SanketDG — APPROVED** [review]
Ready to merge!

**Comment by devkapilbansal** [comment]
@pavani-17 please solve merge conflicts

**Comment by devkapilbansal** [comment]
@pavani-17 can you please solve the merge conflicts too

**Comment by pavani-17** [comment]
> @pavani-17 can you please solve the merge conflicts too

Can I do it in 2 days? I have a lot of assignments and stuff right now. Sorry for the inconvenience

**Comment by vj-codes** [comment]
@pavani-17 hey please solve the merge conflicts , and squash all your commits.
Also since you've deleted your fork repo , this PR cannot be tested,can you create a new one?

**Comment by vj-codes** [comment]
@pavani-17 hey since you have deleted your fork repository , this PR cannot be either reviewed/tested or merged.
I will close this PR , and make the issue available.Do let us know if you would like to continue again:)
Thank you for your contribution 🎉

**Pull request closed without merging**
