### PR TITLE
[Program: GCI] Add is_available property to user in GET/users

### LINKED ISSUE #232: Show if user is currently on a relation on the GET /users API for each user
## Description

As a developer consuming the backend api,
I need to know if the user is already occupied (in a current relation),
so that I can provide a better experience on the backend, showing the user is not currently available.

The idea is to return for each user entry from GET /users API response, a new value indicating if the user is available for new mentorship relations. For example, if the user is already enrolled in a current mentorship relation then the value should be `false`.

The value returned could had the following JSON key `is_available`.

To do this, the logic will be probably contained on the UserDAO class, and you won't have to add anything to the User API code.

_this issue is intended for the Google Code-in participants, it can be released after the program ends on January 23rd_

## Mocks

The GET /users should have an additional returning value, like this:
```
{
    (...),
    "is_available": true,
    (...)
}
```

### Update [Required]
- [ ] Return a new value on the GET /users API
### Enhancement to Update [Optional]
- [ ] Create at least one test for this new feature

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by ilyamaier**
### Description
- Added is_available property to user model
- Added/changed some tests in `test_api_list_users.py`

Fixes #232 

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
The code was tested using new tests.

### Screenshots:

Tests:

Screenshot (56)

Swagger UI:

Screenshot (57)

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by annabauza** [comment]
Can you please fix tests? I think we might need replace `user['is_available'] = user['need_mentoring'] or user['available_to_mentor']` to `user['is_available'] = user['need_mentoring'] == true or user['available_to_mentor'] == true`, because when `need_mentoring` or `available_to_mentor` it `None` then `is_available` become `None`

**Comment by ilyamaier** [comment]
> Can you please fix tests? I think we might need replace `user['is_available'] = user['need_mentoring'] or user['available_to_mentor']` to `user['is_available'] = user['need_mentoring'] == true or user['available_to_mentor'] == true`, because when `need_mentoring` or `available_to_mentor` it `None` then `is_available` become `None`

Yes. I'll fix that today :)

**Comment by annabauza** [comment]
Thanks you :)

**Comment by ilyamaier** [comment]
> Can you please fix tests? I think we might need replace `user['is_available'] = user['need_mentoring'] or user['available_to_mentor']` to `user['is_available'] = user['need_mentoring'] == true or user['available_to_mentor'] == true`, because when `need_mentoring` or `available_to_mentor` it `None` then `is_available` become `None`

@annabauza I fixed the tests. The code you addressed was working fine and it returned `False`, but the actual problem was that there was another user added in #391, so that's why it returned an error. :)

**Pull request merged**
