### PR TITLE
Create Integrating_third_party_authentication.md

### LINKED ISSUE #761: Design a solution for integrating third party apps authentication.
## Description
As a contributor, I need you to design a probable solution for integrating third-party apps authentication.
So that end-user can log in from other social media platforms and third-party apps.

Design a probable solution for integrating third-party apps authentication in the app and submit as a markdown file under the “docs” folder.

#### Important: The solution must be designed from the backend point of view and you need to make sure it is compatible with the current backend. This ONLY involves designing including code snippets (optional), not hardcore coding.
For context: #719 

#### Note: This issue is labeled for Open Source Hack.
I can assign this issue to you on September 1st as the official opening date for Open Source Hack. Please free to check out other issues in the meantime. Program website: https://anitab-org.github.io/events/open-source-hack/

### Update [Required]
- [ ] Submit as a markdown file under the “docs” folder.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
[4+] hours

### PR DESCRIPTION
**Pull request by titiksha01**
### Description

I have documented my research on possible solution for integrating third party authentication

Fixes #761

### Type of Change:

- Outreach/Research

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by paritoshsinghrahar** [comment]
@titiksha01 You have done a promising job on this Issue. Really GREAT!! LGTM! 😃💯

**Review by paritoshsinghrahar — APPROVED** [review]
LGTM.

**Comment by paritoshsinghrahar** [comment]
@isabelcosta This can be merged.

**Comment by titiksha01** [comment]
> @titiksha01 You have done a promising job on this Issue. Really GREAT!! LGTM! 😃💯

Thank you so much!

**Review by SanketDG — COMMENTED** [review]
This is pretty good for a proposal, I am not sure whether this project will ever be interested in integrating a 3rd party service like Auth0.

There are also open source alternatives to `Auth0` that we should definitely take a look at.

In general, given the effort that it takes to integrate a oAuth Provider like google or twitter, I'd be in favour of doing them manually over anything.

**Comment by vj-codes** [comment]
This PR solves #341

**Comment by epicadk** [comment]
> This PR solves #341

I think that issue is the actually implementation for third party auth whereas this is just research for it. Also I think this was a OSH pr and the linked issue has been closed. I think we can close this pr as well. @vj-codes

**Comment by vj-codes** [comment]
@epicadk #341 is labeled as outreach it's just research
#719 deals with implementing it which was done during last gsoc

**Review by epicadk — COMMENTED** [review]
💯

**Comment by vj-codes** [comment]
@epicadk @devkapilbansal I'm not sure if this should be merged to develop, as this PR is general documentation and can be suited more as a blog .
Check Isabel's comment for similar issue [here](https://github.com/anitab-org/mentorship-backend/pull/894#issuecomment-803355841)
If agreed we should close this

**Comment by epicadk** [comment]
@titiksha01 Thankyou for your contribution 🎉. I think the maintainers have decided this would be more suited for a blog post rather than documentation.

**Comment by devkapilbansal** [comment]
@titiksha01 you can write a blog on this and then ask the maintainers to add that in Organization's Medium Account.

**Comment by titiksha01** [comment]
@epicadk @devkapilbansal  okay sure... Thank You!

**Pull request closed without merging**
