### PR TITLE
Adding code quality badges to README file

### LINKED ISSUE #754: Add code quality badges to README file
## Description
As a contributor,
I need to know the status of the code quality of major branches (develop and master).
So that I can be aware of the code quality as I land on the main page of the repository through README.

## Mocks
As done on mentorship-android's repository.
mentorship-android

### Update [Required]
- [ ] Add two badges (develop and master) to the Mentorship Backend [README file](https://github.com/anitab-org/mentorship-backend/blob/develop/README.md).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1-2] hours

### PR DESCRIPTION
**Pull request by ankitwarbhe**
### Description

> Added Code quality badges for master and develop branch.

Fixes #754 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by SanketDG — CHANGES_REQUESTED** [review]
We use Github Actions now, so there is no point putting the Travis builds in here

**Comment by ankitwarbhe** [comment]
Thank you @sanketDG I have already talked about this in issue section #754 and was told to add Travis badge 

Also, would you guide me on what to do next?  If there's no point in adding Travis badge.

**Comment by paritoshsinghrahar** [comment]
@SanketDG essentially this issue came first and that's why I felt it conflicts with the issue #773. And the contributor in question has already made a PR. Like so wouldn't it be unfair.

**Comment by SanketDG** [comment]
I still don't see the issue though. Because Travis is not about code quality anyway, I am up for adding Github Actions badge to the README (I don't know if that exists at all)

**Comment by paritoshsinghrahar** [comment]
> I still don't see the issue though. Because Travis is not about code quality anyway, I am up for adding Github Actions badge to the README (I don't know if that exists at all)

Yes, I agree Travis isn't about code quality, the context of the Issue was essentially changed because Codacy required Ankit to be a part of the organization. So I asked him to go with Travis only. So what exactly needs to be done now?

**Comment by SanketDG** [comment]
There are always badges to be added, I would love to see a coverage and dependencies badge, if you can't add anything else, does github actions really not have a badge though? @paritoshsinghrahar @ankitwarbhe

**Comment by ankitwarbhe** [comment]
> There are always badges to be added, I would love to see a coverage and dependencies badge, if you can't add anything else, does github actions really not have a badge though? @paritoshsinghrahar @ankitwarbhe 

In that case the issue need to be updated properly.

**Pull request closed without merging**
