### PR TITLE
fix:update HTTTP error codes(200 with 201 & 400 with 409)

### LINKED ISSUE #619: Fix: refactor HTTP error codes POST /register for Users service
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to POST /register request,
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA

### Update [Required]
- [ ] 201: Created need to be returned instead of 200: OK if the process is successful 
- [ ] 409: Conflict need to be returned instead of 400: Bad Request if the username or email already exist

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by nandini45**
### Description

Fixes #619

### Type of Change:

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Update Postman API at /docs folder

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nandini45** [comment]
@isabelcosta  my travis check is failing can you tell me what am i doing wrong?
is it because my docker is not updated or anything else?
image

**Comment by mtreacy002** [comment]
Thanks, @nandini45 for doing it so fast. Just a hint on Travis. When you click the details on the right side of Travis you could see the travis log including why it has failed. From what I can see you forgot to replace the code on the related tests. see ([review comment below](https://github.com/anitab-org/mentorship-backend/pull/620#pullrequestreview-424028570))

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
Just to point out the cause of travis failed build. You also need to change the status code on the related tests used with user registration as per shown on travis log below

Screen Shot 2020-06-04 at 8 44 05 am
Screen Shot 2020-06-04 at 8 44 13 am

**Review by mtreacy002 — COMMENTED** [review]
Can you please remove the space between `#` and `619` on the description of the PR?
Screen Shot 2020-06-04 at 10 56 17 am
That way the issue will be automatically link to the PR and once the PR is approved, the issue will get automatically closed. With the `space in between, it won't get linked.

**Comment by nandini45** [comment]
@mtreacy002  can you tell me what is the mistake i am doing? my travis check is failing

**Comment by SanketDG** [comment]
@nandini45 If it's still not clear, you have to change the tests too as said in https://github.com/anitab-org/mentorship-backend/pull/620#pullrequestreview-424032309

Scroll down to the bottom of https://travis-ci.org/github/anitab-org/mentorship-backend/builds/694311362 and see the tests have failed.

For every failed test, you would have to go into the respective file and update the test with the new expected change. 

Let me know if this makes sense.

**Comment by mtreacy002** [comment]
> @mtreacy002 can you tell me what is the mistake i am doing? my travis check is failing

Yes, @nandini45 . It is as per @SanketDG mentioned on [his post](https://github.com/anitab-org/mentorship-backend/pull/620#issuecomment-640101556) and as per I have pointed on [my post too](https://github.com/anitab-org/mentorship-backend/pull/620#pullrequestreview-424028570)

**Comment by nandini45** [comment]
i get what you are saying but i previously asked you on zulip too i am not able to install the requirements.  @SanketDG 
i think i will just set it up again

**Comment by SanketDG** [comment]
@nandini45 Yes, please ask on Zulip if you are facing issues with the development setup.

**Comment by isabelcosta** [comment]
@nandini45 why is this closed?

**Pull request closed without merging**
