### PR TITLE
[Program: GCI] Add comment task database table

### LINKED ISSUE #425: comment a task
# Description:

**Is your feature request related to a problem? Please describe.**
As a User I can not comment task which makes completing task harder.

**Describe the solution you'd like**
As a User I would like to comment a task so I could ask/answer related to task questions.

**Describe alternatives you've considered**
Alternative is using chat.

**Additional context**
We need to refactor current tasks to be able to add comments to tasks.

# PRs:
[398](https://github.com/systers/mentorship-backend/pull/398)
[356](https://github.com/systers/mentorship-backend/pull/356)
[368](https://github.com/systers/mentorship-backend/pull/368)

### PR DESCRIPTION
**Pull request by ilyamaier**
### Description
- Added a new model and a DAO for task comments, including:
    - get task comments by id, task_id, user_id methods
    - create, delete and modify methods
    - some new messages
    - tests for all DAO methods

[Task link](https://codein.withgoogle.com/dashboard/task-instances/5039890899664896/)

Fixes #425

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
The code was tested with new tests on my laptop.

### Screenshots:
Screenshot (55)

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by annabauza — APPROVED** [review]

**Comment by annabauza** [comment]
Can you please also resolve conflicts here? I can do this if you feel there are part you are not sure about. Thanks!

**Comment by ilyamaier** [comment]
> Can you please also resolve conflicts here? I can do this if you feel there are part you are not sure about. Thanks!

@annabauza I resolved the conflicts. Should I squash all the commits?

**Comment by ilyamaier** [comment]
> Can you please also resolve conflicts here? I can do this if you feel there are part you are not sure about. Thanks!

@annabauza I will resolve travis conflicts in a moment.

**Comment by annabauza** [comment]
And test fail if you don't mind :)

**Comment by ilyamaier** [comment]
> And test fail if you don't mind :)

I fixed that :)

**Comment by annabauza** [comment]
Super star!

**Pull request merged**
