### PR TITLE
Remove unnecessary comments

### LINKED ISSUE #468: Remove unecessary comments
## Description

There is some unnecessary comment in `app/schedulers/complete_mentorship_cron_job.py` file.
These should be removed

### Update [Required]
- [ ] Remove uncessary comments from `app/schedulers/complete_mentorship_cron_job.py`

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

### PR DESCRIPTION
**Pull request by sayashraaj**
### Description
Removed end comments not required

Fixes #468 

### Type of Change:

- Code

- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Comment removal was checked on my forked repository of this repository

### Checklist:

- [YES] My PR follows the style guidelines of this project
- [YES] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by isabelcosta** [comment]
@sayashraaj on the PR description it should be `Fixes #468`. Can you fix that please? Also, can edit the title of the PR to be more clear?

**Comment by mayburgos** [comment]
@isabelcosta I edited the issue link to appear correctly. :)

**Review by isabelcosta — APPROVED** [review]
Thank you for your contribution @sayashraaj 🎉

**Comment by sayashraaj** [comment]
Thank You for providing me this opportunity to contribute to your open source project! I hope to continue working for AnitaB.org under Gsoc2020!

**Pull request merged**
