### PR TITLE
Base architecture and features

### LINKED ISSUE #4: Create an API to register a new user.
## Description
Create an API using which the user can register on the platform.

- Required fields: email, username, password, name, security question, security answer, terms and conditions check
- Error message specifying what is wrong with the POST data. E.g.: if the users do not check terms and conditions, an error message must be returned indicating that the user must have this checked
- Endpoint: POST /register
- Password must be saved as a hash, and NOT in plain text

### Update [Required]
- [ ] A new user is able to register on the system.

## Definition of Done
- [ ] PR should be sent to the `gsoc18-code` branch
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 hours

### LINKED ISSUE #6: Create an API to login in the system.
## Description
Create an API so that a user who has verified his/her email is able to log in. On successful login, the API should return a JWT which will be required to make further requests.

### Update [Required]
- [ ] User is able to login.
- [ ] A JWT is sent to the user

## Definition of Done
- [ ] PR should be sent to the `gsoc18-code` branch
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 hours

### LINKED ISSUE #8: Create an API to edit User profile
## Description
Create an API which enables a user to edit his/her profile.

API:
- POST /user = Update my profile
- GET /user = Checking my profile

Editable fields:
- bio; username; skills; interests; slack_username; occupation; need_mentoring; available_to_mentor; location; social_media_links; resume_url; photo_url.

### Update [Required]
- [ ] User is able to update items in the profile.

## Definition of Done
- [ ] PR should be sent to the `gsoc18-code` branch
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 hours

### LINKED ISSUE #9: Create an API to get all users
## Description
Create an API that will allow any user to get a list of all the users who have verified their email ids.

- GET /users => Get all users
- GET /users/verified OR GET /users?verified=1 => Get verified users with new endpoint or query param

### Update [Required]
- [ ] List of all users is retrived.
### Enhancement to Update [Optional]
- [ ] List of all users unpaired users is retrived.
- [ ] List of all user in a mentor/mentee relationship is retrived.

## Definition of Done
- [ ] PR should be sent to the `gsoc18-code` branch
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 hours

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description
This pull request contains the base architecture of the Mentorship System backend and 4 main features.

Fixes #4 
Fixes #6  
Fixes #8  
Fixes #9  

Main action items:
- User registration, with the agreed required fields = POST /register -> issue #4
- 1st User is the admin
- Only Admin Users can assign a new admin = POST /admin/new (while authenticated)
- User can update its profile (fields not filled on registration, except for the name) = PUT /user (while authenticated) -> issue #8 
- User can see its own profile on GET /user (while authenticated)
- User can see others profile on GET /users/{user_id} (while authenticated)
- List all users GET /users -> issue #9
- List verified users GET /users/verified -> issue #9
- User’s password is saved a hash, instead of being saved in plain text
- User can login with {email, username}+password into the system (implemented with JWT) -> issue #6
     - POST /auth -> request body = {username:"xxxx", password:"xxxx"} -> this returns an access_token to be used in the header for endpoints where authentication is required
- User can change its password on POST /user/change_password (while authenticated)
- Swagger Documentation accessible on root endpoint (http://localhost:5000/)
- Requirements.txt with the virtual environment dependencies
- README.md updated

### Type of Change:

- Code
- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

- I run the backend on PyCharm. Entry point is `run.py` file.
- I'm still looking for a way to run on the terminal, but I'm getting the following error: `ModuleNotFoundError: No module named 'app'`. To run on the terminal I use `python -m app.run` on mentorship-backend folder.

- This still does not have tests, but I've been testing the backend using [Postman](https://www.getpostman.com/). You can check the Swagger documentation on the main endpoint http://localhost:5000/

- `requirements.txt` has the project dependencies for the virtual environment. README.md file has the instructions to create the virtual environment.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by m-murad** [comment]
@isabelcosta 
Codacy has reported some errors
Can you please address them

**Comment by isabelcosta** [comment]
@m-murad Yes! I will fix them

**Comment by m-murad** [comment]
There are still 6 Codacy issues, please fix them and this will be merged. 
@Dilu9218 Can you please review this

**Comment by isabelcosta** [comment]
@m-murad fixed the remaining Codacy issues

**Comment by Dilu9218** [comment]
There are 28 commits, it is good if we could squash them right? Not into one, to few commits according to task. @m-murad @isabelcosta

**Comment by isabelcosta** [comment]
@Dilu9218 @m-murad I can try to do that at least for the Codacy warnings commits.

**Comment by Dilu9218** [comment]
Good. According to functionalities we can squash the others too right?

**Review by Dilu9218 — CHANGES_REQUESTED** [review]
commented to squash commits

**Comment by isabelcosta** [comment]
@Dilu9218 your suggestion is that I squash all the other commits, before the codacy warnings, into one commit or try to group commits according to the feature in common?

**Review by m-murad — APPROVED** [review]

**Comment by Dilu9218** [comment]
@isabelcosta  Try to group commits according to the feature in common.

**Comment by isabelcosta** [comment]
@Dilu9218 I squashed some initial commits. Is it ok how it is now?

**Review by Dilu9218 — APPROVED** [review]

**Pull request merged**
