### PR TITLE
fixed broken links in the heroku app

### PR DESCRIPTION
**Pull request by surbhigoel191**
### Description

Fixes # 948

### Type of Change:

           User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

Before
Screenshot (249)

After
Screenshot (250)

### CODE REVIEW

**Comment by surbhigoel191** [comment]
Can someone please tell what needs to be done if any mistake in this PR? TIA

**Review by isabelcosta — CHANGES_REQUESTED** [review]
Thank you for your contribution @surbhigoel191 👏 🎉 Great work!
Your change in `app/api/api_extension.py` is 💯 correct!

The other files changes, however, are not needed for this PR. This happened because you did not create a branch for this specific change. So you have changes meant to solve another issue. Can you undo the changes from the other 2 files, on you only have `app/api/api_extension.py` file change in this PR?

Can you also add a screenshot of the app running on your local environment and with the link fixed?

**Comment by surbhigoel191** [comment]
> Thank you for your contribution @surbhigoel191 👏 🎉 Great work!
> Your change in `app/api/api_extension.py` is 💯 correct!
> 
> The other files changes, however, are not needed for this PR. This happened because you did not create a branch for this specific change. So you have changes meant to solve another issue. Can you undo the changes from the other 2 files, on you only have `app/api/api_extension.py` file change in this PR?
> 
> Can you also add a screenshot of the app running on your local environment and with the link fixed?

Thanks a lot. I will try to revert back my last commit now.

**Comment by surbhigoel191** [comment]
Added the screenshots and reverted last commit.

**Review by vj-codes — CHANGES_REQUESTED** [review]
@surbhigoel191 the last 2 lines in the After Screenshot i.e
"The main repository..." and  "  The android client...." are still repeating in the code , can you please remove them and squash all your commits ? Then you're done :)

**Comment by surbhigoel191** [comment]
Can I remove this PR and add a new one? This time I will be creating separate branch for every issue :)
I am having a little hard time in squashing the already pushed commits.

**Comment by vj-codes** [comment]
@surbhigoel191 sure!

**Pull request closed without merging**
