### PR TITLE
docs: add user search default values to Swagger UI

### LINKED ISSUE #612: Mention on Swagger UI the default values regarding pagination
## Description

As a developer/tester,
I need to know what I should expect as default values of pagination,
so that I can properly test is or understand the values used if I don't give any.

## Mocks

Here's an example of how the default values could appear there:

image

### Update [Required]
- [ ] Adds default values used for pagination to the Swagger UI.
- [ ] Update API description to mention that when the listing reached the end, the API simply returns an empty list.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by livrbecca**
### Description
Fixes #612 
Updated code on line 40, added default to to specify page of users and specify number of users per page

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by isabelcosta** [comment]
@livrbecca your code is spot on :) To improve this pull request, I would love to see a description properly filled. Could you please edit the description of the pull request (see 3 dots):

image

Could you write a description of the change, you can look it up on the issue, also make sure to add the issue number in the description with `Fixes #612` this will make a reference in the issue so that when someone goes to the issue you solved, they can see the PR you submitted to it.

**Comment by vj-codes** [comment]
@livrbecca hey can you please update the above changes , won't take a more than a minute !

**Comment by livrbecca** [comment]
Hi, I've updated the changes @vj-codes @isabelcosta

**Review by isabelcosta — APPROVED** [review]
@livrbecca great work! Thank you so much for your contribution 🙌

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Comment by vj-codes** [comment]
Adding label ready to merge , since it's documentation change

**Comment by isabelcosta** [comment]
Thank you so much for your help @vj-codes 🤗 and great work @livrbecca 👏

**Pull request merged**
