### PR TITLE
Refresh Endpoint should mention Refresh token instead of access token

### LINKED ISSUE #932: Refresh Endpoint should mention Refresh token instead of access token
**Describe the bug**

In refresh endpoint (to get new access token), it is mentioned to use in the `Authorization` field's input description, an access token, but it should mention refresh token.

**To Reproduce**

1. Go to 'Users' Section
2. Scroll down to refresh endpoint
3. See access token mentioned there instead of refresh token

**Expected behavior**

API endpoint should mention refresh token instead

**Screenshots**

refresher

### PR DESCRIPTION
**Pull request by tichnas**
### Description

The access token is changed to refresh token in refresh endpoint.

Fixes #932

### Type of Change:

- Code
- Documentation
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Ran `python -m unittest discover tests` which gave OK result.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation
- [x] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by devkapilbansal** [comment]
Looks on the right track :+1:

**Comment by tichnas** [comment]
@devkapilbansal I've updated the screenshot of the manual tests. Please take a look and let me know if there are any other changes required (or should I mark it Ready for review?).

Thanks once again for the guidance and fast replies :)

**Comment by devkapilbansal** [comment]
@tichnas you can mark it for review. I will check soon if the work is completed as required or not

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: 

No change in code, hence no testing needed

**Comment by devkapilbansal** [comment]
@tichnas just try to keep your branch up to date with develop branch. All changes done here are as required.
Thanks a lot for this

**Review by vj-codes — APPROVED** [review]
LGTM 🎉 
Thank you for your contribution @tichnas

**Review by isabelcosta — APPROVED** [review]
Amazing contribution @tichnas ! thank you for working on this :)

**Comment by isabelcosta** [comment]
Just as reference, I tested on 
https://ms-backend-review-pr-936.herokuapp.com/ and I confirm this is correct on Swagger UI:
image

**Pull request merged**
