### PR TITLE
fix: Upgraded Flask_JWT_Extended to ensure all tests passed

### LINKED ISSUE #944: Tests Failing on latest version of PyJWT
**Describe the bug**

PyJWT was updated approx a week ago which results in failing tests on the pull requests.

**To Reproduce**

1. Setup the project as per instructions
2. Run Tests to ensure all tests passed

**Expected behavior**

All tests should pass as expected

### PR DESCRIPTION
**Pull request by devkapilbansal**
### Description

Fixes #944

### Type of Change:

- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- 
### How Has This Been Tested?

Run `python -m unittest discover tests` to ensure all test cases passed.

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by devkapilbansal** [comment]
@vj-codes please review it

**Comment by devkapilbansal** [comment]
A minor change in dependency that will fix all errors related to test

**Review by isabelcosta — APPROVED** [review]
Great work @devkapilbansal thank you so much for fixing this asap 👏 🎉

**Comment by isabelcosta** [comment]
I will merge this since this is a dependency upgrade that is fixing failing tests that are blocking other issues (see #944).
cc @vj-codes @devkapilbansal

**Pull request merged**
