### PR TITLE
fix: http status codes fixed

### LINKED ISSUE #846: Use HTTPStatus instead of hard coded status codes in resources/mentorship_relation.py file
**Describe the bug**
[mentorship_relation](https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/resources/mentorship_relation.py) file has **few routes** that uses hardcoded status codes instead of HTTPStatus.

**To Reproduce**

1. Go to https://mentorship-backend-temp.herokuapp.com/
2. Click on `Mentorship Relation`
3. Scroll down to `/mentorship_relation/{request_id}`

**Expected behavior**
HTTPStatus.XYZ should have been displayed instad of raw status codes

**Screenshots**
image
The above image shows hardcoded status codes. It should show the status in the below format:-
image

**Additional Context**
Also, find whether any such hard coded status codes are used for other routes and fix them.

### PR DESCRIPTION
**Pull request by sreelekha901**
Description

Fixes #846

**Type of Change:**
- Code: Replaced HTTP status codes with messages

**Checklist:**
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by PrashanthPuneriya — APPROVED** [review]
LGTM @sreelekha901 :)

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@sreelekha901 thanks for this PR
Although I saw many endpoints were the status code is hard-coded.

The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Hard coding of HTTP Status Code
    _Screenshot/gif_:  
error_code
error_2

    _Expected Result_:  There should be no instances were the code is hard-coded.
    _Actual Result_: Found some instances of the same
  
3 . Status of PR can be Changed to: Changes Requested

**Comment by devkapilbansal** [comment]
@sreelekha901 although in issue it is mentioned for mentorship _relation file only, but please look at other places too

**Comment by rpattath** [comment]
@devkapilbansal I think it is ideal to stick to changes mentioned in the issue. I think it would be better to open new issues for other endpoints. What do you think @vj-codes @PrashanthPuneriya ?

**Comment by devkapilbansal** [comment]
> @devkapilbansal I think it is ideal to stick to changes mentioned in the issue. I think it would be better to open new issues for other endpoints. What do you think @vj-codes @PrashanthPuneriya ?

@rpattath Okay if that's the case this PR is ready to merge. I will open an issue today that will cover all other endpoints

**Review by devkapilbansal — APPROVED** [review]
@sreelekha901 thanks for this PR
LGTM :+1: 

The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Hard coding of HTTP Status Code
    _Screenshot/gif_:  
    **From develop branch**
From develop branch

     **From this PR**
current

    _Expected Result_:  There should be no instances were the code is hard-coded.
    _Actual Result_: Same as expected




 3. Additional testcases covered: Ran `python -m unittest discover tests` to ensure all test cases covered.

4. Status of PR can be Changed to: Ready to Merge

**Comment by devkapilbansal** [comment]
@PrashanthPuneriya Opened an issue here #923

**Review by vj-codes — CHANGES_REQUESTED** [review]
@sreelekha901 hey please solve the merge conflicts , and after that is done the PR can be merged since it's approved and tested already!

**Comment by isabelcosta** [comment]
@sreelekha901 I will close this PR for now, due to lack of responsiveness. However, if you feel you can return to this issue and continue the work, just let us know and we can reopen this if by that time this issue is not assigned yet 😉 
cc @vj-codes

**Pull request closed without merging**
