### PR TITLE
test: replace hardcoded response values with HTTPStatus

### LINKED ISSUE #969: Use HTTPStatus instead of hardcoded values in tests/tasks and tests/user_journey
## Description
As a developer,
I need to avoid using hard-coded values wherever possible,
so that I can make code more readable and scalable.

### Update [Required]
- [ ] Use HTTPStatus instead of hard-coded response status codes (like in the API) in `tests/tasks` and `tests/user_journey`

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by sankha555**
### Description

This patch replaces the hardcoded response codes in tests/tasks and tests/user_journey with their corresponding HTTPStatus codes. This will help in better readability and scalability.

Fixes #969

### Type of Change:

- Documentation

### How Has This Been Tested?

Ran unittests on local machine and they returned OK status.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@sankha555 you have pushed .DS_Store file which is not required. Please amend your commit after removing it

**Comment by sankha555** [comment]
@devkapilbansal Sorry for that mistake, please take a look now. Thanks!

**Review by devkapilbansal — DISMISSED** [review]
LGTM :+1: 
Thanks @sankha555 for this

Tested locally and verified that all hard coded response values are replaced

The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Replaced hard coded responses in mentioned files
    _Expected Result_:   `tests/tasks` and `tests/user_journey` file shoud not contain hard coded responses
    
4. Additional Comments: Run `python -m unittest discover tests` to ensure all tests passed

**Review by vj-codes — DISMISSED** [review]

**Comment by vj-codes** [comment]
Adding label ready to merge since testing is done above

**Comment by isabelcosta** [comment]
@sankha555 actually in this situation, you don't need to call for the value. It's a little detail, that does not need to be there in the code. The `.value` is needed on Swagger UI, for some reason, but within feature code and tests, it does not need.

Can you please try and see if it still works?

cc @vj-codes @devkapilbansal

**Comment by sankha555** [comment]
@isabelcosta made the changes asked. Please take a look at it. Thanks! :)

**Review by isabelcosta — APPROVED** [review]
Awesome work @sankha555 ! thank you for this contribution!

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Pull request merged**
