### PR TITLE
Added docker script to travis with black for auto pep8 linting

### LINKED ISSUE #483: Adding black command to docker-travis script to run automatically on each commit
## Description
As a developer, I would like it if code can be refactored to PEP8 standard automatically every time I commit.
I need to add black to the script within docker/travis,
so that I can ensure code quality of my code changes.
Note: Good reference to start with: https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry

## Mocks)

If we can do this, we can prevent issues in code quality creeping up in our development.

- before adopting black:

Screen Shot 2020-02-29 at 1 16 45 am

- after adopting black:

Screen Shot 2020-02-29 at 1 06 26 am

## Acceptance Criteria
Should not break the system

### Update [Required]
- [ ] Not needed. Black already in pip dependencies
### Enhancement to Update [Optional]
- [ ] Not sure

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
I have modified the Dockerfile to run black and also modified Travis to build docker image on any PR commits. This is so the code changes committed will get automatically formatted to meet pep8 standard. 

Fixes #483 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I tested this in my own repo (forked from develop) which link to own Travis and Codacy space. Here's what I have done:

- I added environment variables on Travis so that it can login to docker.
This was done from inside Travis UI as screenshot below"

Screen Shot 2020-03-25 at 10 00 15 pm

- I added few white lines to run.py (just to test)
- I committed the code change
- I checked on Travis CI the progress and confirm that the code got formatted when travis build docker image

screenshot: Travis build process showing docker was building new image with formatting the code using black.
Screen Shot 2020-03-25 at 9 37 50 pm

Screen Shot 2020-03-25 at 9 38 53 pm

(Note there are other files got reformatted as well as there were few commits after PR #478 that haven't been reformatted).

- There are 2 Travis processes, one on branch and the other is on PR. 

At the moment, since our 'deploy.sh' specifies that the outcome will not be published since it's only a PR (it's not on develop or master branch), the image did not  get pushed to develop as stated in Travis script as 'deploy' branch'. This will hopefully have different outcome if the PR gets merged and trigger Travis on the develop branch. 

screenshot: .travis.yml deploy target branch.
Screen Shot 2020-03-25 at 9 48 18 pm

screenshot: deploy.sh no-publishing on forked repo or other than master/develop branch
Screen Shot 2020-03-25 at 10 48 58 pm

screenshot: successful outcome on branch. 
Screen Shot 2020-03-25 at 8 40 01 pm

screenshot: successful outcome on PR
Screen Shot 2020-03-25 at 8 39 49 pm

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged
- [x] Update requirements.txt - to build docker in travis, MarkupSafe need to be updated to v1.1.1

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works (using Travis)
- [x] existing unit tests pass with my changes (on docker - travis)

### CODE REVIEW

**Comment by mtreacy002** [comment]
@isabelcosta , This is shown as passed on my branch coz I'm using my own "DOCKER_USERNAME" and "DOCKER_PASSWORD" in my Travis environment variables.
Screen Shot 2020-03-25 at 9 54 18 pm

**Comment by mtreacy002** [comment]
Here's where I set the Travis environment for my docker variables..

Screen Shot 2020-03-25 at 10 00 15 pm

**Comment by mtreacy002** [comment]
From the Travis on Mentorship-System we could see that the failed outcome is caused by the missing docker environment variables 
Screen Shot 2020-03-25 at 10 18 07 pm

**Comment by mtreacy002** [comment]
Actually, when I attempted to merge my PR branch to the develop branch in my own repo I noticed that Travis failed to deploy the image regardless of the successful docker build. 🤔 
Screen Shot 2020-03-25 at 11 32 38 pm

I'll work on it tomorrow 😉

**Comment by mtreacy002** [comment]
@isabelcosta or @ramitsawhney27 ... I don't think I can do any other changes from my end since I don't have access to edit anitab-ms-develop branch. When you have time, can you please check this PR? thanks.

**Comment by mtreacy002** [comment]
@isabelcosta and @ramitsawhney27. I just noticed the potential issue for this PR. Black which uses [PEP8](https://www.python.org/dev/peps/pep-0008/) as standard seems to not consider the more recent [PEP612](https://www.python.org/dev/peps/pep-0612/) that allows parameters specification variables or even [PEP589](https://www.python.org/dev/peps/pep-0589/) that allows us to specify TypesDict where we use data: Dict[str, str]. 

Here's the screenshot in this PR of an example where they reformat these occurrences.
Screen Shot 2020-03-31 at 8 14 59 pm

Maybe we should just use Black refactoring manually for now so we can select which one to be accepted as changes. I'm not sure if they can be customise like in pylint with pylint.rc. I'll have to do more research on that. But at least we got that Docker built image in Travis.... 😉

**Comment by mtreacy002** [comment]
i'm especially surprised to see this one... Why did Black do that..... 🤔 💭 😠 
Screen Shot 2020-03-31 at 9 08 03 pm

**Comment by mtreacy002** [comment]
Also, this 58 some commits seems like a not favourable way to do PR. Should I discard this PR, undone all commits (or maybe I can do merge squash in my PR from forked repo 🤔 ...) and just make one final change (now that I now which line of codes actually work for docker build in travis). I might also take out the black reformatting line. if we decide to do it manually. @isabelcosta, pls do share your thoughts. 😉

**Comment by isabelcosta** [comment]
> i'm especially surprised to see this one... Why did Black do that..... 🤔 💭 😠
> Screen Shot 2020-03-31 at 9 08 03 pm

i am still catching up to issues and this one is soooo big that its not on the top of the list.
But I am worried about that change you mentioned @mtreacy002 , that cannot happen to the documentation

**Comment by isabelcosta** [comment]
Oh yes, and type hints are to stay @mtreacy002 . I am sorry if you mentioned this already, I have not read the full discussions yet.

**Comment by mtreacy002** [comment]
> > i'm especially surprised to see this one... Why did Black do that..... 🤔 💭 😠
> > Screen Shot 2020-03-31 at 9 08 03 pm
> 
> i am still catching up to issues and this one is soooo big that its not on the top of the list.
> But I am worried about that change you mentioned @mtreacy002 , that cannot happen to the documentation

I totally agree with you on that. Which is why, I think for now adding Black to automatically reformat code inside docker image build in travis is not the way to go. We could do this as maintenance PR every few commits. And since it will be done manually, we can choose which one to ignore and which one to take in...

**Comment by mtreacy002** [comment]
Do you want me to remove the Black codes in the dockerfile and discard this PR and open a different issue-PR together as docker build in Travis CI? Or just use this PR but remove the Black  auto formatting codes?

**Comment by isabelcosta** [comment]
@mtreacy002 maybe open a new issue and close the other one (issue matching this PR) with a comment explaining the issues you had on doing this with black, the limitations. and close this PR as well then. Can you do that, then create the issue for what you are saying and wait until it is approved and assigned before sending a PR.

what do you think? 

PS: thank you for so many updates and explanations you provided on this PR, this is a very good habit when contributing to Open Source

**Comment by mtreacy002** [comment]
> @mtreacy002 maybe open a new issue and close the other one (issue matching this PR) with a comment explaining the issues you had on doing this with black, the limitations. Can you do that, then create the issue for what you are saying and wait until it is approved and assigned before sending a PR.
> 
> what do you think?

Yep.... I can do that.... Thanks for the advice... @isabelcosta 👍

**Comment by mtreacy002** [comment]
> PS: thank you for so many updates and explanations you provided on this PR, this is a very good habit when contributing to Open Source

Thanks, @isabelcosta .... I'm worried at first to put all these details here coz I'm scared that you'd think I'm being a nuisance. 😆  😂

**Comment by isabelcosta** [comment]
> > PS: thank you for so many updates and explanations you provided on this PR, this is a very good habit when contributing to Open Source
> 
> Thanks, @isabelcosta .... I'm worried at first to put all these details here coz I'm scared that you'd think I'm being a nuisance. 😆 😂

Yes, I receive emails for every little comment 😝 But I really rather this than no comments or updates at all. With this people can see your reasoning and thought process, this is GREAT 👏 and people can help you as you go along with the PR. I even learn from your updates and experience debugging this. So great job! 💯 @mtreacy002

**Comment by mtreacy002** [comment]
> > > PS: thank you for so many updates and explanations you provided on this PR, this is a very good habit when contributing to Open Source
> > 
> > 
> > Thanks, @isabelcosta .... I'm worried at first to put all these details here coz I'm scared that you'd think I'm being a nuisance. 😆 😂
> 
> Yes, I receive emails for every little comment 😝 But I really rather this than no comments or updates at all. With this people can see your reasoning and thought process, this is GREAT 👏 and people can help you as you go along with the PR. I even learn from your updates and experience debugging this. So great job! 💯 @mtreacy002

On this, next time I post a PR request, @isabelcosta do you want me to merge squash the commits instead of lining up all the ones I did in the process like this PR (I'm embarrassed my self to have gone through 58 commits before I can work it out ☺️ )

**Pull request closed without merging**
