### PR TITLE
added TERMS AND CONDITIONS NOT CHECKED response

### LINKED ISSUE #561: 400 Responses does not list "Terms and conditions is false" message
When registering a new user , if Terms and conditions is set to false then we see the expected error message "Terms and conditions are not checked." but this message is not listed under the list of 400 responses.

1. Go to 'Users- register'
2. {
  "name": "testua",
  "username": "testua",
  "password": "testua123",
  "email": "voxij69223@mailop7.com",
  "terms_and_conditions_checked": false,
  "need_mentoring": true,
  "available_to_mentor": true
}
3. Click on 'Execute'
4. Scroll down to 'Responses' 
5. Screenshot (3)

**Expected behavior**

All the error messages should be listed under the 400 error messages

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

### PR DESCRIPTION
**Pull request by Bhavani-Somanchi**
### Description
Listed "terms and conditions are not checked" message

Fixes #561

### Type of Change:

- Code

### How Has This Been Tested?

Found that error "terms and conditions are not checked" is not listed.
Added the response and tested  by running it

github1 2020-09-07 150924

terms and conditions was checked false

github 2020-09-07 150455

response was listed under HTTPStatus.CONFLICT

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by vj-codes** [comment]
@Bhavani-Somanchi hey could you please add a screenshot in `How Has This Been Tested?` section
It'll help the reviewers to approve/review the PR :)

**Comment by Bhavani-Somanchi** [comment]
@vj-codes Sorry for the inconvenience! Required screenshots added.

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: 

Thanks @Bhavani-Somanchi for this contribution

The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  
    _Screenshot/gif_:  
t c_msg

**Review by vj-codes — APPROVED** [review]
Thank you for your contribution @Bhavani-Somanchi  🎉

**Comment by vj-codes** [comment]
Adding label ready to merge since testing is done above

**Review by isabelcosta — APPROVED** [review]
Great work @Bhavani-Somanchi !
Thank you for your contribution 🤗

**Pull request merged**
