### PR TITLE
Design UI for email confirmation

### LINKED ISSUE #768: Design UI for email confirmation
## Description
As a developer,
I need to design a specific UI for email confirmation,
so that I can improve the current UI.

### Context
When a user registers they receive an email confirmation (account activation) link in the email ([current template](https://github.com/anitab-org/mentorship-backend/blob/develop/templates/email_confirmation.html)). This UI should be designed following [AnitaB.org Branding Guidelines](https://drive.google.com/file/d/1QyQrNfGMa5e-3D0obDAGnkHZ1u7nhZ87/view).

## Mocks
Current confirmation email
msemailconf

### Update [Required]
- [ ] Design a specific UI for email confirmation

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by SHITIZ-AGGARWAL**
### Description

providing design for email verification

Fixes #768 

### Type of Change:

- User Interface

#### figma link : https://www.figma.com/file/wQp9Gj2QTaTlMs7nGi5aFo/email-verification?node-id=0%3A1

image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by SHITIZ-AGGARWAL** [comment]
@SanketDG @gaurivn I created a new pull request with the following changes ,please suggest if any changes required : )

**Review by SanketDG — APPROVED** [review]
This looks good.

I personally would like if figma links just exists in issues, and then they are coded and a PR is created. There can always be a new issue that can be created to code this UI.

Also, why not just do a white background?

**Comment by SHITIZ-AGGARWAL** [comment]
@SanketDG I changed the background to white please tell if it is okay so that I can change the description image

**Comment by SanketDG** [comment]
Looks good @SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
@SanketDG is this PR ready for OSH submission

**Comment by SanketDG** [comment]
Sure, I am not sure whether @isabelcosta will merge this in, because this is clearly very temporary work.

Asking @gaurivn to create an issue for the implementation so that someone code this.

Can you also paste the screenshots/UI links in the issue? @SHITIZ-AGGARWAL

**Comment by SHITIZ-AGGARWAL** [comment]
@SanketDG  sure

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: 

@vj-codes please add a label

**Comment by vj-codes** [comment]
@devkapilbansal which label do you want ?
I doubt this PR's merging status as this and other UI PRs are just a mockups . However will double check with other project managers and Isabel :)

**Comment by devkapilbansal** [comment]
@vj-codes if this PR will be merged then `Ready to Merge` label or if we need review from maintainers then `Review Required` label. But, we should add a label to the PR to categorise it

**Comment by devkapilbansal** [comment]
@isabelcosta needs your input here

**Comment by isabelcosta** [comment]
Thank you @devkapilbansal for pinging me here 🙌🏾 
@SHITIZ-AGGARWAL thank you for contributing for OSH!
We will close the issue as we're going discuss designs with new community design ambassadors. I will add this PR to our Wiki :)

**Pull request closed without merging**
