### PR TITLE
chore: improve Pull Request & Issue templates

### LINKED ISSUE #560: imporve issue templates and pull request templates
**Is your feature request related to a problem? Please describe.**

The description like above should be commented as they are for Author's eye only. and hence they will not be seen in preview.

**Describe the solution you'd like**

`<!-- A clear and concise description of what you want to happen. -->`

**Describe alternatives you've considered**

NA

**Additional context**

I am willing to work on this one.

### PR DESCRIPTION
**Pull request by snitin315**
### Description

Improved Pull request templates & Issue templates.
Made the description comments as they are for the Author's Eye only.

Fixes #560 

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bugfix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by isabelcosta** [comment]
@snitin315 I really appreciate this PR, since I just learned something new about the markdown 🤗 but as per our guidelines you have to first create an issue -> issue get approved -> and then get assigned, can you do that please, and then I can look at this?

**Comment by snitin315** [comment]
@isabelcosta Sure :+1:

**Comment by isabelcosta** [comment]
I added this `Fixes #560` to the description @snitin315

**Comment by snitin315** [comment]
@isabelcosta Thanks

**Review by isabelcosta — APPROVED** [review]
This looks great! and I feel this is super helpful, since it becomes clear to the author of an issue or PR, that the content they should add is missing.

Thank you for proposing this change @snitin315 and for your contribution 👏

**Comment by isabelcosta** [comment]
i reached out on Zulip, for someone to give a 2nd review, after that I am happy to merge @snitin315

**Review by sakshi1499 — APPROVED** [review]
The changes look good and would be really helpful too. 💯

**Review by robotjellyzone — APPROVED** [review]
I think this PR will be helpful in the sense that one doesn't have to remove those detailed lines while creating issues or pr in the descriptions, making them as a comment will be good and then no need to remove those lines for adding yours. good @snitin315 👍

**Comment by isabelcosta** [comment]
Thank you @sakshi1499 and @robotjellyzone for your reviews 🤗 
I really really appreciate them!

**Pull request merged**
