### PR TITLE
chore(api): fix typo in task.py

### PR DESCRIPTION
**Pull request by snitin315**
### Description

Fixed Some typos.

### Type of Change:

**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bugfix (non-breaking change which fixes an issue)

### How Has This Been Tested?

NA

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by robotjellyzone** [comment]
Hi @snitin315 please first fill up the description part of this PR as it would then be easy for anyone to understand what exactly this PR is doing ! Also, to place a check mark you should do --> [x] without any space between brackets

**Comment by isabelcosta** [comment]
@snitin315 I really appreciate this PR, since I just learned something new about the markdown 🤗 but as per our guidelines you have to first create an issue -> issue get approved -> and then get assigned, can you do that please, and then I can look at this?

**Comment by snitin315** [comment]
@isabelcosta Done :+1:

**Comment by isabelcosta** [comment]
This PR was good but I will close this, since me and @snitin315 agreed to leave this to first timers in this repository :)
this was fixing issue #559

**Pull request closed without merging**
