### PR TITLE
feat: Decrease expiry time for access tokens

### LINKED ISSUE #933: Feature/bug: Decreasing the expiry time for access tokens.
**Is your feature request related to a problem? Please describe.**

The access tokens have an expiry set to one week. 

**Describe the solution you'd like**

Reduce the time to somewhere around 10 mins.

**Additional context**

This will ensure that even in the case where an access token is compromised it may be used only for a short period of time before it expires.

### PR DESCRIPTION
**Pull request by HeroicHitesh**
### Description

Decrease the expiry time for access token from 1 week to 10 minutes

Fixes #933 

### Type of Change:

- Code

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by epicadk** [comment]
You'll also have to change some tests that are failing.

**Comment by HeroicHitesh** [comment]
> You'll also have to change some tests that are failing.

Yeah I saw the tests failing, I thought that will be a separate issue so didn't fix them. I'll work on them now.

**Review by epicadk — APPROVED** [review]
💯💯 looks good

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: 

Congrats @HeroicHitesh  for your first PR :tada: :tada: :tada:

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@HeroicHitesh @epicadk although test cases are amended to ensure `JWT_ACCESS_TOKEN_EXPIRES` is changed to 10 minutes.
But can we add some more tests to ensure `ACCESS_TOKEN` don't work after 10 minutes by mocking datetime ?

**Comment by epicadk** [comment]
> @HeroicHitesh @epicadk although test cases are amended to ensure `JWT_ACCESS_TOKEN_EXPIRES` is changed to 10 minutes.
> But can we add some more tests to ensure `ACCESS_TOKEN` don't work after 10 minutes by mocking datetime ?

This is a first timers only issue so idk if we should expect the contributor to add these tests. cc @isabelcosta

**Comment by isabelcosta** [comment]
@devkapilbansal that suggestion sounds appropriate :) Do you need help on how to do it @HeroicHitesh ? just let me know :)

**Comment by isabelcosta** [comment]
@epicadk who picks a "first timers only" issue does not mean they are beginners in the tech stack they are working on, it just means they have never contributed to this repository ;) Does it makes sense 🤔 
@HeroicHitesh do you think you could do that 1 additional test?

**Comment by epicadk** [comment]
> @epicadk who picks a "first timers only" issue does not mean they are beginners in the tech stack they are working on, it just means they have never contributed to this repository ;) Does it makes sense 🤔
> @HeroicHitesh do you think you could do that 1 additional test?

Hmm yep makes sense.

**Comment by HeroicHitesh** [comment]
> Do you need help on how to do it @HeroicHitesh ? just let me know :)

Yes @isabelcosta I need some guidance on what is the desired outcome of this additional test and how I should approach this. I am a bit new to writing tests.

> @HeroicHitesh do you think you could do that 1 additional test?

@isabelcosta Yes sure.

**Comment by devkapilbansal** [comment]
@HeroicHitesh here is what you may need to do:
1) Login and get the access token
2) Test if access token if working fine
3) Mock the datetime utility(or somethiing similar) to increase current time in test(more than 10 minutes)
4) Ensure the access token is not working

**Comment by isabelcosta** [comment]
> @HeroicHitesh here is what you may need to do:
> 
> 1. Login and get the access token
> 2. Test if access token if working fine
> 3. Mock the datetime utility(or somethiing similar) to increase current time in test(more than 10 minutes)
> 4. Ensure the access token is not working

@HeroicHitesh this seems to make sense :) If you have doubts still, let me know i can try to help more :)

**Comment by devkapilbansal** [comment]
@HeroicHitesh were you able to write some tests? Or need some help

**Comment by HeroicHitesh** [comment]
@devkapilbansal @isabelcosta Sorry for the late reply. I was a bit busy for past few days. I will try to write tests by coming Wednesday.

**Comment by vj-codes** [comment]
@HeroicHitesh any updates here?

**Comment by HeroicHitesh** [comment]
@vj-codes I am extremely sorry. I am not getting time for it currently due to personal reasons. You can proceed without the tests or assign someone else to write tests.

cc @isabelcosta @devkapilbansal

**Comment by epicadk** [comment]
Ac

> @HeroicHitesh here is what you may need to do:
> 
> 1. Login and get the access token
> 2. Test if access token if working fine
> 3. Mock the datetime utility(or somethiing similar) to increase current time in test(more than 10 minutes)
> 4. Ensure the access token is not working

Actually this would be kinda like testing the JWT library itself which is not upto us but rather the maintainers of the library. We could make this a part of a user journey test but apart form this I don't think this makes sense.

**Comment by vj-codes** [comment]
@HeroicHitesh any update here?

**Comment by devkapilbansal** [comment]
> Ac
> 
> > @HeroicHitesh here is what you may need to do:
> > 
> > 1. Login and get the access token
> > 2. Test if access token if working fine
> > 3. Mock the datetime utility(or somethiing similar) to increase current time in test(more than 10 minutes)
> > 4. Ensure the access token is not working
> 
> Actually this would be kinda like testing the JWT library itself which is not upto us but rather the maintainers of the library. We could make this a part of a user journey test but apart form this I don't think this makes sense.

Okay, approving this :+1: @epicadk should an issue be opened to add it in user journey test?

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1:

**Review by isabelcosta — APPROVED** [review]
Nice work @HeroicHitesh !
Thank you for contributing!

**Comment by epicadk** [comment]
> > Ac
> > > @HeroicHitesh here is what you may need to do:
> > > 
> > > 1. Login and get the access token
> > > 2. Test if access token if working fine
> > > 3. Mock the datetime utility(or somethiing similar) to increase current time in test(more than 10 minutes)
> > > 4. Ensure the access token is not working
> > 
> > 
> > Actually this would be kinda like testing the JWT library itself which is not upto us but rather the maintainers of the library. We could make this a part of a user journey test but apart form this I don't think this makes sense.
> 
> Okay, approving this 👍 @epicadk should an issue be opened to add it in user journey test?

Yup I think we can do that.

**Review by isabelcosta — COMMENTED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

   * _Access GET /user API 10 min later_  
     _Screenshot/gif_:  
    accessing user data was unsuccessful after 10 min

     _Expected Result_:  The access to GET /user should fail when using the access token after 10 min
     _Actual Result_: As expected

   * _Access GET /user API before 10 min before_  
     _Screenshot/gif_:  
    accessing user data was successful before 10 min
     _Expected Result_:  The access to GET /user should work when using the access token before 10 min pass
     _Actual Result_:  as expected
  
3. Additional Comments: N/A

4. Status of PR Changed to: Ready to Merge.

**Pull request merged**
