### PR TITLE
update UI for email confirmation

### LINKED ISSUE #768: Design UI for email confirmation
## Description
As a developer,
I need to design a specific UI for email confirmation,
so that I can improve the current UI.

### Context
When a user registers they receive an email confirmation (account activation) link in the email ([current template](https://github.com/anitab-org/mentorship-backend/blob/develop/templates/email_confirmation.html)). This UI should be designed following [AnitaB.org Branding Guidelines](https://drive.google.com/file/d/1QyQrNfGMa5e-3D0obDAGnkHZ1u7nhZ87/view).

## Mocks
Current confirmation email
msemailconf

### Update [Required]
- [ ] Design a specific UI for email confirmation

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by SHITIZ-AGGARWAL**
### Description

updating user interface for email confirmation

Fixes #768 

### Type of Change:

- User Interface

### Checklist:

- [x]  Design a specific UI for email confirmation

### CODE REVIEW

**Review by SanketDG — CHANGES_REQUESTED** [review]
@gaurivn Is this what was expected of the issue?

Also, please don't assign someone issues if they are already assigned.

**Comment by gaurivn** [comment]
> Also, please don't assign someone issues if they are already assigned.

 I've always checked that before assigning, will take care.. in some cases they got assigned to other issues after I assigned them. And design PRs do take a lot more time to get approved.

**Comment by gaurivn** [comment]
@anitab-org/design-team, please review this PR. 

> @gaurivn Is this what was expected of the issue?

Not completely, changes will be required, I've tagged the design team to help for same.

**Comment by gaurivn** [comment]
@SHITIZ-AGGARWAL, by updating UI, you'll have to design a mock for the same, please refer [this PR](https://github.com/anitab-org/mentorship-backend/pull/828) for a similar issue.

**Comment by SHITIZ-AGGARWAL** [comment]
sure , got it , I will make the required changes

**Comment by SHITIZ-AGGARWAL** [comment]
@gaurivn please help

**Pull request closed without merging**
