### PR TITLE
Added basic support for database migrations

### LINKED ISSUE #198: Support SQLAlchemy Schema Migration using Alembic
**Is your feature request related to a problem? Please describe.**
A database/schema migration refers to the management of incremental, reversible changes to relational database schemas. A schema migration is performed on a database whenever it is necessary to update or revert that database's schema to some newer or older version.

A database migration usually changes the schema of a database, such as adding a column or a constraint, adding a table or updating a table. It's often performed using raw SQL wrapped in a transaction so that it can be rolled back if something went wrong during the migration. 

**Describe the solution you'd like**
Migrations can be performed programmatically by using a `schema migration tool` (e.g. Alembic). When invoked with a specified desired schema version, the tool automates the successive application or reversal of an appropriate sequence of schema changes until it is brought to the desired state. Most schema migration tools aim to minimize the impact of schema changes on any existing data in the database.

Instead of changing the schema directly and then recreate the database from scratch, we can choose to migrate the database using alembic. Alembic is a lightweight database migration tool for SQLAlchemy. It is created by the author of SQLAlchemy and it has become the de-facto standard tool to perform migrations on SQLAlchemy backed databases.

**Describe alternatives you've considered**
[Flask-migrate](https://flask-migrate.readthedocs.io/en/latest/) is an extension that handles SQLAlchemy database migrations for Flask applications using Alembic. The database operations are made available through the Flask command-line interface or through the Flask-Script extension. Using this might also be helpful.

**Additional context**
https://en.wikipedia.org/wiki/Schema_migration
https://www.pythoncentral.io/migrate-sqlalchemy-databases-alembic/

### PR DESCRIPTION
**Pull request by bartekpacia**
### Description
I encountered migration-related issue while adding `gravatar_url` column to UserModel (PR #334). In order to make the server work, I had to remove `dev_data.db`. It is not a serious problem during development, but it will be very serious on production.

I used Flask-Migrate because it seems to be the most mature and popular solution for managing relations in SQLAlchemy-powered databases. It uses Alembic under the hood.

**Okay, how do I use it?**
Let's say you're doing issue #326, that is adding `gravatar_url` to UserModel.

1. Make your changes
2. Run the server and make `POST /register` . It will crash with `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: users.gravatar_url` (full traceback [here](https://gist.github.com/bartekpacia/f1f438489a1a81933711023a1f87b732))
3. It crashed because you added a new column to model declaration, but existing entities in the database still have old model i.e don't have `gravatar_url` property on them.
4. Run `flask db migrate`. This will generate migration script in `migrations/versions`. It's highly recommended that you review it and make adjustments.
5. Run `flask db upgrade`. This will run the migration script which was generated in the previous. That script will apply migrations on the database.
6. Run the server and make `POST /register` again. It should work as intented. (or at *works on my machine* ;) )

Related resources:
- [Flask-Migrate docs](https://flask-migrate.readthedocs.io/en/latest/)
- [Flask-Migrate on PyPI](https://pypi.org/project/Flask-Migrate/)

Fixes #198 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] Update requirements.txt

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bartekpacia** [comment]
@isabelcosta @BadduCoder If you want, please kindly review my changes:)

**Review by mtreacy002 — COMMENTED** [review]
Is it OK if I give some input? @bartekpacia Codacy failed on D213. Maybe you should add --ignore=D213 as per [PEP257 doc](https://pep257.readthedocs.io/en/latest/release_notes.html) and [stackoverflow discussion here](https://stackoverflow.com/questions/45990301/pep257-d212-and-d213-conflicts). Probably also add D212 just incase. Not sure which file to add this though, any suggestion?

**Comment by bartekpacia** [comment]
@mtreacy002 I have zero experience with Codacy and am very low on time now, so, unfortunately, I'm not able to answer your query.

**Comment by mtreacy002** [comment]
> @mtreacy002 I have zero experience with Codacy and am very low on time now, so, unfortunately, I'm not able to answer your query.

Hi again @bartekpacia, I'm a newbie myself, so we're on the same boat :sms. I thought we might need to put something like CMD pydocstyle --ignore=D212,D213 inside Dockerfile, right after "RUN pip install -r requirements.txt" line. But maybe I'm wrong. @isabelcosta @BadduCoder probably can give us a hint?

**Comment by mtreacy002** [comment]
> > @mtreacy002 I have zero experience with Codacy and am very low on time now, so, unfortunately, I'm not able to answer your query.
> 
> Hi again @bartekpacia, I'm a newbie myself, so we're on the same boat :sms. I thought we might need to put something like CMD pydocstyle --ignore=D212,D213 inside Dockerfile, right after "RUN pip install -r requirements.txt" line. But maybe I'm wrong. @isabelcosta @BadduCoder probably can give us a hint?

Sorry, just checked and realised that our requirements.txt has no pydocstyle install. @isabelcosta, do you think we need this to be added so that we can pass Codacy test? Or is this missing the point altogether? 😀

**Comment by isabelcosta** [comment]
> Is it OK if I give some input? @bartekpacia Codacy failed on D213. Maybe you should add --ignore=D213 as per [PEP257 doc](https://pep257.readthedocs.io/en/latest/release_notes.html) and [stackoverflow discussion here](https://stackoverflow.com/questions/45990301/pep257-d212-and-d213-conflicts). Probably also add D212 just incase. Not sure which file to add this though, any suggestion?

Thank you for your input here @mtreacy002 you are more than welcome to review other people's PR. No matter how experienced you are, you can always catch typos ;) (or other stuff)
Regarding this change, I feel that it can be done once we have Codacy in place. Also, I know you have a PR meant to solve some of these formatting issues.

**Comment by isabelcosta** [comment]
@bartekpacia while running this I have encountered this issue: 
```
root@ba5f1e8b7835:/dockerBuild# flask db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> f5a9df5208f9, Initial migration.
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_migrate/__init__.py", line 280, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 96, in <module>
    run_migrations_online()
  File "migrations/env.py", line 90, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.7/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/dockerBuild/migrations/versions/f5a9df5208f9_initial_migration.py", line 23, in upgrade
    sa.Column('tasks', app.database.db_types.JsonCustomType.JsonCustomType(), nullable=True),
NameError: name 'app' is not defined
```
When running the `flask db upgrade` command, where you running the app itself? Or can the app, be not running?

**Comment by isabelcosta** [comment]
@bartekpacia Ok, I edited the flask migration file and managed to run it.

I had to export the variable FLASK_APP like:
```
export FLASK_APP=run.py
```

Then I successfully ran this:
```
(venv) isabel@debian:~/dev/mentorship-backend$ flask db init
  Creating directory /home/isabel/dev/mentorship-backend/migrations ...  done
  Creating directory /home/isabel/dev/mentorship-backend/migrations/versions ...  done
  Generating /home/isabel/dev/mentorship-backend/migrations/script.py.mako ...  done
  Generating /home/isabel/dev/mentorship-backend/migrations/alembic.ini ...  done
  Generating /home/isabel/dev/mentorship-backend/migrations/env.py ...  done
  Generating /home/isabel/dev/mentorship-backend/migrations/README ...  done
  Please edit configuration/connection/logging settings in '/home/isabel/dev/mentorship-backend/migrations/alembic.ini' before
  proceeding.
(venv) isabel@debian:~/dev/mentorship-backend$ flask db migrate -m "Initial migration."
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'tasks_list'
INFO  [alembic.autogenerate.compare] Detected added table 'users'
INFO  [alembic.autogenerate.compare] Detected added table 'mentorship_relations'
INFO  [alembic.autogenerate.compare] Detected added table 'tasks_comments'
  Generating /home/isabel/dev/mentorship-backend/migrations/versions/1b2fe1d4a4b5_initial_migration.py ...  done
(venv) isabel@debian:~/dev/mentorship-backend$ flask db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 1b2fe1d4a4b5, Initial migration.
(venv) isabel@debian:~/dev/mentorship-backend$ 

```

**Comment by bartekpacia** [comment]
@isabelcosta I'm glad you managed to work it out! TBH I wouldn't be really able to help because I don't remember anything about this PR and the changes I made🙄

**Comment by isabelcosta** [comment]
@bartekpacia no problem! I only got time to review this and understand it. And since this is sort of important I will see if this can be incorporated soon and properly documented

**Review by isabelcosta — APPROVED** [review]
After fixing the merge conflicts, I think this works as it is.
Thank you for contributing @bartekpacia

**Comment by isabelcosta** [comment]
All files under `migrations` folder are autogenerated, not sure if it should go, but i don't see a problem in it being there either.

**Comment by mtreacy002** [comment]
> > Is it OK if I give some input? @bartekpacia Codacy failed on D213. Maybe you should add --ignore=D213 as per [PEP257 doc](https://pep257.readthedocs.io/en/latest/release_notes.html) and [stackoverflow discussion here](https://stackoverflow.com/questions/45990301/pep257-d212-and-d213-conflicts). Probably also add D212 just incase. Not sure which file to add this though, any suggestion?
> 
> Thank you for your input here @mtreacy002 you are more than welcome to review other people's PR. No matter how experienced you are, you can always catch typos ;) (or other stuff)
> Regarding this change, I feel that it can be done once we have Codacy in place. Also, I know you have a PR meant to solve some of these formatting issues.

😀 @isabelcosta, this was one of the first PR I looked at when I tried to contribute. Because of this PR as well I realised that some other PR also trying to work on the code reformatting issue. That's how I thought of my #478 approach. Glad that all good now 😉

**Comment by mtreacy002** [comment]
Great job @bartekpacia and @isabelcosta for solving this PR. It would greatly help me in the work need to be done in the app I'm aiming (in GSoC proposal). 🎉

**Comment by isabelcosta** [comment]
@mtreacy002 this was a really important thing for the app, indeed, because with new features, comes new changes to the database model 🙈 So I tried to test this today to see if this did not ruin any other feature. I hope this does help how you're saying :)

**Comment by bartekpacia** [comment]
I also think that we should consider adding some tests for db migrations.

**Comment by isabelcosta** [comment]
> I also think that we should consider adding some tests for db migrations.

i have no idea how to write tests for these migrations 🤔 @bartekpacia any idea?
if this is possible we need an issue 🚀

**Comment by bartekpacia** [comment]
Me neither, my only experience with Flask and SQLAlchemy is this project:/
I created #486 for this

**Comment by isabelcosta** [comment]
No problem! thank you so much for your work here @bartekpacia :) I am reviewing another issue now, that I needed this to be done.
Annnnd thank you so much for creating the issue 🙈 sometimes I don't create if I don't know that it is feasible.

**Comment by isabelcosta** [comment]
Just an update for documentation purposes. This worked fine manually, when I was testing PR #216 . I managed to run 2 commands and create the `cancellation_reason` field for every mentorship relation.
Here it is the new column, on my instance of ElephantSQL:
image

Here's the commands I ran on the terminal:
image

**Comment by mtreacy002** [comment]
Thanks, @isabelcosta for the tips. This would help us heaps later when we need to add/change the db 👍

**Pull request merged**
