### PR TITLE
Fix: refactor HTTP error codes PUT /mentorship_relation/{request_id}/task/{task_id}/complete

### LINKED ISSUE #632: Fix: refactor HTTP error codes PUT /mentorship_relation/{request_id}/task/{task_id}/complete
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to PUT /mentorship_relation/{request_id}/task/{task_id}/complete,
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA

### Update [Required]
- [ ] 409: Conflict need to be returned instead of 400: Bad Request if the task was already achieved

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by vj-codes**
### Description

Updated to 409:CONFLICT  if the task was already achieved
Fixes #632

### Type of Change:

- Code
- User Interface

### How Has This Been Tested?
Tested locally works as expected

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes
Screenshot (194)

### CODE REVIEW

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1:

**Comment by devkapilbansal** [comment]
Thanks @vj-codes for making this change

The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  HTTP error code for endpoint mention should be refactored
    _Screenshot/gif_:  


    _Expected Result_:  Error code for `Task Already Achieved` changed to `CONFLICT`
    _Actual Result_: Same as expected
    
3. Additional Comments: All instances of the code are replaced and unit tests pass successfully

P.S. :-  After one more approved review, PR can be labelled as `Ready to Merge`

**Review by epicadk — APPROVED** [review]
👍🏼 looks good.

**Comment by isabelcosta** [comment]
Thank you so much @vj-codes @devkapilbansal @epicadk !

**Pull request merged**
