### PR TITLE
fix: refactor http status code (replace 200 with 201 and 400 with 409) 

### LINKED ISSUE #619: Fix: refactor HTTP error codes POST /register for Users service
## Description
As a GSoC student,
I need the correct HTTP error response code to be returned accordingly by Mentorship System API in relation to POST /register request,
so that I can represent the error message accordingly to both Mentorship System and Bridge In Tech users.

## Mocks
NA

### Update [Required]
- [ ] 201: Created need to be returned instead of 200: OK if the process is successful 
- [ ] 409: Conflict need to be returned instead of 400: Bad Request if the username or email already exist

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by nandini45**
### Description
Fixes #619

**### Type of Change:**
Code

 **Code/Quality Assurance Only**
New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Update Postman API at /docs folder

### Code/Quality Assurance Only

- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by satya7289 — COMMENTED** [review]
Looks good.
One more thing needs to do in this PR. Add the test cases to validate that it returning correct Https status responses.

**Comment by mtreacy002** [comment]
thanks, @nandini45 for your contribution. I'll forward the review request to @anitab-org/bridgeintech-maintainers as I'm a bit low on bandwith at the moment.

**Review by foongminwong — APPROVED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses were tested as below:

   * _Before PR 650_  
    _Screenshot/gif/url_:  

    before-pr-650

    _Expected Result_:  The HTTP error response codes to be returned accordingly by Mentorship System API in relation to POST **/register** request are 200 and 400.
    _Actual Result_: Same as expected.

   * _After PR 650_  
    _Screenshot/gif/url_:  

   after-pr-650

    _Expected Result_:  The HTTP error response codes to be returned accordingly by Mentorship System API in relation to POST **/register** request are 201 and 409.
    _Actual Result_:  Same as expected
    
3. Additional testcases covered: N/A
    
4. Additional Comments: N/A

5. Status of PR Changed to: N/A

6. OS: Windows 10

**Review by snitin315 — APPROVED** [review]

**Review by isabelcosta — APPROVED** [review]
Great work @nandini45 🎉 
Thank you for this contribution 👏 👏 👏

**Comment by isabelcosta** [comment]
Thank you for testing this @foongminwong  🙌 🙌 🙌 🙌 🙌

**Pull request merged**
