### PR TITLE
heroku app broken links fixed

### LINKED ISSUE #948: Heroku app broken links
## Description
To fix the broken link to wiki guide in the Heroku app and remove repeated lines.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 minutes

### PR DESCRIPTION
**Pull request by surbhigoel191**
### Description

Repeated code deleted along with fixing broken link to wiki guide in the Heroku app.

Fixes #948 

### Type of Change:

- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

Before 
Screenshot (249)

After
Screenshot (251)

### CODE REVIEW

**Review by vj-codes — APPROVED** [review]
Thank you for your contribution @surbhigoel191 
LGTM 🎉

**Comment by isabelcosta** [comment]
@surbhigoel191 I would love for your commit to identify your GitHub account. You can see that the commit on github does not show you avatar image, that is because you don't have your email setup when you did this commit. This means you won't be credited once the PR gets merged.

image

Here's a guide on how to setup the email you have on github to be used in your commits; https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git

If you rather not do this, that is ok. Let me know and I can test this and merge as it is.

**Comment by surbhigoel191** [comment]
@isabelcosta Done :D

**Review by isabelcosta — APPROVED** [review]
Great work @surbhigoel191 👏 Thank you for contributing!

**Comment by isabelcosta** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Open Swagger UI on https://ms-backend-review-pr-951.herokuapp.com/_  
    
_Screenshot/gif_:  

image

_Expected Result_:  there is no broken links on the swagger UI description
_Actual Result_: all links work now 🚀 

3. Status of PR Changed to: Ready to Merge.

**Comment by isabelcosta** [comment]
@surbhigoel191 your PR just got merged 👏

**Pull request merged**
