### PR TITLE
Style: Convert string formatting to f-strings in tests/tasks/*

### LINKED ISSUE #744: Use f-strings in tasks folder test files
## Description
As a developer,
I need change strings interpolation in tasks folder test files,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `tests/tasks/*` files.

## Mocks
As an example, here:
https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/tests/tasks/test_api_create_task.py#L32
We can use f-strings such as:
```
f"/mentorship_relation/{self.mentorship_relation_w_second_user.id}/task",
```
### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for all such files present in `tests/tasks` folder.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hour

### PR DESCRIPTION
**Pull request by Nibba2018**
### Description
Converts string formatting in `tests/tasks/*` to f-strings.

Fixes #744 

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [X] My changes generate no new warnings 
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by PrashanthPuneriya — DISMISSED** [review]
I am extremely sorry for the late review @Nibba2018. Haven't got any notification about this PR and I thought that I have already reviewed this PR. I hope you don't mind it.
Thanks a lot for your contribution to this project :)

**Review by vj-codes — DISMISSED** [review]
LGTM 🎉

**Comment by vj-codes** [comment]
Adding label `Ready To Merge` as it is a documentation issue

**Review by keshakaneria — DISMISSED** [review]
Good work 👍 but you're requested to squash the commits @Nibba2018

**Comment by Nibba2018** [comment]
Thank you for you reviews @keshakaneria @vj-codes @PrashanthPuneriya . I will get my commits squashed. On a different note, I was not able to complete 4 PRs during OSH so should I fillup the OSH form as this issue was part of OSH?

**Comment by keshakaneria** [comment]
> Thank you for you reviews @keshakaneria @vj-codes @PrashanthPuneriya . I will get my commits squashed. On a different note, I was not able to complete 4 PRs during OSH so should I fillup the OSH form as this issue was part of OSH?

Well it is recommended for those who successfully sent 4 PRs to fill up the form :) But dont worry, this was just an experience, I know you'll do more better next time 🥳

**Review by isabelcosta — APPROVED** [review]
Good work @Nibba2018 🎉 
Thank you for this contribution!

**Review by keshakaneria — APPROVED** [review]
Good to go 🥳

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Comment by isabelcosta** [comment]
@Nibba2018 i just merged your PR! thank you for your contribution!

**Pull request merged**
