### PR TITLE
feedback feature

### LINKED ISSUE #170: Create user feedback feature
## Description

As a someone interested in the mentorship system development,
I need to receive feedback from the user,
so that I can improve the app with the user's feedback.

For this issue, you'll need to think about what the data model should have as attributes (e.g.: a creation timestamp, description of the feedback, ...)

**Note:** if this is too big, maybe this work should be split into more than one PR (e.g.: 1 for DAO and tests, 1 for data model and tests and 1 for API and tests).

### Update [Required]
- [ ] Create a Feedback data model class, possibly link it to the specific user
- [ ] Tests for the data model class
- [ ] Create Feedback DAO
- [ ] Create Feedback API
- [ ] Tests for all of these?

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by chahat99**
### Description
Feedback feature has been added. Any user who has been or is in a mentorship relation can give the feedback.

Fixes #170

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)
-Added Feedback data model class
-Created Feedback DAO
-Created Feedback API

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by chahat99** [comment]
@isabelcosta I have added the feedback feature in the backend regarding issue 170.Please review it.

**Comment by chahat99** [comment]
@isabelcosta do I need to make some changes in this?

**Comment by isabelcosta** [comment]
@chahat99 I don't know yet, since this is such a big PR, I need more time to look at it. Will call for help nonetheless on Zulip!

**Comment by robotjellyzone** [comment]
Hi @chahat99 just one suggestion, if one is not in any relation but still want to send a feed back related to look and feel or any type of bug or any enhancement that the user want in the app then I what would happen!? I think its good to allow that sort of user as well... What do you think @chahat99 @isabelcosta 🤔

**Comment by chahat99** [comment]
@robotjellyzone I think you are right. I haven't given that option in the code.I thought that the people who are in relation would be willing to give the feedback. But anyone can give feedback about the looks and the bugs.I will add that option. What do you think @isabelcosta ?

**Comment by devkapilbansal** [comment]
@chahat99 can you please add necessary tests for your changes?

**Comment by devkapilbansal** [comment]
Closing due to inactivity. Thanks for your contribution @chahat99 
If you like to work on in, do comment on the pull request

**Pull request closed without merging**
