### PR TITLE
test: Performed manual testing of POST /user/resend_email API endpoint

### LINKED ISSUE #875: Perform manual testing and report POST /user/resend_email API
## Description

As a tester,
I need to test POST /user/resend_email API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#resend-verification-email](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#resend-verification-email)

### Update [Required]
- [ ] Test POST /user/resend_email API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by devkapilbansal**
### Description
Fixes #875 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by devkapilbansal** [comment]
@gaurivn @PrashanthPuneriya @isabelcosta please review this too.

**Comment by devkapilbansal** [comment]
@vj-codes please look into this too.

**Review by vj-codes — APPROVED** [review]
@devkapilbansal LGTM 🎉

**Review by gaurivn — APPROVED** [review]
Code Review: NA

Verified PR by manually testing POST /user/resend_email

Results

Test 1
t1

Test 2
t2

Test 3
t3

Expected results and Actual results are the same.

Great work, thank you :tada:

**Review by PrashanthPuneriya — APPROVED** [review]

**Comment by vj-codes** [comment]
Updating label as ready to merge (testing done above)

**Review by isabelcosta — APPROVED** [review]
Good work @devkapilbansal 👏 🎉 
Thank you for your contribution!

**Pull request merged**
