### PR TITLE
Add black to support code refactoring to pep8 style

### LINKED ISSUE #464: Add Black to help simplify code refactoring to PEP8 standard
**Is your feature request related to a problem? Please describe.**
I'm wondering if we could implement a reformatting tool to help refactor code to comply with pycodestyle (aka PEP8) standard. This will help save time and make us more productive in our app development.

**Describe the solution you'd like**
We could try adopting [black](https://github.com/psf/black) that not only can help us check our code against PEP8 standard but also reformat the code for us using only one single command line. The coverage can be from just a single file up to the whole project. 

**Describe alternatives you've considered**
I haven't look for alternative yet 😊. 

PS: I'm aware that code refactoring to PEP8 standard has been discussed in a couple of previous issues and relevant PRs and they all are great. We could still apply the solution offered here in integration with 'black':

- PR #174 for issue #173 
- PR #197, #417 for issue #187 
- PR #253, #255 
- PR #260, issue #261
- PR #414, #416, #421, #422, #433, issue #178

I have no intention to disregard the efforts and contribution that others have made. My intention is only to offer an alternative solution. I will gladly follow any solution that @mentors/@maintainers decide to be adopted 😉. If this does not follow the common acceptable practice, I apologise beforehand and appreciate the patience as I'm a newbie who's still in learning 😊    

**Additional context**

- checking codes in the whole project against pycodestyle with black:

> <root dir> $ black . --check

Screen Shot 2020-02-28 at 11 12 40 pm

- reviewing the 'before/after' code changes prior to reformatting:

> <root dir> $ black . --diff

Screen Shot 2020-02-28 at 11 13 52 pm

- reformatting codes with black using one line command:

> <root dir> $ black .

Screen Shot 2020-02-28 at 11 43 17 pm

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
To test black in whole project code refactoring. This should improve code quality and lessen the issues detected by codacy.

Fixes [#464](https://github.com/anitab-org/mentorship-backend/issues/464)

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I tested this by:

- reformatting whole project using black in new branch
- making sure that this pull request improve code quality in codacy shown by lesser number of issues found (tested in own codacy space with only pylint 2.4.3 set to 'ON' as Code Patterns).

> codacy - number of issues before refactoring:

Screen Shot 2020-02-29 at 1 16 45 am

> codacy - after refactoring:

Screen Shot 2020-02-29 at 1 06 26 am

PS: not sure if this is the right representation though, coz on develop branch only shows last 8 commits whereas on branch shows last 7 or 31 days. Not sure how to change this 😊 

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Update requirements.txt

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
@isabelcosta, can you please help review this? Thanks

**Comment by annabauza** [comment]
I like the idea of keeping code consistent, however I'd like to hear from Isabel, she will be online since Monday.

**Comment by mtreacy002** [comment]
> I like the idea of keeping code consistent, however I'd like to hear from Isabel, she will be online since Monday.

Thanks, @annabauza, for the feedback. Look forward to hear from @isabelcosta when she's back.

**Comment by mtreacy002** [comment]
@isabelcosta and @annabauza, I've just realised that this PR was fork from the branch I created for PR #463 (fix of issue #461) Preventing data to be inserted when email verification failed to send. Since we're still discussing #463, this PR might got blocked. Should I delete this and open new PR as new branch made from the current develop branch? Your advise is appreciated.

**Pull request closed without merging**
