### PR TITLE
removing is_done from get /tasks api response.

### LINKED ISSUE #376: Duplicate fields is_done and completed_at in GET /tasks
**Is your feature request related to a problem? Please describe.**
Use of both fields is unnecessary. **is_done** field can be removed.

**Describe the solution you'd like**
If **completed_at** has *null" value then it automatically implies that is_done is false. If **completed_at** contains a timestamp then task is complete.

```json
[
  {
    "id": 2,
    "description": "task2",
    "is_done": true,
    "created_at": 1577709722.596752,
    "completed_at": 1578133696.121925
  },
  {
    "id": 3,
    "description": "task3",
    "is_done": false,
    "created_at": 1577709726.626315,
    "completed_at": null
  }
]
```
**Describe alternatives you've considered**
Keep the API as it is. It doesn't obstruct functionality although it is unnecessary.

**Additional context**
None

### PR DESCRIPTION
**Pull request by saikirankv**
### Description

Fixes #376 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by saikirankv** [comment]
@isabelcosta @SanketDG @PrashanthPuneriya build failed due to a decrease in code coverage, which is expected.
can you help me here?

**Comment by devkapilbansal** [comment]
@saikirankv in my opinion it's okay here.

**Review by devkapilbansal — DISMISSED** [review]
LGTM :+1: Thanks @saikirankv for your contribution.

Tested locally and all test cases passed.

**Review by vj-codes — DISMISSED** [review]
LGTM 🎉

**Comment by vj-codes** [comment]
@devkapilbansal can you add your testing screenshots , then this can be merged !

**Comment by devkapilbansal** [comment]
@vj-codes don't we need a migration file too as we have to remove is_done field from previous dev database

Reference: - https://github.com/anitab-org/mentorship-backend/pull/887/#pullrequestreview-506175087

Although I am adding testing screenshots but please look into this

**Review by devkapilbansal — COMMENTED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  
    _Screenshot/gif_:  
is_done

  
3. Additional Comments: Ran test cases using `python -m unittest discover tests` to ensure all test cases passed.

**Comment by NenadPantelic** [comment]
@saikirankv Please, solve the merge conflicts.

**Comment by saikirankv** [comment]
@NenadPantelic  I resolved conflicts.

**Comment by NenadPantelic** [comment]
PR review after the conflicts solving.
1) Code review -> [Done] :+1: 
2) Unit tests -> [Done] :+1: 
3) Manual testing:
- Case 1: OK
image
- Case 2: 404
image

**Review by NenadPantelic — APPROVED** [review]
LGTM :tada:

**Comment by NenadPantelic** [comment]
@isabelcosta This is reviewed and verified. When you get some time, you can merge it (to prevent new merge conflicts).

**Comment by NenadPantelic** [comment]
It is a tinny thing @saikirankv, just update your PR description properly - remove unnecessary things, tick proper checkboxes...

**Comment by saikirankv** [comment]
Done, I updated the PR description.

**Comment by isabelcosta** [comment]
before merging this, it's important to know. is this field being used on android currently? i am not sure, we should look into that

**Comment by NenadPantelic** [comment]
@isabelcosta I checked the android client. Field `is_done` is used here:
https://github.com/anitab-org/mentorship-android/blob/develop/app/src/main/java/org/systers/mentorship/models/Task.kt
https://github.com/anitab-org/mentorship-android/blob/develop/app/src/main/java/org/systers/mentorship/viewmodels/TasksViewModel.kt

**Comment by devkapilbansal** [comment]
> @isabelcosta I checked the android client. Field `is_done` is used here:
> https://github.com/anitab-org/mentorship-android/blob/develop/app/src/main/java/org/systers/mentorship/models/Task.kt
> https://github.com/anitab-org/mentorship-android/blob/develop/app/src/main/java/org/systers/mentorship/viewmodels/TasksViewModel.kt

Then an issue should be opened on the android side too :thinking:

**Comment by epicadk** [comment]
> > @isabelcosta I checked the android client. Field `is_done` is used here:
> > https://github.com/anitab-org/mentorship-android/blob/develop/app/src/main/java/org/systers/mentorship/models/Task.kt
> > https://github.com/anitab-org/mentorship-android/blob/develop/app/src/main/java/org/systers/mentorship/viewmodels/TasksViewModel.kt
> 
> Then an issue should be opened on the android side too 🤔

I have opened an issue. It needs to be approved though.

**Comment by vj-codes** [comment]
@devkapilbansal the migration script was need for zulip PR because there was change of parameter name but since we are removing it here can you confirm if it's required in this .
@epicadk issue valid for android, do we need to wait until this gets merged though?

**Comment by devkapilbansal** [comment]
> @devkapilbansal the migration script was need for zulip PR because there was change of parameter name but since we are removing it here can you confirm if it's required in this .

Yes @vj-codes a migration script would be needed to remove a field too

**Comment by epicadk** [comment]
> @devkapilbansal the migration script was need for zulip PR because there was change of parameter name but since we are removing it here can you confirm if it's required in this .
> @epicadk issue valid for android, do we need to wait until this gets merged though?

Nope infact it would be the other way around. This would need to wait till the issue on android isn't merged.

**Comment by epicadk** [comment]
The corresponding android PR has been merged you can merge this now @isabelcosta.

**Review by isabelcosta — APPROVED** [review]
Looks nice :) With this PR, now the field won't be exposed to through the API.
We will create a follow up to remove the field from database.

Thank you for your contribution @saikirankv !

**Comment by isabelcosta** [comment]
Fairly confident that we can merge this, since it was just removing a field :)

**Comment by isabelcosta** [comment]
@NenadPantelic thank you sooo much for testing this feature 🙌🏾 ❤️

**Pull request merged**
