### PR TITLE
Deletion of swagger.json file in mentorship-backend / docs /

### LINKED ISSUE #764: Remove swagger.json from docs folder
## Description
As a contributor,
I need an up-to-date [swagger.json](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/swagger.json) file,
so that I can refer to the urls, responses and can search them easily. But, since this [link](http://mentorship-backend-temp.herokuapp.com/swagger.json) serves the purpose we no longer need to update [swagger.json](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/swagger.json) and can remove it.

## Mocks
The [swagger.json](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/swagger.json) file isn't up-to-date and alternatively this [link](http://mentorship-backend-temp.herokuapp.com/swagger.json) serves the purpose if incase someone needs it.

### Update [Required]
- [ ] Delete the [swagger.json](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/swagger.json) file

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.1 hour

### PR DESCRIPTION
**Pull request by SHITIZ-AGGARWAL**
### Description

>Deletion of swagger.json file

Fixes #764 

### Type of Change:

>deletion of file

- Documentation

### Checklist:

- [x]  Delete the swagger.json file

### CODE REVIEW

**Review by PrashanthPuneriya — APPROVED** [review]
LGTM! Let's go :)

**Review by SanketDG — APPROVED** [review]
Ready for Merge :tada:

**Review by vj-codes — APPROVED** [review]
@SHITIZ-AGGARWAL Congrats on your first contribution to this repo 🎉

**Comment by SHITIZ-AGGARWAL** [comment]
@PrashanthPuneriya @SanketDG @vj-codes 
Thanks a lot ,this was my first ever open source contribution ,looking forward to contribute more to the community 😊

**Review by isabelcosta — APPROVED** [review]
Great work @SHITIZ-AGGARWAL 🎉 
Thank you for your contribution!

**Pull request merged**
