### PR TITLE
Fixed Description Messages on Backend Server

### LINKED ISSUE #577: Fix description messages on Backend Server
## Description
As a developer, i need to see the same way for displaying messages on the backend server. so that i can follow the same pattern on the messages im writing.

### Update 
The following methods should include:  
image before the message itself. 

Users
- [ ] GET / dashboard
- [ ] PUT /user
- [ ] POST user/send email
- [ ] GET /users
- [ ] GET /users/verified

Admins
- [ ]  GET /admins

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by Aayush-hub**
### Description

This changes the description messages to follow the general structure: {"message": "some message"}.

Fixes #577 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by epicadk — APPROVED** [review]
👍🏼 looks good to me.

**Comment by Aayush-hub** [comment]
@vj-codes @isabelcosta Can you please review my PR?

**Review by vj-codes — APPROVED** [review]
@Aayush-hub thank you for your contribution:)
LGTM 🎉

**Review by devkapilbansal — APPROVED** [review]
Great work @Aayush-hub Thanks for your contribution
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Refactor Description Messages
    _Screenshot/gif_:  
_On Develop_ 

_From this PR_ 


    _Expected Result_:  All response message are changed as described
    _Actual Result_: Same as expected
    
3. Additional Comments: Tested manually to ensure all instances of description message has been changed.

4. Status of PR Changed to: Ready to Merge.

**Comment by isabelcosta** [comment]
Thank you all so much @epicadk @vj-codes @devkapilbansal for reviewing & testing!
Thank you @Aayush-hub for your contribution!

**Pull request merged**
