### PR TITLE
doc: delete ISSUE_TEMPLATE.md

### LINKED ISSUE #1013: Remove .github/ISSUE_TEMPLATE folder
## Description

As a org admin / maintainer,
I need to maintain 1 version of issue templates used in the organization,
so that I can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Update [Required]
- [ ] Delete `.github/ISSUE_TEMPLATE`

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by Sejalcodes**
[#1013 ](https://github.com/anitab-org/mentorship-backend/issues/1013) Deleted ISSUE_TEMPLATE.md file since it was an older version of ISSUE_TEMPLATE file

Fixes #1013

### CODE REVIEW

**Comment by vj-codes** [comment]
@Sejalcodes great work on creating your first PR to the repo , please update the link in contributing.md to the one mentioned in issue comments and then this PR can be reviewed/approved :)

**Review by vj-codes — APPROVED** [review]
@Sejalcodes congrats on your first contribution !
LGTM 🎉

**Comment by Sejalcodes** [comment]
> @Sejalcodes congrats on your first contribution !
> LGTM 🎉

Thankyou so much, the community really helped!

**Review by ashwinijha6 — COMMENTED** [review]
@Sejalcodes  just a suggestion whenever you create a pull request just follow the PULL_REQUEST_TEMPLATE.md
Could you pls mention the type in the PR title & description on why you are making these changes. 👍

**Comment by devkapilbansal** [comment]
@Sejalcodes look into what @ashwinijha6 quoted above. It is necessary for all to follow the proper commit message guideline and the Pull Request Template. Without that, PR can't be merged.

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
The link in `contributing.md` file is not yet fixed. Consider changing the link.
https://github.com/anitab-org/mentorship-backend/blob/479f1c75a8a84a598612ef53f7bb7bc372e13f3e/.github/CONTRIBUTING.md#L12

**Comment by ashwinijha6** [comment]
@devkapilbansal & @vj-codes  I'm just confused which is the correct pull request for #1013 this one or [this](https://github.com/anitab-org/mentorship-backend/pull/1021). Could u'll help me out .

**Comment by vj-codes** [comment]
@ashwinijha6 the merged PR partially solved the issue so this is valid as well
@devkapilbansal the link in contributing.md is created in another PR #1035 , @Sejalcodes as a newcomer wasn't aware it shall be done in the same PR .
(It's fine for this time but should take care next time onwards)

**Comment by Sejalcodes** [comment]
> @Sejalcodes just a suggestion whenever you create a pull request just follow the PULL_REQUEST_TEMPLATE.md
> Could you pls mention the type in the PR title & description on why you are making these changes. 👍

Yes, okay I added the description too...

**Comment by Sejalcodes** [comment]
> The link in `contributing.md` file is not yet fixed. Consider changing the link.
> https://github.com/anitab-org/mentorship-backend/blob/479f1c75a8a84a598612ef53f7bb7bc372e13f3e/.github/CONTRIBUTING.md#L12

I updated the link earlier, however I think that too is not working!...... I wanted to confirm if this is the correct link that needs to be updated "https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE.md"?

**Comment by vj-codes** [comment]
@Sejalcodes you have added the link in #1035 , don't make any changes in this one 
Both are good

**Comment by Sejalcodes** [comment]
> @Sejalcodes you have added the link in #1035 , don't make any changes in this one
> Both are good

okay, thankyou for letting me know!

**Comment by ashwinijha6** [comment]
> @ashwinijha6 the merged PR partially solved the issue so this is valid as well
> @devkapilbansal the link in contributing.md is created in another PR #1035 , @Sejalcodes as a newcomer wasn't aware it shall be done in the same PR .
> (It's fine for this time but should take care next time onwards)

Ok I get you @vj-codes  👍

**Review by ashwinijha6 — CHANGES_REQUESTED** [review]
@Sejalcodes I wanted you to change the type that is `doc` in this PR title
Change it to **doc: delete ISSUE_TEMPLATE.md** &  mention some description here ( shown in the screenshot) as to why certain changes need to be done 
des

**Comment by Sejalcodes** [comment]
> @Sejalcodes I wanted you to change the type that is `doc` in this PR title
> Change it to **doc: delete ISSUE_TEMPLATE.md** & mention some description here ( shown in the screenshot) as to why certain changes need to be done
> des

Hello, is it okay now? :)

**Review by ashwinijha6 — APPROVED** [review]

**Comment by ashwinijha6** [comment]
@Sejalcodes I have approved the PR. Actually I meant to use the PR TEMPLATE but I guess there are 2 PR's related to 1 Issue, So you wanted to keep this as a contintuation. Also I feel that the reason for deleting the ISSUE_TEMPLATE.md file is because they are now on https://github.com/anitab-org/.github, correct me if I'm wrong.

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1:

**Comment by devkapilbansal** [comment]
Adding `Ready to Merge` since this PR don't need testing.

**Comment by isabelcosta** [comment]
@Sejalcodes congrats on your PR merge 👏🏾

**Pull request merged**
