### PR TITLE
Pylint integration in deploy script (In progress....)

### LINKED ISSUE #187: Running pylint for Code quality checks
## Description
This issue is to test all the test cases of features in the project.
Add pylint to the configuration in the deploying script, and return an exit code of 0 only if all files exceed the score of 7.0

## Test Cases
Sample output for pylint:
C: 61, 0: Function name "dumpErrors" doesn't conform to snake_case naming style (invalid-name)
C: 61, 0: Missing function docstring (missing-docstring)
C: 67, 0: Missing function docstring (missing-docstring)

------------------------------------------------------------------
Your code has been rated at 3.75/10 (previous run: 5.22/10, -1.47)
The code rating should be > 7.0 for each python script in the repository.

## Definition of Done
- [ ] At least one test case tested.
- [x] Approval by 1 mentor.

## Estimation
10 hours

### PR DESCRIPTION
**Pull request by NidhiKJha**
### Description
Pylint integration in deploy script. The script runs pylint over each file in and extracts score from each output. The script emits exit code 2 whenever a score below 7 is encountered.

Fixes #187 

### Type of Change:
Appended code to deploy.sh

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How to run
Install Pylint
`chmod a+x deploy.sh`
`./deploy.sh`

### How Has This Been Tested?
By running the script with different inputs.

### CODE REVIEW

**Comment by NidhiKJha** [comment]
@isabelcosta my PR just follows the template, I just deleted the irrelevant sections.
Please open the issue and review the code.

**Comment by isabelcosta** [comment]
@NidhiKJha you're missing the checklist that comes with the template, please edit the description.

**Comment by NidhiKJha** [comment]
Thank you @isabelcosta. I'll do it

**Comment by vj-codes** [comment]
Closing as author is not assigned to the issue , 
Thank you for your contribution:)

**Pull request closed without merging**
