### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by muskanvk**
Added License shield to documentation to improve readability

- Documentation

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by sumit-badsara — COMMENTED** [review]
Looks good to me! :+1: 
Congratulations on your first PR @muskanvk 

A better way would be to create an issue regarding this, and then ask the project owner/maintainer to work on the same issue and then create a PR for that. 
It is easy to keep track of what was the issue and why was the PR created in that way.

Maybe you can create one now and then link this PR as a fix to that issue.

**Comment by muskanvk** [comment]
Thanks for the suggestion. I did that. #827

**Comment by vj-codes** [comment]
Closing since issue is not yet approved and assigned to @muskanvk 
You may re-open it later after the issue is assigned:)

**Comment by gaurivn** [comment]
@muskanvk, please do edit the issue you created following any of these [issue templates](https://github.com/anitab-org/mentorship-backend/tree/develop/.github/ISSUE_TEMPLATE), and if you want to create a PR for the same, do leave a comment (under the issue) asking to be assigned if it gets approved and if it gets approved by one of the maintainers, you can send a PR.

**Pull request closed without merging**
