### PR TITLE
Database URI comes from environment variables to support Amazon RDS

### LINKED ISSUE #87: Use Amazon Relational Database Service (Amazon RDS) for persistence.
## Description
As a developer
I need to use the Amazon Relational Database Service (Amazon RDS),
so that we can have DB persistence even after redeploying the app.

### Update [Required]
- [ ] DB persistence even after redeploying the app.
- [ ] All environments have an Amazon RDS database.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description

- SQLAlchemy Database URI is imported from environment variables to enable different types of databases to be used. Example would be using a SQLite db versus a MySQL remote database on Amazon RDS
- The database URI is defined by the developer in a environment variable called `DATABASE_URI`. I provide 2 examples in the `config.py` file
- Added a new configuration similar to `DevelopmentConfig` but meant to run only on a local configuration usign a SQLite database
- Fixed and added tests according to the new import of the SQLAlchemy Database URI

Followed example for Database URI for a MySQL database from this blog post: https://medium.com/@rodkey/deploying-a-flask-application-on-aws-a72daba6bb80
I also checked the documentation.

Fixes #87 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Ran pre existing tests and new ones.
Switched configurations used locally to see if the environment was being imported.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by isabelcosta** [comment]
I removed the `ENV = 'production'` or `ENV = 'development'` because they were apparently useless. The application would always assume a development environment, even if I imported the production environment the initial print would return `* Environment: development` and only after this it would import the configurations.

**Comment by m-murad** [comment]
@isabelcosta we need to discuss this in our 1:1

**Comment by isabelcosta** [comment]
@m-murad @Dilu9218 and @roopalJazz I will close this and submit a PR again for this when the gsoc18-code branch is merged into develop and master

**Comment by m-murad** [comment]
No need to send a new PR. Just update this PR later and change the base
branch to `develop`

**Comment by isabelcosta** [comment]
I had no idea that could be done, changing the base branch in a current PR :O Ok! I'll open this later

**Comment by isabelcosta** [comment]
Ahhhh I just learned that now! I see it! thank you @m-murad !

**Pull request closed without merging**
