### PR TITLE
docs: blog osh experience

### LINKED ISSUE #904: blog: OSH Experience
## Description

I want you to write a blog about the OSH experience from a newcomer's point of view for the backend repo. So that it tells your experience about open source and also may serve as an intro to backend repo for prospective contributors.

Write a blog on Medium and share the link in a document called `outreach-work.md` in the “/docs” folder of mentorship-backend. So you need to create a post and add a new line to this document. 

#### Mention AnitaB.org as a publication while publishing the blog/article (called: story on medium) at the end of your blog.
https://medium.com/anitab-org-open-source

### Update [Required]
- [ ] [Submit Blog. Add line to `outreach-work.md`]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1 Hour] hours

### PR DESCRIPTION
**Pull request by ashwinijha6**
### Description
Blog OSH Experience for Mentorship-backend

Fixes #904 

### Type of Change:
- Outreach

### How Has This Been Tested?

The medium link is added

### Checklist:

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by paritoshsinghrahar — CHANGES_REQUESTED** [review]
Space out `ASHWINI JHA:[Open` in .md file.
image

Just to be sure. Please proofread it again.

Tag your article in relevant #hastags Open Source, Backend etc. if not done already.

**Comment by ashwinijha6** [comment]
> Space out `ASHWINI JHA:[Open` in .md file.
> image
> 
> Just to be sure. Please proofread it again.
> 
> Tag your article in relevant #hastags Open Source, Backend etc. if not done already.

ok sure @paritoshsinghrahar I will read it again & I have used tags Open Source Anita Borg Contribution Hacks & Experience should I change them?

**Comment by paritoshsinghrahar** [comment]
> ok sure @paritoshsinghrahar I will read it again & I have used tags Open Source Anita Borg Contribution Hacks & Experience should I change them?

That is great. Add more relevant tags. If, you can.

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@ashwinijha6 in your description, it should be Related or Relates rather than fixes for that issue.

**Comment by ashwinijha6** [comment]
> @ashwinijha6 in your description, it should be Related or Relates rather than fixes for that issue.

But why @devkapilbansal

**Comment by devkapilbansal** [comment]
Because your Pull request should not close that issue.

**Comment by ashwinijha6** [comment]
> Because your Pull request should not close that issue.

But after I make the changes it will close 
Do u mean that it is still available for others to work on?
But OSH has come to an end

**Comment by ashwinijha6** [comment]
@devkapilbansal is that ok

**Comment by ashwinijha6** [comment]
@paritoshsinghrahar I have read it again also I have added the space which you requested & added relevant tags , squashed the commits as well.

**Comment by ashwinijha6** [comment]
@paritoshsinghrahar can participants also suggest reviews on other participants pull request ?

**Comment by PrashanthPuneriya** [comment]
> @paritoshsinghrahar can participants also suggest reviews on other participants pull request ?

Reviews from anyone are welcomed :)

**Comment by ashwinijha6** [comment]
@paritoshsinghrahar could u pls review my pull request I have made the changes u suggested

**Comment by ashwinijha6** [comment]
@PrashanthPuneriya could u pls review my pull request

**Review by PrashanthPuneriya — COMMENTED** [review]
The following link is enough to include. There is no need of extra parameters in the link. https://medium.com/@ashwinijha006/open-source-hack-experience-mentorship-backend-ebda1f3ca47d

Also, top participants are judged based on their contributions to the community and active participation but, you have mentioned in your blog that top participants = maximum merged PRs. Anyway, I totally enjoyed reading the blog :)

**Comment by ashwinijha6** [comment]
> The following link is enough to include. There is no need of extra parameters in the link. https://medium.com/@ashwinijha006/open-source-hack-experience-mentorship-backend-ebda1f3ca47d
> 
> Also, top participants are judged based on their contributions to the community and active participation but, you have mentioned in your blog that top participants = maximum merged PRs. Anyway, I totally enjoyed reading the blog :)

Ok @PrashanthPuneriya next time I'll take care about the link & I guess it's written in the site that top participants(maximum merged PRs) that's why I mentioned, didn't know about the active participation part. Thanx for appreciating my work.

**Review by vj-codes — APPROVED** [review]
Thank you for your contribution @ashwinijha6 🎉

**Comment by vj-codes** [comment]
Closing this PR , your contribution is noted [here](https://docs.google.com/document/d/1EWxpM5A9sIR4uDf7nJ0WGPi3L77q_pv9VkuPujO7vts/edit?usp=sharing)

**Pull request closed without merging**
