### PR TITLE
Added Features in the Readme.md

### LINKED ISSUE #528: Create a bulleted list of features the app has on the README
## Description
As a contributor,
I need to know the app's features,
so that I can know more about the app before working on it.

The README has practical information on how to contribute to the app and a small description of the app, but misses some information about the features it has, like see members of the app, send mentorship request.

### Update [Required]
- [ ] Add a bullet list of high-level features to the README

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by Kunal1198**
### Description

Added bulleted list of features in the Readme.

Fixes #528

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

### CODE REVIEW

**Review by vj-codes — CHANGES_REQUESTED** [review]
@Kunal1198 please remove the extra lines , just one line after title  and last feature is fine , also  the lines between 4th and 5th feature.
The [Android repo](https://github.com/anitab-org/mentorship-android) has similar section , please go through that once
I'll tag the content team for better review  if no one responds , I'll suggest/approve :)

**Comment by vj-codes** [comment]
@anitab-org/content-team This PR needs review .Thanks!

**Comment by Kunal1198** [comment]
@vj-codes I removed the extra lines and also the lines in between 4th and 5th feature.

**Comment by isabelcosta** [comment]
@Kunal1198 please try to follow the pull request template. Include the id of the issue you are solving, please.

**Comment by Kunal1198** [comment]
I updated the PR template and also included the id of the issue. @isabelcosta please review.

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@Kunal1198 can you please squash your commits in one. Also we have a commit message guideline, please follow that

**Review by isabelcosta — CHANGES_REQUESTED** [review]
Thank you for your contribution @Kunal1198 !

Can you please add this section as the first section after the table of contents is shown, and also make it appear on the table of content as an entry?

**Comment by vj-codes** [comment]
@Kunal1198 please update the above requested changes .Thanks!

**Comment by isabelcosta** [comment]
@Kunal1198 I will close this PR due to lack of update within the time asked in contribution guidelines.
Thank you for your contribution!
cc @vj-codes

**Pull request closed without merging**
