### PR TITLE
Added Mentorship Relation Tasks feature

### LINKED ISSUE #82: Create Tasks database model, DAO and API list method
## Description
As a developer,
I need to create Task database model,
so that I can start creating the APIs.

Anyone in the current mentorship relation, mentor or mentee, can create, delete tasks and mark them as achievements.

### Update
- [x] Create the database model
- [x] Create tests for the database model
- [x] Create DAO list function
- [x] Create tests for the DAO function
- [x] Create API to list tasks
- [x] Create tests for API list endpoint

## Definition of Done
- [ ] All of the required items are completed.
- [ ] PR should be sent to the `gsoc18-code` branch
- [x] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description

Completed a simple version of the Tasks feature
Tasks feature is a JSON object part of TasksListModel which has a 1:1 relation with MentorshipRelationModel.
I'm not allowing for users to create a task which is already achieved.

A task entity will have the following format. This is the JSON response returned by the List all Tasks API:
```
[
  {
    "id": 3,
    "description": "sloa loa loag",
    "is_done": false,
    "created_at": 1534132997.472032,
    "completed_at": null
  },
]
```

Request Body:
```
{
    "description": "sample text"
}
```

New APIs:

apis exceprt on Swagger

**Note**: You may notice that I deleted some repeated code from tests, this is related to the setup of Mentorship Relation tests, there was a lot of repeated setup that I moved to a file which has this common setup. I did this in this PR because I was already changing this files to adapt to the new changes on MentorshipRelationModel.

Fixes #82 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Created extensive tests for each module: DAO, database model and API
Tests can be still improved, although I think the ones I developed are enough for now.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [x] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by isabelcosta** [comment]
@m-murad you suggested more fields in a weekly meeting:
```
{
           "id": 1,
           "create_on": 456789098765,
           "create_by": "Someone 1",
           "title": "Title 1",
           "description": "Description 1",
           "done": true,
           "completed_on": 12345678,
           "completed_by": "Someone else 1"
}
```

Also Current Mentorship Relation API does not return tasks yet, but I think this can be added in a later PR. This will be helpful for Current Relation screen on the android application.

@systers/maintainers-mentorship-android thoughts on this? 1º Extra fields; 2º Add or not the tasks response together with the list relation API? Do this on this PR or another?

**Comment by Dilu9218** [comment]
I think it would be better to do it in a separate PR

**Comment by isabelcosta** [comment]
@Dilu9218 I think too. just because its an enhancement, even though necessary, it is an enhancement, this PR has the basis of the feature.

**Review by Dilu9218 — APPROVED** [review]

**Review by r00pal — APPROVED** [review]

**Comment by r00pal** [comment]
@isabelcosta  do the enhancements in a separate PR taking this as the basis. I'm merging this one.

**Comment by isabelcosta** [comment]
OK thank your for merging it @roopalJazz. Now I should create the PR for merging gsoc18-code into develop?

**Pull request merged**
