### PR TITLE
Add a query parameter support to GET /users, to order users by name a…

### LINKED ISSUE #420: Add query parameter to sort users for GET /users and GET /users/verified APIs
## Description

As a user of the app,
I need to have ordering capabilities,
so that I can order the users by certain attributes.

APIs used to fetch Users, don't have an option to be sorted by a certain attribute. We want to be able to filter users by name (alphabetically order) and creation date. Both should have ascending and descending order option. The idea is having a "order" parameter.

Example of order:
"name_asc" = order by name alphabetically order ascending
"name_desc" = order by name alphabetically order descending

This ^^ is just a suggestion, up for dicsussion

Please, commit your change using our [Commit message Style Guide](https://github.com/systers/mentorship-backend/wiki/Commit-Message-Style-Guide).

### Update [Required]
- [ ] Add a query parameter support to GET /users, to order users by name and creation date (both ascending and descending order).
- [ ] Update Swagger UI documentation for this API.
- [ ] Write at least one test to prove your new feature is working.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by satya7289**
### Description
1. Add a query parameter support to GET /users, to order users by name and creation date (both ascending and descending order).
2. Update Swagger UI documentation for this API.
3. Write one test case to check where filter_by(name, creation date) and order_by(ascending or descending order) is working properly or not.

Fixes #420

### Type of Change:
- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
When filter_by=0 (filter by name) and order_by=0 (ascending order)
filter0order0

When filter_by=0(filter by name) and order_by=1(descending order)
filter0order1

When filter_by=1(filter by creation date; use email_verification_date) and order_by=0(ascending order)
filter1order0

When filter_by=1(ffilter by creation date; use email_verification_date) and order_by=1(descending order)
filter1order1

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Update Swagger UI documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by isabelcosta — CHANGES_REQUESTED** [review]
Thank you @satya7289 for this contribution :)

I just have a note: here the filter is a required parameter, but I think we should not enforce the user to filter ("0" or. "1"), but we could have a default filter. Also, this issue is more about ordering instead of filtering. Filtering would be another issue we have which is "search_by" that implements the search by name. Here we want to just order the list.

So what about having identifiers like, a set of possible values that determine the order such as:
- "name_asc" = order by name alphabetically order ascending
- "name_desc" = order by name alphabetically order descending

This is just a suggestion I came up with right now, just to give you an idea of what we want from the issue. Let me know what do you think, or if you have any other ideas for the implementation.

**Comment by satya7289** [comment]
Thanks for the review of this PR.
For this issue, I only set the ordering part as name_asc and name_desc and make it optional and remove the filter part. If user set name_asc to 1 then it sorts by(name) ascending order and if user set name_desc to 1 then it sorts by (name) descending order if nothing then no sorting is there.

Do I need to resolve the conflict for this PR?

**Comment by isabelcosta** [comment]
@satya7289 I am confused, is the PR #488 the same as this one? Do you want to close this PR?

**Comment by isabelcosta** [comment]
@satya7289 If your problem here was about fixing the merge conflicts, be aware that the solution is not creating another PR, but actually doing another commit where you fix the conflicts. If you get the same issue in the next PR please ask for help so we can help you learn how to do it. I will close this PR.

**Pull request closed without merging**
