### PR TITLE
style: format strings using f-strings in app/api/resources/user.py

### LINKED ISSUE #739: Use f-strings on User Resources file
## Description
As a developer,
I need change strings interpolation in User Resources file,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `app/api/resources/user.py` file.

## Mocks

As an example, here:

https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/app/api/resources/user.py#L171-L172

We can use f-strings such as:

```
@users_ns.response(HTTPStatus.CREATED, f"{messages.PASSWORD_SUCCESSFULLY_UPDATED})
```

### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for `app/api/resources/user.py` file

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by KushalBeniwal**
### Description

Used formatted strings instead of %-formatting in app/api/resources/user.py

Fixes #739 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Tested using existing tests by running
`python -m unittest discover tests`

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by devkapilbansal — APPROVED** [review]
Great work @KushalBeniwal 

LGTM :+1:

**Review by isabelcosta — APPROVED** [review]
Awesome work @KushalBeniwal 👏🏾 
Thank you for contributing!

**Comment by isabelcosta** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

   * _Ran locally and opened Swagger_  
     _Screenshot/gif_:  

fetch user by id swagger UI

     _Expected Result_:  Messages show up on Swagger UI just as before. There should be no difference visually
     _Actual Result_: Messages are being shown correctly

3. Additional Comments: N/A

4. Status of PR Changed to: Ready to Merge.

**Comment by isabelcosta** [comment]
Your PR just got merged @KushalBeniwal 👏🏾  Congrats on your first contribution with us!

**Pull request merged**
