### PR TITLE
refactor: Formatted the code

### PR DESCRIPTION
**Pull request by devkapilbansal**
### Description

- I use black as described in #478 for code formatting.
- Isort is used to alphabetically sort imports and other stuffs
- Formatted messages to increase readability

### Type of Change:

- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Ran `python -m unittest discover tests` to ensure all tests passed.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by devkapilbansal** [comment]
@rpattath @vj-codes please review this PR

**Comment by vj-codes** [comment]
@devkapilbansal hey which issue is this PR created for ?

**Comment by devkapilbansal** [comment]
> @devkapilbansal hey which issue is this PR created for ?

@vj-codes While testing I saw that code is not formatted well in files like `messages` etc. That's why I make this PR

**Comment by vj-codes** [comment]
@devkapilbansal that's great but the community guidelines suggest that a PR should be created only when a particular issue is assigned to you .
Also this is a huge change to code so
If refactoring is necessary right now , I would suggest to break up the code and create small issues for the same. What say ?

**Comment by devkapilbansal** [comment]
Okay I should open an issue for this but the formatting is done using the formatter as mentioned in #478 therefore I don't think the we should break it in different PRs as there is no code change

**Comment by vj-codes** [comment]
Ahhh okay I thought you had done it manually formatter works good also the build is passing , then can you create an issue and comment there. I'll just assign it to you .
It just helps us (project managers) to keep better track :)

**Comment by SanketDG** [comment]
I am already doing this in https://github.com/anitab-org/mentorship-backend/pull/710, so I am not sure how this will integrate

If it helps in the future, please do a search about what you are going to fix in the issues and PRs list.

**Comment by devkapilbansal** [comment]
> I am already doing this in #710, so I am not sure how this will integrate
> 
> If it helps in the future, please do a search about what you are going to fix in the issues and PRs list.

@SanketDG Ohh, extremely sorry that I don't saw your pull request. Should I close this PR?

**Comment by SanketDG** [comment]
Yes, but feel free to find another issue and work on it!

**Pull request closed without merging**
