### PR TITLE
Update CONTRIBUTING.md

### LINKED ISSUE #430: Update CONTRIBUTING.md adding project specific guidelines
## Description
As an open source contributor,
I need updated CONTRIBUTING.md,
so that I can know what is the desired procedure when contributing to the repository.

What to update?
- Communication channel (mention Zulip website and proper channels)
- Follow Commit Message Style Guidelines
- Have an issue matching the problem the PR is fixing (preferable)
- When submitting a PR with changes to UI, add screenshots to the PR description
- When making a new feature, try to include at least one test for it
- Follow the PR template
- Squash commits (at least be aware that we will squash it when merging)

### Update [Required]
- [ ] Add and update the CONTRIBUTING.md

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description

I updated the CONTRIBUTING.md with the project-specific guidelines that have been followed since the beginning of the project.

Fixes #430 

### Type of Change:

- Documentation

### How Has This Been Tested?

N/A

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by isabelcosta** [comment]
Changed to WIP because I want to see if the relative paths work. I think some might not work, will fix it.
@m-murad I would like to have your review as well, if you can

**Review by m-murad — DISMISSED** [review]

**Comment by m-murad** [comment]
@isabelcosta 
Everything looks good, but I guess we should merge this in `gci-dev` branch so that there are no merge conflicts later.

**Comment by isabelcosta** [comment]
Thank you for reviewing it @m-murad ! 🙌 
I agree this should be merged after GCI, so I could get some work done already.

**Comment by isabelcosta** [comment]
TODO: I have to add a line for [following this guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings) when writing docstrings.

**Review by isabelcosta — COMMENTED** [review]
Need to add the following:
- a line for [following this guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings) when writing docstrings.
- when raising a bug issue, follow the BUG_REPORT.md template

**Comment by mayburgos** [comment]
Testing the Travis CI Details link. Closing the PR and re-opening to see if the link updates itself.

**Review by m-murad — APPROVED** [review]

**Pull request merged**
