### PR TITLE
replace hardcoded messages and errors with constants.

### LINKED ISSUE #116: Save error and success messages into an array and replace hardcoded text
## Description
As a developer,
I need hardcoded error messages to be saved in an array,
so that I can avoid bugs related to the usage of hardcoded strings and pay attention to the repeated messages.

On backend save common messages of error and HTTP codes on a JSON
Have an Array of messages instead of using all over the code hardcoded text

Find a way to avoid hardcoded messages, that can be duplicated, with small differences. Make this uniform?!

### Update [Required]
- [ ] Suggestion: Create arrays for both success and error messages joined to replace hardcoded text
- [ ] Suggestion: Have an array for error codes as well to see clearly the meaning of the error codes
- [ ] Fix tests accordingly

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
5 hours

### PR DESCRIPTION
**Pull request by CleverFool77**
### Description
This PR changes the hardcoded errors and messages with constants.

I created a `constants.py` file in which messages have been assigned to variables. I preferred this choice over arrays as in arrays , it is need to keep track of indexes for particular messages or every time search for the message required.This approach can make the system slow as searching over arrays is time-consuming task.
I didn't use dictionary to store the data as it would have again lead to hardcoding of strings when accessing the key in the dictionary.

Having all the constants stored in a constants file makes it easier to maintain and use the constants and also faster as it's only importing the specific variable only. I looked in other orgs to find how they handle this problem and found that they are also using constants for hardcoded strings.

Fixes #116

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by isabelcosta** [comment]
Please check why Travis ci is failing and this comment https://github.com/systers/mentorship-backend/pull/183#pullrequestreview-196826877 to improve your PR @CleverFool77

**Comment by isabelcosta** [comment]
Why did you close this issue @CleverFool77?

**Comment by CleverFool77** [comment]
I made a new PR @isabelcosta as I messed up my branch while resolving the tests, so in a new branch I have done changes in tests so that mismatch can be removed .https://github.com/systers/mentorship-backend/pull/186

When I run the unitests commands in terminal, it failed due to such examples
Eg :
```
Test file= "This mentor is not available" 
Other file ="The mentor is not available" 
```
Due to such mismatches the test were failing and showing errors.

**Comment by isabelcosta** [comment]
I saw some of your problems in the pr, but I didn't have time to explain you at that time. Next time don't close and create a new one, most of the times there is no need for that. Next time ask for help, so we can help you fix the problem before you create another PR. If and when I ask you for changes in the other PR, you should make the changes on that pr. Once I find some time I'll review your PR. @CleverFool77

**Comment by CleverFool77** [comment]
Thanks @isabelcosta It was my time first time contributing in an org. I didn't know that.I'll keep that in mind and surely ask for help :) .

**Comment by isabelcosta** [comment]
@CleverFool77 No problem, we're here to learn ;)

**Pull request closed without merging**
