### PR TITLE
fix: Add local as an option for FLASK_ENVIRONMENT_CONFIG variable in env.template file 

### LINKED ISSUE #663: Add a missing environment config value to .env.template
[environment-variables.md](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md) doc specifies that the run configuration has 4 options: `dev`, `local`, `test` and `prod` values to be loaded. But, **FLASK_ENVIRONMENT_CONFIG** variable under [.env.template](https://github.com/anitab-org/mentorship-backend/blob/develop/.env.template) file doesn't include `local` value as an option.

### PR DESCRIPTION
**Pull request by PrashanthPuneriya**
### Description

Adds `local` value as an option for **FLASK_ENVIRONMENT_CONFIG** variable.

Fixes #663 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Review by vj-codes — APPROVED** [review]
Congrats on sending your first PR to backend repo!!! @PrashanthPuneriya

**Comment by vj-codes** [comment]
@PrashanthPuneriya Just remember about creating a new branch again while working on other issues

**Comment by PrashanthPuneriya** [comment]
@vj-codes Thanks! I will remember it.

**Review by isabelcosta — APPROVED** [review]
Great work @PrashanthPuneriya 👏 👏 👏 
Thank you for this contribution 🎉

**Comment by isabelcosta** [comment]
@anitab-org/qa-team this PR was not tested because it is a documentation task

**Pull request merged**
