### PR TITLE
Spelling mistake correction in the documentation.

### LINKED ISSUE #780: Spelling mistake in the subtitle of the documentation section.
**Description**
There is a spelling mistake in the Documentation section of the Readme it is in the first line itself, identify the word and correct the spelling.

**Acceptance** **Criteria**

- [ ] update required

**Definition of Done**

- [ ] All of the required items are completed.

- [ ] Approval by 1 mentor.

**Estimation**
   5 minutes.

**Note**
This issue will be assigned from September 1, 2020.

### PR DESCRIPTION
**Pull request by rutujadhanawade**
### Description

There was a spelling mistake in the Documentation section of the Readme. I have corrected it.

Fixes #780 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by rutujadhanawade** [comment]
@vj-codes @yashasvimisra2798 please review this. This is part of OSH .

**Review by yashasvimisra2798 — APPROVED** [review]

**Comment by yashasvimisra2798** [comment]
Good work @rutujadhanawade !

**Review by yashasvimisra2798 — APPROVED** [review]

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Review by isabelcosta — APPROVED** [review]
thank you for your contribution @rutujadhanawade 🎉

**Pull request merged**
