### PR TITLE
Perform manual testing and report PUT /user API #767

### LINKED ISSUE #767: Perform manual testing and report PUT /user API
## Description

As a tester,
I need to test PUT /user API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#update-user](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#update-user)

### Update [Required]
- [ ] Test PUT /user API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by yash2189**
### Description

To test the PUT /user API #767 and create a report regarding the same under /docs/manual_tests

Fixes #767 

### Type of Change:

- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Tested the REST API with Swagger UI provided in the link of the deployed server.
Carried out tests on PUT /user and PUT /user/change_password
Created a markdown file under /docs/manual_tests for reports regarding the tests.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by gaurivn** [comment]
@yash2189, can you please squash the commits

**Comment by yash2189** [comment]
@gaurivn I have pushed my commits on the develop branch itself instead of creating a new branch and raising PR for the same. I know I did a mistake by not creating a separate branch . But is it possible that I can squash commits on my develop branch?

**Comment by gaurivn** [comment]
Please remove the screenshots, they are not needed. And instead of making all changes here and squashing, I suggest it would be better to open a fresh PR from a branch other than develop without adding screenshots in a separate folder.

**Comment by yash2189** [comment]
I just included the screenshots as they were specified in the description of the issue. #767
So should I close this PR and fork the repository again, create a new branch from that or is it possible to make changes in the existing repository only like creating a new branch in this repository itself .

**Comment by gaurivn** [comment]
@yash2189, yes screenshots are required for this issue no changes for that and there is no need to fork a repo once already forked. However, if you want to delete and fork again because of some issues in updating ..then please make sure you don't have any open PRs and previous PRs if any were merged.

**Comment by yash2189** [comment]
@gaurivn I will just squash the commits then instead of closing this PR

**Comment by yash2189** [comment]
@gaurivn Please review my PR

**Comment by yash2189** [comment]
Why did the build fail @gaurivn ?

**Comment by yash2189** [comment]
I am closing this PR since it has build issues

**Pull request closed without merging**
