### PR TITLE
Added pagination of users endpoint

### LINKED ISSUE #279: Allow pagination of /users endpoint
**Is your feature request related to a problem? Please describe.**
Currently, the only way to get a list of users is to `GET /users`. There's one problem with this approach: as there will be more and more users, the size of the data returned will proportionally grow.
As of now it isn't a problem, but imagine what happens when we have 5000 users?

**Describe the solution you'd like**
I'd like to have pagination support in `GET /users` endpoint. Instead of returning all users at once, it'd return, say, 50 and upon a next request, another 50.
I've never done pagination before so I don't exactly know how this could be implemented,but I think the effort put will be worth it. Maintaining scalability is really important.

**Describe alternatives you've considered**
I'm not aware of other alternatives.

### PR DESCRIPTION
**Pull request by bartekpacia**
### Description
As the title says. I've done it by using [`BaseQuery.paginate()`](https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/#flask_sqlalchemy.BaseQuery.paginate) method exposed by SQLAlchemy.

Page number can be controller using `page=[int]` query param at `/users` endpoint/
Fixes #279 

**TODO**
- I will update the documentation ASAP so it will take pagination into account/
- Implement pagination to other types of resources - I'm working on this

### Type of Change:
- Code
- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested manually with postman + all test pass.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mayburgos** [comment]
Sorry for this inconvenience. Checking to see if the Travis CI details link updates after closing and opening this PR.

**Review by ramitsawhney27 — DISMISSED** [review]
Very nice and clean usage of SQLAlchemy for pagination. Great work!

**Comment by isabelcosta** [comment]
@ramitsawhney27 thank you for the review! It helps me a lot understanding if this is a feasible solution.
I just want to find a time to run this branch code and perform tests on it, so that I can review and approve.

**Comment by isabelcosta** [comment]
@bartekpacia could you fix the merge conflicts?

**Comment by bartekpacia** [comment]
@isabelcosta sure, will do!

**Review by isabelcosta — COMMENTED** [review]
@bartekpacia can you please fix the merge conflicts? I think this happens after your work on type hints

**Comment by bartekpacia** [comment]
@isabelcosta sure
tbh I forgot about it🙄

**Comment by bartekpacia** [comment]
@isabelcosta Resolved

**Comment by bartekpacia** [comment]
I have no idea why it fails, all tests pass successfully on my machine🧐

**Comment by isabelcosta** [comment]
@bartekpacia @ramitsawhney27 I am testing this now and even when I select a page this is not working properly, it returns all content of users list. I will see if I am doing something wrong.

**Comment by bartekpacia** [comment]
@isabelcosta Don't waste your time, the code doesn't handle pagination from what I've seen.

**Comment by bartekpacia** [comment]
Now, I wonder how I did this that it worked...I guess I should write more docs next time👀

**Comment by isabelcosta** [comment]
@bartekpacia I just noticed that USERS_PER_PAGE variable is not being used :P I know this was just a proposal at first right? Do you wish to continue this work? I am fine either way :)

**Comment by bartekpacia** [comment]
@isabelcosta I think `USERS_PER_PAGE` can be passed to SQLAlchemy methods (like `paginate`) to easily add the pagination behavior.
Regarding my further work: I'm afraid I don't have enough time, even tho schools are closed, I find myself busy all the time🤨
What do you think about closing it, but creating a separate issue related to pagination for GSOC students (and linking this issue & PR from that newly created issue as a reference/hint/basic example)?

**Comment by isabelcosta** [comment]
@bartekpacia thank you for your insight on the solution to this. It makes sense :)

Regarding your continuing your work here, I am totally fine with what you decide. All I need is to contributors to be honest about their availability, so I highly appreciate that you are telling me you won't continue this. I think I will close this PR and leave your issue open because it is still needed. I will mention on the PR that what is left is that little change if they want to continue your implementation.

This can totally be done before GSoC, open source is all year so we don't have to hold this to a GSoC student. Also, worth mentioning, this is an important feature, we are already having timeout issues on the Android app. I think this would fix that issue.

**Pull request closed without merging**
