### PR TITLE
Tests: Use super() without arguments for Python3 only support

### LINKED ISSUE #595: Add only Python3 support in tests
## Description
I was working on an issue to alter the test structure of the project and discussing with a maintainer we found out that the project should only support python 3 but in some tests, this is not achieved. For example, in tasks_base_setup this is happening:
image
The setup method should be written like this
<code>
super.setUp()
</code>

## Acceptance Criteria
- [ ] Refactor all the test bases which support Python2 to Python3 as presented
- [ ] All local testing passing
### Update [Required]
- [ ] tests/tasks/tasks_base_setup 
- [ ] tests/mentorship_relation/relations_base_setup 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by Aaishpra**
### Description

Refactored .super() function in each of the tests for Python3 only support.

Fixes #595

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

Ran python3 -m unittest test tests/folder/file.py for every test manually

All tests passing.

Screenshot taken after running 

``` python3 -m unittest test tests/users/test_api_list_users.py ```

image

Similarly, all the tests were tested with successful result

Also this
image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Aaishpra** [comment]
@isabelcosta @devkapilbansal @vj-codes need a review here.

**Review by isabelcosta — APPROVED** [review]
🧹 what a cleaning work 👏 
Thank you so much for contributing @Aaishpra 🎉

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Comment by isabelcosta** [comment]
@vj-codes I will merge this since this is naturally tested with PR checks, in particular, the "Run tests" check. So no need for manual testing.

**Pull request merged**
