### PR TITLE
removed unnecessary imports

### LINKED ISSUE #733: Remove unrequired Optional import from typing package
**Describe the bug**

There is no usage of `typing.Optional` import in [user.py](https://github.com/anitab-org/mentorship-backend/blob/develop/app/database/models/user.py) file.

**Expected behavior**
There shouldn't be any unnecessary imports.

**Screenshots**
image

**Additional context**
Remove the unnecessary import from the mentioned file and also search for any other unnecessary imports and remove them.

### PR DESCRIPTION
**Pull request by vaibhavarora102**
removed unnecessary imports

### Description

removed unnecessary imports, as stated in the issue

Fixes  #733

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Just removed unnecessary imports and rest was working well and as it is

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by PrashanthPuneriya** [comment]
I have no idea why codecov/project is failing and no idea about codecov at all :(
Can someone please shed some light on this? @SanketDG @isabelcosta
I am sure that the import was not necessary and can be safely removed. Am I wrong?

**Review by SanketDG — APPROVED** [review]
Codecov issue is a false positive one, we can merge this!

**Review by PrashanthPuneriya — APPROVED** [review]

**Comment by vaibhavarora102** [comment]
can someone tell, what is the next step for me 
and when would this be merged

**Comment by PrashanthPuneriya** [comment]
> can someone tell, what is the next step for me
> and when would this be merged

You can take up other issues and work on them :)

**Comment by vaibhavarora102** [comment]
will this be merged soon?

**Comment by PrashanthPuneriya** [comment]
Most probably @vaibhavarora102 . Incase if you're confused, you can always work on other issues even if a PR hasn't been merged. :)

**Comment by vaibhavarora102** [comment]
Okay

**Review by isabelcosta — APPROVED** [review]
Great work @vaibhavarora102 👏 
Thank you for your contribution!

**Comment by isabelcosta** [comment]
@anitab-org/qa-team I will merge this since this is not a change that affects a feature. If the tests pass, it means that this import was really unnecessary.

**Pull request merged**
