### PR TITLE
docs: Added OSH Experience Blog

### LINKED ISSUE #904: blog: OSH Experience
## Description

I want you to write a blog about the OSH experience from a newcomer's point of view for the backend repo. So that it tells your experience about open source and also may serve as an intro to backend repo for prospective contributors.

Write a blog on Medium and share the link in a document called `outreach-work.md` in the “/docs” folder of mentorship-backend. So you need to create a post and add a new line to this document. 

#### Mention AnitaB.org as a publication while publishing the blog/article (called: story on medium) at the end of your blog.
https://medium.com/anitab-org-open-source

### Update [Required]
- [ ] [Submit Blog. Add line to `outreach-work.md`]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1 Hour] hours

### PR DESCRIPTION
**Pull request by devkapilbansal**
### Description

Fixes #904 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by devkapilbansal** [comment]
@paritoshsinghrahar please review this

**Review by paritoshsinghrahar — CHANGES_REQUESTED** [review]
It can be improved.

Before "What is OSH? and Rules" describe an intro in a more appealing and exciting way.
Tag your article in relevant #hastags Open Source, Backend etc. 
Even Rules part like: Note:- All issues must have the label “Open Source Hack” to be eligible for the program. More details seem redundant to an external reader.

Have you marked AnitaB.org while publishing to feature the publication? Ik, you faced issues let's wait and see.

**Comment by devkapilbansal** [comment]
> It can be improved.
> 
> Before "What is OSH? and Rules" describe an intro in a more appealing and exciting way.
> Tag your article in relevant #hastags Open Source, Backend etc.
> 
> Have you marked AnitaB.org while publishing to feature the publication?

I tried but I wasn't able to add AnitaB.org as publication.
Also, I tried to give intro to OSH in What is OSH?
Should I remove the label or give intro of mentorship-backend only.

**Comment by paritoshsinghrahar** [comment]
> Should I remove the label or give intro of mentorship-backend only.

No heading is all fine. Just a little different manner of writing.

**Comment by paritoshsinghrahar** [comment]
> `hereIt` seems difficult for newcomers to come in the field of Open Source ..........................................

I think this is a grammatical mistake here. Please proofread the article again. Just to be sure.

**Comment by devkapilbansal** [comment]
Ok I will thanks for review

**Comment by paritoshsinghrahar** [comment]
I changed the issue description like this:

> #### Mention AnitaB.org as a publication while publishing the blog/article (called: story on medium) at the end of your blog.
> https://medium.com/anitab-org-open-source


Please take note.

**Review by vj-codes — APPROVED** [review]
Thank you for your contribution @devkapilbansal 🎉

**Comment by vj-codes** [comment]
Closing this , your contribution is noted [here](https://docs.google.com/document/d/1EWxpM5A9sIR4uDf7nJ0WGPi3L77q_pv9VkuPujO7vts/edit?usp=sharing)

**Pull request closed without merging**
