### PR TITLE
[Program:GCI] Fetching User Profile picture using Gravatar

### PR DESCRIPTION
**Pull request by rudrakshjhalanii07**
### Description
This feature implements fetching and storing the user profile picture using Gravatar through user's email. 

Fixes # [ISSUE]
#326 

### Type of Change:
**Delete irrelevant options.**

- Code
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested manually and was working fine, as expected.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [x] Update requirements.txt

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by rudrakshjhalanii07** [comment]
The changes of line breaks was auto-generated(can't say how), but it ultimately doesn't change anything!

**Review by sara-02 — APPROVED** [review]
Hey, @Hardik0403 I would highly suggest avoid adding/deleting these spaces, I know it is mainly auto-correct by editors but it can be distracting.
As for the code, good work, it does as expected.

**Comment by rudrakshjhalanii07** [comment]
> Hey, @Hardik0403 I would highly suggest avoid adding/deleting these spaces, I know it is mainly auto-correct by editors but it can be distracting.
> As for the code, good work, it does as expected.

It was indeed auto-corrected by the editor!

**Comment by isabelcosta** [comment]
I am closing this because during final evaluations of PRs we decided to proceed with PR #334
Thank you for your contribution during GCI contest 🙌

**Pull request closed without merging**
