### PR TITLE
swagger-cleanup

### LINKED ISSUE #774: Clean up the swagger to follow the same convention throughout the page
## Description
As a contributor,
I need proper convention used in Swagger,
so that it doesn't appear oddly.

## Mocks
image
As one can easily see that, capital letters are not used when required and full stops are redundant at few places. e.g. relations begin with small letter unlike others and the last two have full-stops whereas others don't.

### Update [Required]
- [ ] Start every sentence with capital.
- [ ] Remove full stops to follow same convention.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hour if you don't know where to look.
15 mins if you know where to look.

### PR DESCRIPTION
**Pull request by aditya2499**
### Description

Fixes #774 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

### CODE REVIEW

**Review by PrashanthPuneriya — APPROVED** [review]
LGTM :)

**Review by vj-codes — APPROVED** [review]
@aditya2499 Congrats on your first contribution to the repo! 🎉 
LGTM

**Comment by aadityamp01** [comment]
> @aadityamp01 Congrats on your first contribution to the repo! 🎉
> LGTM

Hey! @vj-codes  it's not me, please tag @aditya2499

**Review by yashasvimisra2798 — APPROVED** [review]

**Comment by yashasvimisra2798** [comment]
Well done @aditya2499 :)

**Review by isabelcosta — APPROVED** [review]
Great work @aditya2499 👏 👏 
Thank you for your contribution!

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1:

**Comment by rpattath** [comment]
@devkapilbansal did you test this locally. If so please upload the screenshots.

**Review by devkapilbansal — APPROVED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Clean up swagger
    _Screenshot/gif_:  
      Before 
before

     After
After

3. Additional testcases covered: Run `python -m unittest discover tests` to ensure all tests passed.

5. Status of PR can Changed to: Ready to Merge.

**Comment by devkapilbansal** [comment]
> @devkapilbansal did you test this locally. If so please upload the screenshots.

@rpattath done :+1:

**Comment by isabelcosta** [comment]
@devkapilbansal thank you so much for that detailed test report 👏 🎉 really really amazing work!

**Pull request merged**
