### PR TITLE
updated docusaurus.config.js

### PR DESCRIPTION
**Pull request by msaini28r**
issue solved. #1146

### Description

Fixes # [ISSUE]

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [x] Update Postman API at /docs folder
- [x] Update Swagger documentation and the exported file at /docs folder
- [x] Update requirements.txt

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by msaini28r** [comment]
issue solved. #1146

**Comment by msaini28r** [comment]
changes done. #1145

**Comment by devkapilbansal** [comment]
Spammy PR. This issue is already solved

**Comment by isabelcosta** [comment]
thank you @devkapilbansal 🙌🏾

**Pull request closed without merging**
