### PR TITLE
Fix #189: User can update details as empty string.

### LINKED ISSUE #189: In edit profile section,if user removes his/her details like bio,user name..they are not removed ,instead they are showing the older details again
**Describe the bug**
In edit profile section,if user removes his/her details like bio,user name..they are not removed ,instead they are showing the older details again

**To Reproduce**
1. Go to 'update user'
2. remove any details
3.save and see error

I want to work on this issue

### PR DESCRIPTION
**Pull request by sumit-badsara**
### Description
- __"Updated users.py in app/api/dao__ :
`data['key']` returned `false` for empty string, which blocked the entire process of updating the details.
- __Added tests in  test_dao_update_user.py in tests/users/__ : 
Tests check whether the fields are updated to None if the details are passed as empty strings.

Fixes #189 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
- Tested using unit tests
- Tested this locally
- Added tests for this change

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have added tests which verify the correctness of my change

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by isabelcosta** [comment]
Thank you for sending this PR @BadduCoder 🎉 
Once I save some time to review PRs and tested them accordingly, I'll take a look at this and let you know ;)

**Comment by sumit-badsara** [comment]
@isabelcosta Yeah sure! Thanks for the help :smile:

**Review by isabelcosta — CHANGES_REQUESTED** [review]
@BadduCoder this seems fine, even though I haven't yet tested locally.
Could you please add a couple of tests to prove this is working as intended?

**Comment by sumit-badsara** [comment]
Sure @isabelcosta! On it...

**Comment by sumit-badsara** [comment]
@isabelcosta I just saw the test for normal details update, so i created test in similar way for empty string, so is that okay or should i include other fields also, or should i merge both the tests together?

**Comment by sumit-badsara** [comment]
@isabelcosta I have also updated the PR description. If something is missing or needs to be changed, please let me know.

**Comment by sumit-badsara** [comment]
I have merged the tests, as it made more sense. Otherwise We could create a new test entirely to test this in similar fashion again. But as tests need to be standalone, maybe I am wrong.

- What the test was before : 
It updated the data of user and verified it
- What I added to the test :
After verifying that above thing works fine, It again updated the details with empty string and verified if they are updated to None.

**Comment by isabelcosta** [comment]
@BadduCoder great suggestion! I think creating a new test wouldn't hurt. It would make tests more focused on testing one small problem instead of testing everything within a single test. I think this is a better practice.

So my opinion is that you could leave the original test as it is, and create another test with another name (e.g.: `def test_update_fields_with_empty_data()`) on that same file.

What do you think?

**Comment by sumit-badsara** [comment]
Yes @isabelcosta that would be a better option, I was confused but keeping modularity is always a better approach.

**Comment by sumit-badsara** [comment]
@isabelcosta Changes done! I guess there must be no more issues left.

**Review by isabelcosta — APPROVED** [review]
Great work @BadduCoder 🎉 
Thank you so much for your contribution!

**Pull request merged**
