### PR TITLE
fix: Add local as an option for FLASK_ENVIRONMENT_CONFIG variable in env.template file

### LINKED ISSUE #663: Add a missing environment config value to .env.template
[environment-variables.md](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/environment-variables.md) doc specifies that the run configuration has 4 options: `dev`, `local`, `test` and `prod` values to be loaded. But, **FLASK_ENVIRONMENT_CONFIG** variable under [.env.template](https://github.com/anitab-org/mentorship-backend/blob/develop/.env.template) file doesn't include `local` value as an option.

### PR DESCRIPTION
**Pull request by PrashanthPuneriya**
### Description

Adds `local` value as an option for **FLASK_ENVIRONMENT_CONFIG** variable.

Fixes #663 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Review by vj-codes — CHANGES_REQUESTED** [review]
@PrashanthPuneriya please don't create PRs from develop branch of your fork , checkout to a suitable branch name and update this PR.

**Comment by PrashanthPuneriya** [comment]
@vj-codes Thanks for informing me. What should I do of this pull request then?

**Comment by vj-codes** [comment]
@PrashanthPuneriya just change the target branch of this PR, no need to send another one:)

**Comment by PrashanthPuneriya** [comment]
@vj-codes  Can you please elaborate? Just before your comment I have reset --hard this branch. Now I am confused. What should I do?

**Comment by vj-codes** [comment]
Ohhh now its better to send another PR
 there's an edit option available comparing the main branch and your fork branch , where you could  create a new one and update it  in the same PR.

**Comment by PrashanthPuneriya** [comment]
@vj-codes Ohh okay! My bad.
Just to clarify, now I need to create a new branch in my fork and make changes in that branch and then make a pull request from my branch to this develop-branch?

**Comment by vj-codes** [comment]
yupp @PrashanthPuneriya

**Comment by PrashanthPuneriya** [comment]
@vj-codes Can you please review #666 pull-request ? Thanks!

**Pull request closed without merging**
