### PR TITLE
docs: beautify swagger.json

### LINKED ISSUE #840: Beautify/Format Swagger.json
**Is your feature request related to a problem? Please describe.**
The Swagger.json page seems to be a bit congested. In order to make it look better we can try to beautify the json file, and present it in tree view format.
You can take a look at the idea in the link : https://codebeautify.org/jsonviewer

**Additional context**
Please comment below to get the issue assigned to you. This is a part of OSH and hence will be assigning it on First come first serve basis

### PR DESCRIPTION
**Pull request by khushishikhu**
Capture
### Description

Formatted swagger.json into tree view format through javascript

Fixes #840

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation
- [x] Update Postman API at /docs folder
- [x] Update Swagger documentation and the exported file at /docs folder

### CODE REVIEW

**Comment by khushishikhu** [comment]
@Shivansh2407  please have look on this PR. i have beautified some of the part of swagger.json data. To make sure if i am doing right or not . please guide me further

**Comment by khushishikhu** [comment]
@Shivansh2407  please review my pr

**Review by vj-codes — CHANGES_REQUESTED** [review]
@khushishikhu hey please keep the commits and files changed to one specific issue only .
All your previous commits and changes can be seen in this PR , so update accordingly

**Comment by khushishikhu** [comment]
@vj-codes  actually i tried to do that but unable to keep the commits belong to specific branch only as i have created the commits in my develop branch too. that's why my all commits are showing over here.

**Pull request closed without merging**
