### PR TITLE
Checked response to return error if status code is not 200

### LINKED ISSUE #437: endpoint /mentorship_relation/send_request does not validate users id
**Describe the bug**
When mentor_id to mentee_id is invalid Internal server error occurs (500)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to localhost try out'/mentorship_relation/send_request.'
2. Send mentorship relation request with non existing  ` "mentor_id": 0`, or `"mentee_id": 0`.
3. See internal server error

**Expected behavior**
Backend should return bad request with information that user with specific id does not exists

**Additional context**
`AttributeError: 'tuple' object has no attribute 'name'`

### PR DESCRIPTION
**Pull request by srivastava9**
### Description
Made a flag to check for responses and if its code is not 200, response error is returned.

Fixes #437 

### Type of Change:

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
I ran test cases on it, checked the API and attaching the image.

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes
Screenshot from 2020-02-23 05-48-59

### CODE REVIEW

**Review by isabelcosta — CHANGES_REQUESTED** [review]
@srivastava9 thank you for your contribution :)

Can you please provide an appropriate PR title, that can explain what you have done?
Also are you sure this fixes the issue? I'm saying this because from the logic you present I don't see how. Can you add a test to prove your solution works?

**Comment by srivastava9** [comment]
@isabelcosta Sorry for the vague title. I hope this one works. :)
Actually, in line 83, response is returned which contains a tuple of response and status code.,
Now from line 94, we call .getUser() which used to fails as no user with mentor /mentee 0 as it shows internal error.
So I added a check if response status code is not 200 it will return response thus displaying the error.
I have checked running it on API and passed all pre-existing tests.I hope there is no need of extra test as it is more on enhancing user experience.

**Comment by srivastava9** [comment]
@isabelcosta Could you please confirm this, or if you want I can try to add a test for this?

**Comment by isabelcosta** [comment]
@srivastava9 because you changed parts of the logic I would say you should create a test to prove that your solution works. You can follow other tests structure. let me know if you have more doubts

**Comment by srivastava9** [comment]
hey @isabelcosta my issue was same as #487 which has been fixed.
I have also had the same logic just the test cases which has been rightly added by @naveennvrgup in pr #489.

**Comment by isabelcosta** [comment]
@srivastava9 I am confused, what you did here was already fixed? If not and this is a valid change, can you please fix the merge conflicts, so that I can test this?

**Comment by naveennvrgup** [comment]
> hey @isabelcosta my issue was same as #487 which has been fixed.
I have also had the same logic just the test cases which has been rightly added by @naveennvrgup in pr #489.

@isabelcosta This exact same problem was fixed by me. As mentioned by @srivastava9  here. So I think it is safe to close this PR. @srivastava9 Thanks for pointing that out :angel:

**Comment by isabelcosta** [comment]
Ah ok @naveennvrgup  I will close this then :)
Thank you both for helping to manage this

**Pull request closed without merging**
