### PR TITLE
Fixed current API documentation on Swagger

### LINKED ISSUE #18: Add Swagger documentation for Login API
## Description
As a developer,
I need Swagger Login API documentation,
so that I can test the API and mantain the project.

### Update
- [x] Update endpoint /auth to /login
- [x] Update Swagger documentation to include Login API (automatically done by flask-jwt)
- [x] Update Swagger documentation to ask for headers regarding authorization tokens
- [x] Update postman.json on docs folder (update testing login)
- [x] Add swagger.json on docs folder

## Definition of Done
- [x] All of the required items are completed.
- [x] PR should be sent to the `gsoc18-code` branch.
- [x] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description
- Fixes API documentation;
- Adds swagger.json to docs folder;
- Updated postman.json;
- Fixed login endpoint (/auth -> /login)

Fixes #18 

### Type of Change:

- Code
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Swagger documentation can be accessed by http://localhost:5000 and be fully tested.
Also there's a swagger.json file with the new documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by m-murad** [comment]
Can you also add a point in PR template - Update the postman API and swagger documentation. Create a different issue and a different PR for this

**Comment by isabelcosta** [comment]
@m-murad fixed the postman url, will check the merge conflicts now for this issue

**Comment by m-murad** [comment]
@isabelcosta also one commit per PR

**Comment by isabelcosta** [comment]
@m-murad ok so squash all the 4 commits, right?

**Comment by m-murad** [comment]
Yes

**Comment by isabelcosta** [comment]
@m-murad @Dilu9218 the minimum number of commit that I can have is 2. 
- 1st commit for my changes
- 2nd to fix merge conflicts regarding your most recent PR

**Comment by Dilu9218** [comment]
@isabelcosta we can have a discussion on chat on how to make it to one commit. I will show you some commands.

**Comment by isabelcosta** [comment]
@Dilu9218 your git commands worked! thank you!

**Comment by Dilu9218** [comment]
@isabelcosta glad the commands worked. Accepting!

**Comment by isabelcosta** [comment]
@Dilu9218 @m-murad I'll fix the merge conflicts now and squash the commits. I'll update you when it is done so that you can do your review on this PR

**Comment by isabelcosta** [comment]
@Dilu9218 @m-murad merge conflicts are fixed and commits are squashed

**Review by Dilu9218 — APPROVED** [review]

**Pull request merged**
