### PR TITLE
test: Remove Python 2 support from tests

### PR DESCRIPTION
**Pull request by morrme**
### Description

Refactored .super() function in each of the tests as requested by issue #595 

Fixes # 595

### Type of Change:

- Quality Assurance
### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by morrme** [comment]
@SanketDG please review 🙂

**Comment by morrme** [comment]
@EfthymiaKostaki @isabelcosta

**Review by SanketDG — COMMENTED** [review]
This looks good!

There is still some Python 2 specific code left, so let's not talk about Python 2 and Python 3 at all, and let's just write `Use super() without arguments` as the commit message!

**Comment by morrme** [comment]
@SanketDG Done.

**Review by SanketDG — APPROVED** [review]

**Comment by isabelcosta** [comment]
@morrme Thank you for your interest in contributing to this project!
Have you read our [Contribution Guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md)?
Before sending a PR you have to ask to be assigned first. Please do that and then after assignment I can review this.

**Comment by isabelcosta** [comment]
@morrme let me know if you need any help or have any confusion.

**Pull request closed without merging**
