### PR TITLE
Rename dockerfile to start w capital letter

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description

Dockerfile starts with a non-capital letter, which causes this error when I try to run the project using Docker.

```
~/mentorship-backend gci-dev ❯ docker build -t mentorship-backend:latest .                                                                                     5s 01:05:26
Sending build context to Docker daemon  513.5kB
Error response from daemon: Cannot locate specified Dockerfile: Dockerfile
```

Fixes no specific issue

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

I ran: `docker build -t mentorship-backend:latest .`

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by annabauza** [comment]
can you please fill the form?

**Comment by isabelcosta** [comment]
Yes! I completely forgot about it! thank you @annabauza :)

**Comment by isabelcosta** [comment]
@annabauza do you think there is any item of the checklist that I should check? Because I left unchecked the ones that are not relevant to what I did. What do you think?

**Review by annabauza — APPROVED** [review]

**Review by sumit-badsara — APPROVED** [review]

**Comment by isabelcosta** [comment]
Thank you for your approvals @annabauza @BadduCoder ! Will merge now

**Pull request merged**
