### PR TITLE
fix: replacing hardcoded status code values with httpstatus module code

### PR DESCRIPTION
**Pull request by nandini45**
### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes  #532 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
When a user does a mistake instead of showcasing the error code it will show the meaning of the hard coded error value. It has been tested by doing a error and seeing what values it returns.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Update Postman API at /docs folder

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by isabelcosta — CHANGES_REQUESTED** [review]
@nandini45 there are some changes needed for this PR:
- Can you please edit the description of the PR with a proper description, how it was tested, ... this helps reviewers to better understand your changes
- Can you remove the changes done to the README, as they are related with another issue. This helps keep the PRs solving one specific task only, this facilitates the code review and keeping different concerns in separate commits.
- What the issue requires is: whenever you see a hardcoded HTTPStatus code being used, for example [here in this line of code](https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/dao/mentorship_relation.py#L68), you can see 400 being returned as the second argument. You should change it to `HTTPStatus.NOT_FOUND` (please check the documentation of [HTTPStatus module](https://docs.python.org/3/library/http.html)). So you don't need `app/rep_code.py` file.

Let me know if anything is unclear :)

**Comment by isabelcosta** [comment]
The latest commit you did is in accordance to what I was asking :) good work! Now you just have to replicate to the rest of the files :) @nandini45

**Comment by nandini45** [comment]
@isabelcosta  i think i did that too Isabel. i made all the changes in the app package

**Comment by isabelcosta** [comment]
@nandini45 you didn't commit that yet. For example this file `app/api/resources/admin.py` does not have that yet

**Review by isabelcosta — COMMENTED** [review]
@nandini45 Can you edit the PR description to include proper Description, `Fixes #ISSUE`, How Has This Been Tested?, and not the placeholder text?

**Comment by nandini45** [comment]
@isabelcosta  i had a question now can i ask more more issues to work on?

**Comment by isabelcosta** [comment]
@nandini45 changing description is not the same thing as changing the title. You changed the title of the PR. Here's how you can change the description of the PR:

image

After clicking "Edit" option you can edit "proper Description, Fixes #ISSUE, How Has This Been Tested?, and not the placeholder text".

Can you try this out?

**Review by isabelcosta — CHANGES_REQUESTED** [review]
@nandini45 can you please undo the README deletion?

**Comment by nandini45** [comment]
@isabelcosta  sorry for the silly mistakes. i made all changes you asked

**Comment by isabelcosta** [comment]
@nandini45 no problem with doing mistakes :) once you learned them you'll avoid these mistakes ;)

Another thing, in the PR description its supposed to be:
`Fixes #532`

instead of

`Fixes # replacing hardcoded status code values with httpstatus module code #532`

this will make GitHub close the issue you are solving once this is merged

**Review by isabelcosta — APPROVED** [review]
@nandini45 great work with this PR 🎉 
Thank you for your contribution!

I tested this manually, running a simple request to register a user with a username that already exists, so that I could get the error 400, which happened as expected. Here's a proof of what I did:

image

**Comment by isabelcosta** [comment]
I will request just a double check on the code, that I approved, and if all good and we get another approval I can merge this :)
And then we can create an issue to do the same in the tests module.

**Comment by nandini45** [comment]
@isabelcosta  thank you for answering all my question so i could start somewhere.
and yeah if approved and if we have to make more changes I will be more than willing to make the required changes. Thank you

**Review by foongminwong — APPROVED** [review]
Tested by returning current details of a registered user, and it returns successfully
pr532-test

Good work @nandini45 !!

**Comment by isabelcosta** [comment]
Very cool @foongminwong 👏  ! I like to see your thorough tests :D

**Comment by isabelcosta** [comment]
Your PR was merged! great work @nandini45 🎉

**Pull request merged**
