### PR TITLE
chore : Fix typos in task.py in api app

### LINKED ISSUE #559: API: typo present in task.py
**Describe the bug**

presence of some typos.

**To Reproduce**
1. Go to https://github.com/anitab-org/mentorship-backend/blob/dfecaec198db134bed32b7d3232b9c62791d84c6/app/api/dao/task.py#L28

https://github.com/anitab-org/mentorship-backend/blob/dfecaec198db134bed32b7d3232b9c62791d84c6/app/api/dao/task.py#L95

https://github.com/anitab-org/mentorship-backend/blob/dfecaec198db134bed32b7d3232b9c62791d84c6/app/api/dao/task.py#L129

4. See error [succesful]

**Expected behavior**

It should be `successful`.

**Screenshots**

NA

**Desktop (please complete the following information):**
 
Any

**Smartphone (please complete the following information):**
 Any

**Additional context**
I would like to work on this.

### PR DESCRIPTION
**Pull request by sankha555**
### Description

Fixes typos in spellings in the comments of task.py file 

Fixes #559 

### Type of Change:

- Code

### How Has This Been Tested?

The typos have been verified with correct spellings

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Great work @sankha555 🎉 
thank you for your contribution!

**Comment by sankha555** [comment]
> Great work @sankha555 🎉
> thank you for your contribution!

**Comment by snitin315** [comment]
@sankha555 did you closed it by mistake?

**Comment by sankha555** [comment]
> @sankha555 did you closed it by mistake?

Yes @snitin315 , I closed it by mistake. I am extremely sorry for that. Can you please fix it or guide me as to what should I do? Thanks

**Comment by snitin315** [comment]
> > @sankha555 did you closed it by mistake?
> 
> Yes @snitin315 , I closed it by mistake. I am extremely sorry for that. Can you please fix it or guide me as to what should I do? Thanks

No problem I reopened it.

**Review by snitin315 — APPROVED** [review]
LGTM.
Thank you for your contribution.

**Comment by isabelcosta** [comment]
Thank you for managing this issue/PR contribution sooo well @snitin315 🎉 🤗

**Comment by sankha555** [comment]
Thank you @isabelcosta and @snitin315 for your approvals and reviews. 
I wish to contribute more in the backend of the repository. I am going through the issue tracker and browsing relevant issues. If there are some issues that you think might be relevant for me to work on, I would be obliged if you could please guide me to them. Thanks again :)

**Pull request merged**
