### PR TITLE
docs: manual testing report PUT /user/change_password

### LINKED ISSUE #845: Perform manual testing and report PUT /user/change_password
## Description

As a tester,
I need to test PUT /user/change_password,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#change-password](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#change-password)

### Update [Required]
- [ ] Test PUT /user/change_password API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by ankit-saraf**
### Description

Performed manual testing of PUT user/change_password API and created a user_change_password.md file at /docs/manual_tests

Fixes #845 

### Type of Change:
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

The following tests have been performed with SWAGGER UI at [link](https://mentorship-backend-temp.herokuapp.com/) :
* Change password to a different password from the current one
* Change password to a password equal to the current one
* Change password to an empty password
* Change password to a password with white spaces

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by vj-codes — APPROVED** [review]
@ankit-saraf congrats on your first contribution to the repo 🎉

**Comment by ankit-saraf** [comment]
> @ankit-saraf congrats on your first contribution to the repo

Thank You

**Review by SanketDG — APPROVED** [review]
LGTM!

**Review by isabelcosta — APPROVED** [review]
Great work @ankit-saraf 👏 
Thank you so much for this contribution!

**Comment by isabelcosta** [comment]
cc @rpattath this is a cool example of a Quality assurance contribution

**Comment by ankit-saraf** [comment]
Thank you @isabelcosta. Looking forward to contributing more.

**Pull request merged**
