### PR TITLE
Update README.md

### LINKED ISSUE #782: In the documentation add a section displaying versions of the frameworks and extensions use.
**Description**
In the Readme of the repository, in the documentation section add the versions of the frameworks and extensions used.

**Acceptance Criteria**

- [ ]  Update [Required]

**Definition of Done**

- [ ] All of the required items are completed.

- [ ] Approval by 2 mentors.

**Estimation**
   1 hr

**Note**
This issue will be assigned from September 1, 2020.

### PR DESCRIPTION
**Pull request by bhumikasharma29**
### Description

Mentioned the versions of the framework and flask extensions being used.

Fixes #782 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by yashasvimisra2798 — APPROVED** [review]

**Comment by yashasvimisra2798** [comment]
looks good @bhumikasharma29

**Comment by bhumikasharma29** [comment]
Thank you @yashasvimisra2798 . How will the review be approved?

**Comment by yashasvimisra2798** [comment]
@bhumikasharma29 one more mentor shall approve it. PR will be merged after OSH ends

**Comment by bhumikasharma29** [comment]
Okay ma'am. Do we need to approach a mentor or they will do it on their own?

**Comment by yashasvimisra2798** [comment]
I'll ask them, and you don't need to call me ma'am xD

**Comment by bhumikasharma29** [comment]
Okay :-)

**Comment by devkapilbansal** [comment]
@bhumikasharma29 change your pull request title and commit message to something more descriptive

**Comment by vj-codes** [comment]
@bhumikasharma29 hey please do as suggested above

**Comment by vj-codes** [comment]
Closing due to inactivity 
Thank you for your contribution:)

**Pull request closed without merging**
