### PR TITLE
Fix Swagger UI http response documentation for Task Comment API

### LINKED ISSUE #554: Fix description messages on Mentorship Relation
## Description
As a developer, i need to see the same way for displaying messages on the backend server. so that i can follow the same pattern on the messages im writing. Right now the messages are shown in 2 ways:
image
image

### Update [Required]
Change the messages to either:
a){’message’: 'User is already an Admin.’}
or
b)User is already an Admin.
## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by StergiosSozos**
### Description

The description shows the context of JSON on all Mentorhip Relation APIs. The ones that were changed are:
Creates a new task comment
image
Modifies the task comment
image
Deletes the task comment
image
Lists the task comments
image
 

Fixes #554 

### Type of Change:

- Code
- User Interface

### How Has This Been Tested?

All tests on Travis have passed.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Great great work @StergiosSozos ! I really appreciate your contribution, now the Swagger UI can reflect more accurate documentation about HTTP status codes!
Thank you for your contribution 🎉

**Comment by isabelcosta** [comment]
@StergiosSozos I updated the title of the PR to reflect what was done here, instead of just having the name of the branch :)

**Comment by isabelcosta** [comment]
@anitab-org/qa-team I added the needs testing, this is just for someone to double-check that the Swagger UI works and shows these changes.

**Comment by isabelcosta** [comment]
I just tested this, through running the tests and checking the Swagger UI:

Unit Tests:

image

The left side is this PR Swagger UI, and the right side is the deployed server:

image

**Comment by isabelcosta** [comment]
@anitab-org/coding-team can you please review this simple PR :)

**Review by foongminwong — APPROVED** [review]
Reviewed and tested codes on local machine
**Before pr567**
before_pr567

**After pr567**
after_pr567

**Comment by isabelcosta** [comment]
Thank youuuuuu so much @foongminwong 🙌 really really appreciate all the help you've been giving with mentorship repositories!

**Pull request merged**
