### PR TITLE
docs: show invalid email message for 400 code on Swagger

### LINKED ISSUE #562: 400 Responses does not list "Your email is invalid." message.
When we register a new user, if we entered  an invalid email address then we see the expected error message "Your email is invalid." but this message is not listed under 400 Responses.

1. Go to 'User-Register'
2. {
  "name": "testua",
  "username": "testua",
  "password": "testua123",
  "email": "voxij69223mailop7.com",
  "terms_and_conditions_checked": true,
  "need_mentoring": true,
  "available_to_mentor": true
}
3. Click on 'Execute'
4. Scroll down to 'Response'
Screenshot (4)

**Expected behavior**
All the error messages should be listed under the 400 error messages.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  Chrome

### PR DESCRIPTION
**Pull request by aadityamp01**
### Description

Fixes #562 

### Type of Change:

- Code
- Documentation

**Code/Quality Assurance Only**
- Bugfix (non-breaking change which fixes an issue)

### How Has This Been Tested?

All tests on local machine server have passed

Screenshot (84)
Screenshot (85)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by SanketDG — APPROVED** [review]

**Comment by isabelcosta** [comment]
@aadityamp01 please keep in mind our Contribution Guidelines, which mentioned that we follow this [Commit Message Style Guide](https://github.com/anitab-org/mentorship-backend/wiki/Commit-Message-Style-Guide).

**Review by isabelcosta — APPROVED** [review]
Seems good :)
Thank you for your contribution @aadityamp01 👏

**Comment by isabelcosta** [comment]
@anitab-org/qa-team could you run this code and check if the message is documented?

**Comment by rpattath** [comment]
1. Code review - Not Done
2. All possible responses (positive and negative tests) were tested as below:
  * _Test1 Description_  : email address without @
    _Screenshot/gif_:  
no@

    _Expected Result_:  400 response - "message": "Your email is invalid."
    _Actual Result_: 400 response - "message": "Your email is invalid."
  * _Test2 Description_  : email address without .com
    _Screenshot/gif_:  
nodotcom

    _Expected Result_:  400 response - "message": "Your email is invalid."
    _Actual Result_:  400 response - "message": "Your email is invalid."
    ...  
    
3. Additional testcases covered:
  * _Test1 Description_  : Successful registraion
    _Screenshot/gif_:  
valid

    _Expected Result_:  User is register and login successful
    _Actual Result_: User is register and login successful
    
4. Additional Comments: 
Screenshot from 2020-06-11 17-07-25

5. Status of PR Changed to: Ready to Merge.

**Comment by isabelcosta** [comment]
@rpattath thank you so much for being soo quick to review this! However the test here was just seeing if when you run the project and see Swagger, if this response appears documented under the 400 status code messages area:

image

Did you manage to see that last message?

**Comment by rpattath** [comment]
@isabelcosta sorry I forgot to add that screenshot to each of the test description in the test report. Once I realized my mistake I added that sceenshot to the additional comments. So yes, I was able to see it in each test.

**Comment by isabelcosta** [comment]
Awesome @rpattath 👏 🙌

**Pull request merged**
