### PR TITLE
fix: Optimize query of unverified users in scheduler

### LINKED ISSUE #611: Optimize query of unverified users in scheduler
## Description

The idea is to optimize query of unverified users, so that these are fetched directly from the database instead of fetching all and then filtering with python code.

In this line https://github.com/anitab-org/mentorship-backend/blob/develop/app/schedulers/delete_unverified_users_cron_job.py#L20 you can see the code fetches the all users fro `UserModel` and only then it filters non verified users

### Update [Required]
- [ ] Filter unverified users from `UserModel` instead of from the list of users returned from it.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by PareenKarpe**
### Description

Optimize query of unverified users in scheduler

Fixes #611 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

I created 4 new users and verified only 2 of them. With this corn job, I was able to delete only the unverified users.

### Checklist:
 
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

Code/Quality Assurance Only
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by satya7289 — APPROVED** [review]

**Comment by isabelcosta** [comment]
@PareenKarpe there should be a checklist in your PR description as per the template, can you please add it back? You can find the template under `.github/pull_request_template.md` I think

**Comment by PareenKarpe** [comment]
@isabelcosta Thank you for fixing the title. I have added back the checklist. Please let me know if I am missing anything in it

**Review by isabelcosta — APPROVED** [review]
Looks good @PareenKarpe 🎉
Thank you for your contribution!

**Comment by isabelcosta** [comment]
@PareenKarpe I edited the PR description to have the subtitles format with `###`, and a small description (same as the title of the PR).
It would be great if you could check the boxes in the checklist, corresponding to your changes. You don't need to edit the description, you can simply check the boxes as it is.

@anitab-org/qa-team can you please test this PR? Let us know if you need any clarification here.
I would suggest reducing the corn job time interval to 1 min, and check the users before and after the job runs and deletes the unverified users.

**Comment by foongminwong** [comment]
Probably someone from the @anitab-org/qa-team might know how to test/query for unverified users, but I don't know how to test this hmm... 

I saw there's a python script `test_delete_unverified_users_cron.py` inside the `tests/cron_job_functions/` folder. Do you just run this script and track the performance of the codes? @PareenKarpe @isabelcosta how will you test this?

**Comment by PareenKarpe** [comment]
@foongminwong I tried to test it by running the script `test_delete_unverified_users_cron.py ` locally. I created 4 users and verified only 2 users' email ids. I checked that number of users that are getting deleted is only the one with an unverified email id.

**Comment by foongminwong** [comment]
sounds good @PareenKarpe ! I had some error testing it locally, so @rpattath will be testing it :)

**Comment by rpattath** [comment]
@PareenKarpe @isabelcosta I am seeing the same issue, unable to run the python script.

```
$ python test_delete_unverified_users_cron.py
Traceback (most recent call last):
  File "test_delete_unverified_users_cron.py", line 5, in <module>
    import config
ModuleNotFoundError: No module named 'config'
```
I tried to pip install config and app when I am hitting
```
$ python test_mentorship_completion_cron.py 
Traceback (most recent call last):
  File "test_mentorship_completion_cron.py", line 5, in <module>
    from app.database.models.tasks_list import TasksListModel
ModuleNotFoundError: No module named 'app.database'
```
Are there any requirements to be met before running those scripts?

**Comment by PareenKarpe** [comment]
@rpattath I think it is because of the location of the `test_delete_unverified_users_cron.py`. The `config` file is the header level. So while running locally it will throw an error. For testing purposes, we can change the location of `test_delete_unverified_users_cron.py` to the same level as the `config` file. I think we can bypass the error then. I tried this way through debugging but I am sure there will be some other better way to test. @isabelcosta Any suggestions about testing `test_delete_unverified_users_cron.py` in some other way?

**Comment by isabelcosta** [comment]
@rpattath I think you just needed a little change in your command to indicate you are running a unittest?!
I ran this `python -m unittest tests/cron_job_functions/test_delete_unverified_users_cron.py` from the root folder of the project, using the virtual environment.

Here's the output:
```
~/d/mentorship-backend PareenKarpe-611 > python -m unittest tests/cron_job_functions/test_delete_unverified_users_cron.py
/Users/isabelcosta/dev/mentorship-backend/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py:374: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  args = inspect.formatargspec(*spec)
/Users/isabelcosta/dev/mentorship-backend/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py:384: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  spec[2], None, spec[4])
/Users/isabelcosta/dev/mentorship-backend/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py:405: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  formatvalue=lambda x: '=' + x)
.
----------------------------------------------------------------------
Ran 1 test in 0.509s

OK
```

Screenshot:
image

**Comment by isabelcosta** [comment]
@rpattath let me know how it goes for you running the command I mentioned.
With this, can we consider that this passes our tests?
@foongminwong I am trusting the unit test, since the code change only involved a small optimization.
If this was a total new feature, I would test it by:
1. creating a user, and not verify their email
2. check the user in **this in** the database, using `GET /users`
3. reduce this corn job interval time to 5 sec
4. wait >5 seconds
5. check the user **is not** this in the database, using `GET /users`

cc @PareenKarpe

**Comment by rpattath** [comment]
@PareenKarpe I tried this out based on @isabelcosta's suggestions. I was able to run that script without any error but I see the following when I try to login as a verified user after I ran the script.

```
(venv) [rpattath@rpattath mentorship-backend]$ vim app/schedulers/delete_unverified_users_cron_job.py 
(venv) [rpattath@rpattath mentorship-backend]$ python -m unittest tests/cron_job_functions/test_delete_unverified_users_cron.py
/home/rpattath/mentorship-backend/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:374: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  args = inspect.formatargspec(*spec)
/home/rpattath/mentorship-backend/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:383: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  apply_pos = inspect.formatargspec(spec[0], spec[1],
/home/rpattath/mentorship-backend/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:403: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  apply_kw = inspect.formatargspec(name_args, spec[1], spec[2],
.
----------------------------------------------------------------------
Ran 1 test in 0.332s
```
Screenshot from 2020-06-27 12-59-56
Screenshot from 2020-06-27 13-00-06

**Comment by isabelcosta** [comment]
@rpattath can you show the console log to see the error that appeared, when you got that error?

**Comment by rpattath** [comment]
@isabelcosta https://gist.github.com/rpattath/687460eadb1e36fee464c9f9a17287de

**Comment by PareenKarpe** [comment]
> @PareenKarpe I tried this out based on @isabelcosta's suggestions. I was able to run that script without any error but I see the following when I try to login as a verified user after I ran the script.
> 
> ```
> (venv) [rpattath@rpattath mentorship-backend]$ vim app/schedulers/delete_unverified_users_cron_job.py 
> (venv) [rpattath@rpattath mentorship-backend]$ python -m unittest tests/cron_job_functions/test_delete_unverified_users_cron.py
> /home/rpattath/mentorship-backend/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:374: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
>   args = inspect.formatargspec(*spec)
> /home/rpattath/mentorship-backend/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:383: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
>   apply_pos = inspect.formatargspec(spec[0], spec[1],
> /home/rpattath/mentorship-backend/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:403: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
>   apply_kw = inspect.formatargspec(name_args, spec[1], spec[2],
> .
> ----------------------------------------------------------------------
> Ran 1 test in 0.332s
> ```
> 
> Screenshot from 2020-06-27 12-59-56
> Screenshot from 2020-06-27 13-00-06

@rpattath Is it related to the setting of environment variable values?

**Comment by isabelcosta** [comment]
> https://gist.github.com/rpattath/687460eadb1e36fee464c9f9a17287de

@rpattath I don't see the stack trace the call to `POST /login` which is the one giving the error 🤔 
We can look into this more in my Office Hour, but if you could get me the stack trace that includes the `POST /login` call that would help.

**Comment by rpattath** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Not Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Ran the python script
    _Screenshot/gif_:  In this [comment](https://github.com/anitab-org/mentorship-backend/pull/642#issuecomment-650754141)
    _Expected Result_:  Script ran successfully
    _Actual Result_: Same as above

4. Additional Comments: The issue I was seeing in this [comment](https://github.com/anitab-org/mentorship-backend/pull/642#issuecomment-650754141) was my mistake, I had not started the server. Since the Travis tests have passed I am marking this PR `Ready to Merge`

5. Status of PR Changed to: `Ready to Merge.`

**Pull request merged**
