### PR TITLE
Performed manual testing and report PUT /user API 

### LINKED ISSUE #767: Perform manual testing and report PUT /user API
## Description

As a tester,
I need to test PUT /user API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#update-user](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#update-user)

### Update [Required]
- [ ] Test PUT /user API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by yash2189**
### Description

To test the PUT /user API #767 and create a report regarding the same under /docs/manual_tests

Fixes #767 

### Type of Change:

- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Tested the REST API with Swagger UI provided in the link of the deployed server.
Carried out tests on PUT /user 
Created a markdown file under /docs/manual_tests for reports regarding the tests.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by yash2189** [comment]
@vj-codes @gaurivn can you please review my PR?

**Comment by gaurivn** [comment]
```
It was given to test only /user API but out of curiosity I have tested /user/change_password API as well.
```
@yash2189, I don't think this line is required. Since the issue requires testing only PUT/User you can remove the Change password part that was fixed in #854. @isabelcosta, please confirm if I am right.

**Comment by yash2189** [comment]
@gaurivn I had asked this doubt before on issue #767  but I didn't receive any response. 
Also in issue #845 I had mentioned about this to which @vj-codes told me to change the description and update PR.
`https://github.com/anitab-org/mentorship-backend/issues/845#issuecomment-689323419`

I will do the required changes then till tomorrow morning.

**Comment by yash2189** [comment]
@gaurivn Should I remove the` PUT /user/change_password` part?

**Comment by yash2189** [comment]
@isabelcosta @gaurivn  can you please tell me whether I should remove the `PUT /user/change_password` part ?

**Comment by yash2189** [comment]
@gaurivn please confirm whether I should remove the part for `PUT /user/change_password`

**Comment by gaurivn** [comment]
> @gaurivn please confirm whether I should remove the part for `PUT /user/change_password`

Yes, do remove it, commit only what the issue asked to do and the "curiosity" line is really unnecessary.

**Comment by yash2189** [comment]
@gaurivn yes I'll do that till today evening/night

**Comment by yash2189** [comment]
@gaurivn please review the changes

**Review by gaurivn — CHANGES_REQUESTED** [review]
Good, pls remove the screenshots .png separate ones you added under test screenshots folder, just remove that folder.

**Comment by yash2189** [comment]
@gaurivn I have only added the required screenshots for PUT /user API rest have been removed.

**Comment by yash2189** [comment]
@gaurivn done...please review the same.

**Review by gaurivn — APPROVED** [review]
Good work, thank you :tada:

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: Thanks @yash2189 for your time and contribution

The changes made in this PR were tested locally. Following are the results:

1. Code review - NA

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Tested endpoint by changing the fields
    _Screenshot/gif_:  
success_case

    _Expected Result_:  SUCCESS
    _Actual Result_: SUCCESS
  * _Test2 Description_  Changed Username to already available username
    _Screenshot/gif_:  
failure_case

    _Expected Result_:  FAIL
    _Actual Result_:   FAIL
 
5. Status of PR can be Changed to: Ready to Merge.

**Review by isabelcosta — APPROVED** [review]
thank you for contributing @yash2189 with this piece of documentation 🎉

**Comment by isabelcosta** [comment]
@devkapilbansal thank you so much for testing so many PRs 🤗 🎉 🙌

**Pull request merged**
