### PR TITLE
docs: update environment variable declarations

### LINKED ISSUE #965: docs: Update environment variables declarations in documentation
**Describe the bug**

As a developer,
I would like to be able to install and repository on my local system. Using any development configuration other than "local", requires one to add a few more environment variables. One of them, the declaration of "MOCK_EMAIL" has a slight misprint, due to which newcomers might face problems in settings up the repo. The issue is that there is whitespace between "MOCK_EMAIL" ,  "=" and "True/False" in the documentation, which if included in the cli too, will produce an error. This small misprint can be quickly fixed and might help in saving a bit more debugging time for newcomers.

**To Reproduce**

1. Open up your CLI and ```cd``` into your fork of ```mentorship-backend``` repository 
2. Declare new environment variable as ```MOCK_EMAIL = True``` (please note the spaces in between)
3. Error from bash : ```-bash: export: `=': not a valid identifier```

**Expected behavior**
Removing the spaces from the declarations will resolve the issue and not return any errors, the env variable will be set.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.14.5 Mojave
 - Tested on Terminal

**Additional context**
This issue might seem a bit too trivial to raise, but I thought it might help newcomers in setting up the repo on their system. I will be eager to quickly make a patch for the issue and make the required changes in the docs.

### PR DESCRIPTION
**Pull request by battuAshita**
### Description

Documentation containing misprint at the environment variable declaration has been fixed.

Fixes #965

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by sankha555** [comment]
@battuAshita great that you have used the PR template to raise the PR, but a few changes are required :smile:
> Fixes # [ISSUE]

You need to replace [ISSUE] by the actual issue number here


> * Code
> * Quality Assurance
> * User Interface
> * Outreach
> * Documentation

Please remove those categories under which this PR doesn't fall. Since this is a documentation patch, you can remove all other categories.

Similarly for the other headings, please remove the irrelevant options.

In the checklist, please select those options which are ensured in your PR. To select an option, fill in the box ([ ]) with an 'x'. You can also view the PR description preview before submitting it. Also, please remove those options which are not checked.

Your commit message should also follow the commit guidelines completely. Please include a short patch description in your commit message too.

**Comment by battuAshita** [comment]
> @battuAshita great that you have used the PR template to raise the PR, but a few changes are required 
> 
> > Fixes # [ISSUE]
> 
> You need to replace [ISSUE] by the actual issue number here
> 
> > * Code
> > * Quality Assurance
> > * User Interface
> > * Outreach
> > * Documentation
> 
> Please remove those categories under which this PR doesn't fall. Since this is a documentation patch, you can remove all other categories.
> 
> Similarly for the other headings, please remove the irrelevant options.
> 
> In the checklist, please select those options which are ensured in your PR. To select an option, fill in the box ([ ]) with an 'x'. You can also view the PR description preview before submitting it. Also, please remove those options which are not checked.
> 
> Your commit message should also follow the commit guidelines completely. Please include a short patch description in your commit message too.

Ok @sankha555. Will make these changes.

**Comment by battuAshita** [comment]
> > @battuAshita great that you have used the PR template to raise the PR, but a few changes are required
> > > Fixes # [ISSUE]
> > 
> > 
> > You need to replace [ISSUE] by the actual issue number here
> > > * Code
> > > * Quality Assurance
> > > * User Interface
> > > * Outreach
> > > * Documentation
> > 
> > 
> > Please remove those categories under which this PR doesn't fall. Since this is a documentation patch, you can remove all other categories.
> > Similarly for the other headings, please remove the irrelevant options.
> > In the checklist, please select those options which are ensured in your PR. To select an option, fill in the box ([ ]) with an 'x'. You can also view the PR description preview before submitting it. Also, please remove those options which are not checked.
> > Your commit message should also follow the commit guidelines completely. Please include a short patch description in your commit message too.
> 
> Ok @sankha555. Will make these changes.

Hi @sankha555. I have made the required changes.

**Review by vj-codes — CHANGES_REQUESTED** [review]
@battuAshita congrats on your first PR 🎉 
You will also have to update these changes in environment-variables.md file

**Comment by battuAshita** [comment]
> @battuAshita congrats on your first PR 
> You will also have to update these changes in environment-variables.md file
Thank you @vj-codes. Will update the environment-variables.md file.

**Comment by battuAshita** [comment]
> > @battuAshita congrats on your first PR
> > You will also have to update these changes in environment-variables.md file
> > Thank you @vj-codes. Will update the environment-variables.md file.

@vj-codes I am done updating the environment-variables.md file also.

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1:

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Comment by vj-codes** [comment]
Adding label ready to merge since it's a documentation change

**Review by isabelcosta — APPROVED** [review]
Awesome work! Thank you for this contribution @battuAshita 👏

**Pull request merged**
