### PR TITLE
Create quality assurance test cases md file

### LINKED ISSUE #454: Add Quality Assurance documentation to /docs folder
## Description
As a contributor,
I need a way to contribute to the Quality Assurance table through PRs,
so that I can contribute to this particular documentation.

Quality Assurance table are defined here: https://github.com/anitab-org/mentorship-backend/wiki/Quality-Assurance

### Update [Required]
- [ ] Add Quality Assurance docs to allow contributors to contribute to it, without having to give extra permissions to Wiki

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description

Add Quality Assurance test cases just as is in the Wiki documentation.
By doing this, other contributors will be able to contribute to this documentation 🎉 

Fixes #454 

### Type of Change:

- Documentation

### How Has This Been Tested?

I looked at how it is displayed on GitHub on my forked repository [(link to the file)](https://github.com/isabelcosta/mentorship-backend/blob/454-add-quality-assurance-docs/docs/quality-assurance-test-cases.md). So I see the markdown format works.

It looks the same as the [Wiki documentation](https://github.com/anitab-org/mentorship-backend/wiki/Quality-Assurance).

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by isabelcosta** [comment]
@annabauza @m-murad can approve if you see fit please.

**Comment by isabelcosta** [comment]
Tagged you here @mayburgos , because this is what I mentioned once to you on the Feedback sessions from GCI, where I mentioned we could turn some Wiki docs into docs in the repo, so that contributors could contribute to these docs, such as the Quality Assurance docs

**Review by mayburgos — APPROVED** [review]
Yes! Would love to add QA tasks. :)

**Comment by isabelcosta** [comment]
Thank you @mayburgos 🙏

**Pull request merged**
