### PR TITLE
doc: updated reporting_guidelines 

### LINKED ISSUE #772: Create a reporting_guidelines.md
## Description
As a user, I need to modify the reporting guidelines, so that I can seek for help when necessary.
1. The content should be consistent with [Reporting Guidelines](https://github.com/anitab-org/mentorship-flutter/blob/develop/.github/reporting_guidelines.md)
2. And then update the code of conduct link in **Readme.md**>>Contributing section.
3. Add the updated Reporting Guidelines file to doc folder.

## Acceptance Criteria
- [ ] Update [Required]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

## Note
This issue will be assigned from September 1, 2020.

### PR DESCRIPTION
**Pull request by atharwa-24**
### Description

Updated reporting_guidelines.md file
Updated the code of conduct & reporting guidelines link in Readme.md>>Contributing section.
Added the updated Reporting Guidelines file to doc folder.

Fixes #772 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

### CODE REVIEW

**Comment by atharwa-24** [comment]
@sanchibansal340 can you plz review it once.

**Comment by sanchibansal340** [comment]
Will do. Thanks @atharwa-24

**Comment by sanchibansal340** [comment]
@atharwa-24 Please check your commit again, the build failed

**Comment by atharwa-24** [comment]
> @atharwa-24 Please check your commit again, the build failed
> 

Haven't made any code changes 
Dont know why the build is failing

**Comment by sanchibansal340** [comment]
@atharwa-24 check your first 2 commits.

**Comment by atharwa-24** [comment]
> 
> 
> @atharwa-24 check your first 2 commits.

can you plz comment on the lines, i would fix it 
I haven't found any build error,
its the code coverage report which is throwing error:
Merging changes into develop will decrease coverage by 0.00%.

**Comment by vj-codes** [comment]
@atharwa-24 no need to worry the build task and tests are successful , only codecov report was not generated

**Review by vj-codes — DISMISSED** [review]
LGTM 🎉

**Review by gaurivn — DISMISSED** [review]
Good, please squash the commits

**Comment by atharwa-24** [comment]
> 
> 
> Good, please squash the commits

Done!! @gaurivn

**Comment by atharwa-24** [comment]
@gaurivn @vj-codes

**Review by vj-codes — APPROVED** [review]
@atharwa-24 Thank you for your contribution 🎉 
LGTM !

**Comment by vj-codes** [comment]
@devkapilbansal hey can review this ?

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: Thanks @atharwa-24 for this

Pinging @sanchibansal340 for review

**Comment by devkapilbansal** [comment]
After one more approved review, this PR can be labelled as `Ready to Merge` as this doesn't needs testing

**Comment by vj-codes** [comment]
@isabelcosta hey this PR is good to merge :)

**Review by isabelcosta — APPROVED** [review]
Good work @atharwa-24 👏 
Thank you for your contribution!

**Pull request merged**
