### PR TITLE
fix: add values to error message in get_env_config fuc

### LINKED ISSUE #533: Add misplaced values to error message
**Describe the bug**
If I put values other than "prod", "test", "dev", "local", and "stag" in the FLASK_ENVIRONMENT_CONFIG environment variable, the error message excluding local and stag are printed.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by sihhub**
### Description
i added values local, stag to error message of get_env_config fuc  in config.py

Fixes #533

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
I checked that an error message containing local and stag was printed.

### Checklist:
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by isabelcosta** [comment]
@hongsungin92 this issue is not assigned yet, please wait for assignment before sending the PR. I can re open this once you are assigned

**Comment by sihhub** [comment]
hello @isabelcosta  I see. It's my first time. I didn't know.

**Comment by isabelcosta** [comment]
no problem at all! We have a CONTRIBUTING.md, which is maybe not clear enough about this specific guideline of waiting for approval, but it is there. This is a very nice catch, this is just so you can understand our workflow. Now that I assigned this to you I can reopen and evaluate your issue.

**Comment by isabelcosta** [comment]
Also, so that the PR is linked to the issue, could you fix your description to have: `Fixes #533` instead of `Fixes # [533]`, in this way GitHub will see that this PR should close the issue once it's merged.
It's okay that you did this little mistake because I think the PR template is not clear enough about this. I will fix that soon @hongsungin92

**Review by isabelcosta — APPROVED** [review]
Great catch @hongsungin92 🎉 
Thank you so much for your contribution and following our Commit Message Style Guide 👏

**Comment by sihhub** [comment]
> Also, so that the PR is linked to the issue, could you fix your description to have: Fixes #533 instead of Fixes # [533], in this way GitHub will see that this PR should close the issue once it's merged.
> It's okay that you did this little mistake because I think the PR template is not clear enough about this. I will fix that soon @hongsungin92

 @isabelcosta  Oh, I see. Then do I not need to revise this PR again now?

**Comment by isabelcosta** [comment]
@hongsungin92 no need to do anything now, as per my review. your commit follows guidelines and the code is only about the issue you reported :) So its great, I just need another approval to be able to merge this into the `develop` branch :)

**Comment by isabelcosta** [comment]
@hongsungin92 I just needed you to edit the PR description for cross-reference of the PR with Issue. Now you will see that the issue has the link to the PR.

**Comment by sihhub** [comment]
Okay. Thank you @isabelcosta

**Review by foongminwong — APPROVED** [review]
Good work @hongsungin92 !

**Pull request merged**
