### PR TITLE
Style: Change to f-strings (fix#741)

### LINKED ISSUE #714: Add badge with Python 3.6 version on README
## Description

Add badge with Python 3.6 version in the README

### Update [Required]
- [ ] Add badge with Python 3.6 version in the README

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

### LINKED ISSUE #741: Use f-strings on Admin Resources file
## Description
As a developer,
I need change strings interpolation in Admin Resources file,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `app/api/resources/admin.py` file.

## Mocks

As an example, here:

https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/app/api/resources/admin.py#L16

We can use f-strings such as:

```
@admin_ns.response(HTTPStatus.FORBIDDEN, f"{messages.USER_IS_NOW_AN_ADMIN})
```

### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for `app/api/resources/admin.py` file

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by LivesInRoom29**
### Description

Fixes #741 

To start, the file <code>app/api/resources/admin.py</code> contained %-formatted strings for the descriptions of the code responses, for example:

```python
@admin_ns.route("admin/new")
@admin_ns.response(HTTPStatus.FORBIDDEN, "%s" % messages.USER_IS_NOW_AN_ADMIN)
@admin_ns.response(HTTPStatus.BAD_REQUEST, "%s" % messages.USER_IS_ALREADY_AN_ADMIN)
@admin_ns.response(
    HTTPStatus.UNAUTHORIZED,
    "%s\n%s\n%s"
    % (
        messages.TOKEN_HAS_EXPIRED,
        messages.TOKEN_IS_INVALID,
        messages.AUTHORISATION_TOKEN_IS_MISSING,
    ),
)
```

Any instance of this was changed to use f-strings, as described in the [Coding Standards](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/coding_standards.md).

For example:

```python
@admin_ns.route("admin/new")
@admin_ns.response(HTTPStatus.FORBIDDEN, f"{messages.USER_IS_NOW_AN_ADMIN}")
@admin_ns.response(HTTPStatus.BAD_REQUEST, f"{messages.USER_IS_ALREADY_AN_ADMIN}")
@admin_ns.response(
    HTTPStatus.UNAUTHORIZED,
    f"{messages.TOKEN_HAS_EXPIRED}\n{messages.TOKEN_IS_INVALID}\n{messages.AUTHORISATION_TOKEN_IS_MISSING}"
)
@admin_ns.response(HTTPStatus.FORBIDDEN, f"{messages.USER_ASSIGN_NOT_ADMIN}")
@admin_ns.response(HTTPStatus.NOT_FOUND, f"{messages.USER_DOES_NOT_EXIST}")
```

### Type of Change:

- Style (formatting)

### How Has This Been Tested?

I had the program open in my browser and kept checking to make sure that there were no errors on the page or in the terminal.

### Checklist:

- [x ] My PR follows the style guidelines of this project
- [x ] I have performed a self-review of my own code or materials

### CODE REVIEW

**Review by SanketDG — APPROVED** [review]
Looks good to me code wise!

**Review by isabelcosta — APPROVED** [review]
@LivesInRoom29 great work! Thank you for your contribution!

**Comment by LivesInRoom29** [comment]
Thank you @isabelcosta! It was fun - thanks for the opportunity to get my feet wet with an easy one :)

**Comment by isabelcosta** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Used deployed version to see response listed on Swagger UI_  
    _Screenshot/gif_:  
image

    _Expected Result_:  Message to appear as it does originally in the `develop` branch version
    _Actual Result_: Message from this branch appears just like the `develop` branch version
    
4. Additional Comments: This is just a style change, since the app and tests run, I could already assume that this was fine.

5. Status of PR Changed to: Ready to Merge.

**Comment by isabelcosta** [comment]
@LivesInRoom29 your PR was merged 👏 💪

**Pull request merged**
