### PR TITLE
Add tests for Revoking admin role API #142

### PR DESCRIPTION
**Pull request by hereisamara**
### Description

Created `tests/admin/test_api_revoking_admin_role.py` and added the following tests:
    - Revoking a user which is an admin, when the current user is an admin -> should receive a success message, and remove the admin status from the revoked user
    -   Revoking a user which is not an admin -> should receive a message indicating the user is not an admin
    -   Revoking a user as an admin, when the current user is not an admin -> should receive an error message
    -   Revoking a non-existent user -> should receive error message
    -   Revoke self the admin role, should only work if the user is not the only user
    -   Try using the API without sending authentication token -> should receive an error message

Tests #142

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

`python -m unittest tests/admin/test_api_revoking_admin_role.py`

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by epicadk — DISMISSED** [review]
👍🏼

**Review by isabelcosta — COMMENTED** [review]
Nice work @hereisamara 👏🏾  thank you for this!

Can you please merge these into https://github.com/anitab-org/mentorship-backend/blob/develop/tests/admin/test_api_remove_admin_user.py. If you want to merge the previous into this one is also fine. I'm just wondering about avoiding duplicate tests :)

**Comment by hereisamara** [comment]
Thank you for your time. 

I have viewed the one you mentioned. My test file already contained the tests that are in that one. My test file has all tests that you have asked for in the description.

It says some checks were not successful under `Lint Code and Run Tests / lint (pull_request)` . What should I do? 

image

**Comment by vj-codes** [comment]
@hereisamara hey install black locally and run it to the project, once done push the formatted code for the check to pass

**Comment by hereisamara** [comment]
Thank you @vj-codes. 
I was stuck.

**Comment by vj-codes** [comment]
> Thank you @vj-codes. I was stuck.

All checks passed! ✔️ 💯

**Review by isabelcosta — APPROVED** [review]
Great work @hereisamara 👏🏾 
So glad you got the help you needed and managed to finish this 👏🏾 💯

**Comment by hereisamara** [comment]
Thank you everyone. This is my first time contributing to a project on GitHub.

**Review by vj-codes — APPROVED** [review]
@hereisamara LGTM 🎉 
Thank you for your contribution :)

**Comment by isabelcosta** [comment]
> Thank you everyone. This is my first time contributing to a project on GitHub.

Makes me soo happy!
@vj-codes I will merge since these are tests already tested with actions run of the tests.

**Pull request merged**
