### PR TITLE
Fix: Use Real number values of statuscode instead of enum expressions in Swagger

### LINKED ISSUE #939: Bug:Use HTTPStatus code values instead  of enum representation, in mentorship_relation API in Swagger UI
**Describe the bug**

The values shown on Swagger UI of mentorship_relation API should be in number format instead of Enum Representations of Status Codes. For example 200 instead of HTTPStatus.OK. 

**To Reproduce**

1. Go to https://mentorship-backend-temp.herokuapp.com/
2. Scroll down to ```mentorship_relation```
3. See enum representation.
4. 
image

**Expected behavior**
Use of Values of Status Codes instead of Enum Representations in Swagger UI

**Desktop (please complete the following information):**
 - OS: Ubuntu 20+
 - Browser FireFox Web Browser
 - Version --

### PR DESCRIPTION
**Pull request by Aaishpra**
### Description
The values of  HTTPStatus codes shown on Swagger UI of mentorship_relation API changed to be in number format instead of Enum Representations. 

Fixes #939

Closed PR #942 
### Type of Change:

- Code

- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Go to ``` mentorship_relation```
Click on ```Post/mentorship_relation/send_request```(or any other task)
See Results

image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Aaishpra** [comment]
@isabelcosta @devkapilbansal I messed up a little bit in my earlier PR so, opened this one. Please review here.

**Comment by isabelcosta** [comment]
@Aaishpra for future references and tracking history, could you link the PR you closed in your PR description please? So I can check it out and see if I did previous reviews there.

**Review by isabelcosta — DISMISSED** [review]
Great work @Aaishpra 👏 
Thank you for your contribution! 🎉

**Comment by Aaishpra** [comment]
> @Aaishpra for future references and tracking history, could you link the PR you closed in your PR description please? So I can check it out and see if I did previous reviews there.

Done @isabelcosta and thanks for the quick review.

**Comment by Aaishpra** [comment]
@isabelcosta can you review again.
I removed the merge conflicts

**Review by vj-codes — APPROVED** [review]
Congrats on your first contribution @Aaishpra 
LGTM 🎉

**Review by isabelcosta — APPROVED** [review]
Great work @Aaishpra !

I just tested and it looks awesome!

**Comment by isabelcosta** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Open Swagger and see HTTP status values being rendered_  
    _Screenshot/gif_:  

image

    _Expected Result_:  See HTTP status values on "code" column, instead of HTTPStatus enum string representation
    _Actual Result_: All Mentorship Relation endpoints show the http statue values instead of enum name like "HTTPStatus.OK" on it
    
4. Additional Comments: I tested this on https://ms-backend-review-pr-983.herokuapp.com/

5. Status of PR Changed to: Ready to Merge.

**Pull request merged**
