### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dipanshug124**
### Description

Run tests link under Table to tests was showing error 404.

Fixes #853

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by isabelcosta** [comment]
@dipanshug124 This is a very nice catch. Have you linked to the right issue? Is there an issue created to fix this? This is part of our Contribution Guidelines, that is why I am asking

**Comment by dipanshug124** [comment]
@isabelcosta Pardon me, this was my first time doing any contribution. Could you help me with linking this with particular issue, and is it necessary to always link PR with an issue?

**Comment by isabelcosta** [comment]
> @isabelcosta Pardon me, this was my first time doing any contribution. Could you help me with linking this with particular issue, and is it necessary to always link PR with an issue?

@dipanshug124 no need to apologize :) According to our community guidelines you need to get an issue approved by maintainers, assigned to you and then you can send a PR for it. This is so maintainers can manage better the work being done and also assign people contributing to issues. Here's the [contribution guidelines](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/CONTRIBUTING.md).

So if there is no issue, can you please create it and explain what is the change you are proposing so it gets approved first? I know it is a very easy fix, but we expect contributors to follow these guidelines to keep consistency.

**Comment by vj-codes** [comment]
@isabelcosta hey there is already an issue #784  regarding this for OSH and a PR #800 is opened for the same by the another contributor assigned to it

**Comment by vj-codes** [comment]
@dipanshug124  first you have to create a new issue or comment on any available issues to claim/ get that particular issue assigned to you . Once the issue is assigned , you can create a new branch , commit changes and create a PR for the same.

Please have a look at other available issues [here](https://github.com/anitab-org/mentorship-backend/issues?q=is%3Aopen+is%3Aissue+label%3A%22Status%3A+Available%22+no%3Aassignee) .Thanks!
I will be closing this PR now

**Pull request closed without merging**
