### PR TITLE
Remove cffi dependencies

### LINKED ISSUE #578: Remove cffi from dependencies
**Describe the bug**

When installing dependencies `pip install -r requirements.txt`, it fails on Python 3.8.2

**To Reproduce**

- Try to setup the project on Python version 3.8.2
- `pip install -r requirements.txt` fails on installing `cffi`

**Expected fix**
Remove cffi from dependencies and make sure our tests work.

**Additional context**
https://bitbucket.org/cffi/cffi/issues/403/build-fails-on-38-dev-pyinterpreterstate

### PR DESCRIPTION
**Pull request by nickinack**
### Description

Removed CFFI dependency

Fixes #578

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

-  run python unittest - result: all unittest passed

### Checklist:

- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by nickinack** [comment]
@isabelcosta @SanketDG can you please CR?!

**Review by SanketDG — APPROVED** [review]
The point of this PR should also (by extension) be to make sure that the project works with Python 3.8, could you check for that too? I see you have already fixed one newcomer issue, so this shouldn't be too hard for you :slightly_smiling_face:

**Review by isabelcosta — APPROVED** [review]
Looks good @nickinack :) 
Can you please do what @SanketDG suggested? You can create a virtual environment with python 3.8 and see if the app works.

**Comment by nickinack** [comment]
@isabelcosta @SanketDG  I have Python 3.8 in my Ubuntu and I ran the tests on my local system and it passed.

**Comment by SanketDG** [comment]
@nickinack Can you then update the README accordingly here https://github.com/anitab-org/mentorship-backend#run-app?

> The project runs on Python 3.

This can be changed to:

> This project runs on Python 3.6, 3.7 and 3.8

**Comment by isabelcosta** [comment]
@nickinack could you please follow @SanketDG suggestion?

**Comment by nickinack** [comment]
@isabelcosta sure, I'll do it by the end of the day? Should I squash the commits or open a new PR?!

**Comment by SanketDG** [comment]
> could you please follow @SanketDG suggestion?

@isabelcosta Apologies about not converting this to a "requested changes" comment, got pretty late yesterday

sure, I'll do it by the end of the day? Should I squash the commits or open a new PR?!

@nickinack Feel free to squash the commits!

**Comment by nickinack** [comment]
@isabelcosta @SanketDG I was trying to set the app up in python and I got an error related to a cffi dependency. Can you please guide me?

The error is as follows:

```bash
 Command errored out with exit status 1: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m9/y3_lstms7hl64944cck2kr2h0000gn/T/pip-install-0zuuy1et/cffi/setup.py'"'"'; __file__='"'"'/private/var/folders/m9/y3_lstms7hl64944cck2kr2h0000gn/T/pip-install-0zuuy1et/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m9/y3_lstms7hl64944cck2kr2h0000gn/T/pip-record-p86zxxgu/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/cffi Check the logs for full command output.
```

**Comment by SanketDG** [comment]
@nickinack What command is this?

**Comment by nickinack** [comment]
@SanketDG This was when I was trying to install the dependencies using pip3

**Comment by SanketDG** [comment]
I have no idea why this would happen, could you post the full log?

**Comment by PrashanthPuneriya** [comment]
> @isabelcosta @SanketDG I was trying to set the app up in python and I got an error related to a cffi dependency. Can you please guide me?
> 
> The error is as follows:
> 
> ```shell
>  Command errored out with exit status 1: /usr/local/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m9/y3_lstms7hl64944cck2kr2h0000gn/T/pip-install-0zuuy1et/cffi/setup.py'"'"'; __file__='"'"'/private/var/folders/m9/y3_lstms7hl64944cck2kr2h0000gn/T/pip-install-0zuuy1et/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m9/y3_lstms7hl64944cck2kr2h0000gn/T/pip-record-p86zxxgu/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/cffi Check the logs for full command output.
> ```

I think you are not running the command after activating the virtual environment. See this `/usr/local/opt/python@3.8/bin/python3.8`. It is not accessing the virtual env python. It must access `/venv/..../python`.

**Review by PrashanthPuneriya — APPROVED** [review]
Removing `cffi` fixes few errors. For instance it fixes #212 issue. I have tested this locally and it works fine. Infact, we also need to upgrade `werkzeug` to fix few more errors as I mentioned in [this](https://github.com/anitab-org/mentorship-backend/issues/664#issuecomment-658105326) comment.

**Comment by PrashanthPuneriya** [comment]
> @SanketDG This was when I was trying to install the dependencies using pip3

You were trying to install the dependencies without actually activating the environment. This is evident from `Command errored out with exit status 1: /usr/local/opt/python@3.8/bin/python3.8`. It is accessing `/usr/.../python` instead of `/.../venv/.../python`

**Comment by PrashanthPuneriya** [comment]
Can we merge this issue @SanketDG @isabelcosta ? Many of them are facing issues because of this dependency while setting up the project.

**Review by SanketDG — APPROVED** [review]
Let's merge this!

**Comment by PrashanthPuneriya** [comment]
Also, why is the following img showing that 1 has approved even though we all 3 have approved this? @SanketDG 
image

**Comment by SanketDG** [comment]
Because it only shows approvals from people with write access

**Comment by isabelcosta** [comment]
@PrashanthPuneriya, when you see the 1 approval is usually me as maintainer. I always look to the ✔️ on the PR from each reviewer. I care about having at least 2 approvals from other contributors (me included if possible)

**Comment by GuruCharan-13** [comment]
I would like to work on this issue
please assign it to me
thank you

**Pull request merged**
