### PR TITLE
chore: add heroku deploy needs

### LINKED ISSUE #501: Add necessary files to allow deployment on Heroku?
## Description
As a developer,
I need a couple of configurations,
so that I can deploy the app to Heroku.

I want to empower anyone who wished to deploy the project on heroku to do so. To do this I needed 2 files to be added, here are the [2 latest commits I did in my repository](https://github.com/isabelcosta/mentorship-backend/commits/heroku) `heroku` branch.

I am in doubt if this is something that is done on backend projects in open source, so if anyone could give your opinion on this, I would highly appreciate!

### Update [Required]
- [ ] Add support to deploy on Heroku

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description

I added the necessary files to deploy this on Heroku without any other configuration.
I had to do these changes to deploy the server there https://mentorship-backend-temp.herokuapp.com/

With this change, it will be easier to set up the deploy previews. You can read more here: [Review Apps (New)](https://devcenter.heroku.com/articles/github-integration-review-apps)
Also relevant for this issue https://github.com/anitab-org/open-source-teams/issues/7

Fixes #501 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?

In progress, but basically what I will do is deploy on Heroku directly from this branch.
So I will do this on https://heroku.com/

I connected my forked repository: https://github.com/isabelcosta/mentorship-backend.

I configured the environment variables using in the platform:

image

I deployed the server with this branch code:

image

I setup like in 5 min the server all through the Heroku user interface and this is the deployed server as a result of this: https://mentorship-backend-test-501.herokuapp.com/

App config is this one:

image

I tested the Login API with user Catalina, and it worked fine:

image

Note: I changed this user credentials, so to test, you have to user another user that you have in the dev server.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [x] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by mtreacy002** [comment]
Just wanna share some thoughts. @isabelcosta , @mayburgos , @m-murad,  @rpattath, @annabauza 

For AnitaB to deploy the PR branch to Heroku from AnitaB repo (not contributors repo), we must create a separate branch before `develop` branch for the PR to be reviewed on its deployed Heroku `review server`. Once the change is confirmed that it doesn't break the app, we can merge it to the `develop` branch. 
I'd like to suggest the following structure to help our app ready for production:

Screen Shot 2020-06-11 at 11 13 17 am

We can decide whether we want to have a **single `Review` branch** or **multiple Review branches** as shown in the example given on heroku `Review Apps` pipeline.

Screen Shot 2020-06-11 at 11 10 13 am

**Comment by mtreacy002** [comment]
The suggested structure above will help makes testing easier for @anitab-org/qa-team because it'll remove the need for pulling contributor's PR branch and running server locally for anyone who wanna test the PR. It also saves time in the case of there's new dependency needs to be installed from code changes - tester no longer need to do this if it's available on Heroku Review server.

**Comment by mtreacy002** [comment]
PS: it might also best to add one more stage between the `Development` and `Production` stages, which is **`Beta`** stage, just to do final check before releasing the app to public 😉 

Screen Shot 2020-06-11 at 11 49 38 am

**Comment by rpattath** [comment]
@mtreacy002 @isabelcosta this is amazing. I may not be the best person to review the technical side of this PR but @mtreacy002 that diagram makes things very clear. One question I have can be seen in the image attached.
84336006-a902b000-abd9-11ea-8751-1258d9646c18

**Comment by isabelcosta** [comment]
> PS: it might also best to add one more stage between the `Development` and `Production` stages, which is **`Beta`** stage, just to do final check before releasing the app to public 😉
> 
> Screen Shot 2020-06-11 at 11 49 38 am

@mtreacy002 thank you for providing your insights 👏 This sounds good and in companies, I have been at, there is always an extra environment besides `production` and `development`, so that seems to make sense. However, I don't completely understand the need for the extra environment since we only merge into `development` environment what code we test and "are sure" it's working. In one of my previous companies, the `beta` environment was meant to have the exact same infrastructure as the `production` environment, while with different data (as far as I remember).

What do you suggest would be the use of the `beta` environment?
Could you define clear objectives/reasons for each environment, to justify this extra one?

A nice to know, is that the production server might be defined on AWS instead of Heroku.

cc @rpattath @m-murad @ramitsawhney27 @mayburgos

**Comment by isabelcosta** [comment]
@mtreacy002 regarding Review Apps feature from Heroku, I tried that out on my fork, and the impression I had is that it can work on any PR even if coming from an external contributor branch.

My experiment here: https://github.com/anitab-org/open-source-teams/issues/7#issuecomment-641579659 only uses my PR made to another branch of my own fork.

If my impression is correct - review apps being possible from an external contributor's branch - then why would we need `review` branch? Also, how would it work? How would we coordinate the merges of different PRs to that branch? We want to test a PR isolated from other PRs right?

**Comment by m-murad** [comment]
LGTM 🎉 

@mtreacy002 
I guess the stage you want to add should be called `Staging`  cc @isabelcosta

**Comment by isabelcosta** [comment]
@m-murad could you add a review as approval, so it does not show up as review requested :P

**Review by m-murad — APPROVED** [review]

**Comment by mtreacy002** [comment]
@isabelcosta. That's great then, if it can take contributor's branch. We definitely won't need the `review` branch if that's the case 😊

**Comment by mtreacy002** [comment]
> @mtreacy002 @isabelcosta this is amazing. I may not be the best person to review the technical side of this PR but @mtreacy002 that diagram makes things very clear. One question I have can be seen in the image attached.
> 84336006-a902b000-abd9-11ea-8751-1258d9646c18

@rpattath . That's correct. But as @isabelcosta suggested [here](https://github.com/anitab-org/mentorship-backend/pull/640#issuecomment-642885943), it will now coming after PR been approve immediately on the contributor's branch, coz we won't need `review` branch anymore 😄

**Comment by mayburgos** [comment]
Isabel reviewed this PR with Admins, we've reviewed and approved during our meeting.

**Pull request merged**
