### PR TITLE
docs: Fix typos in docs files.

### LINKED ISSUE #522: docs: Typos in documentations
**Describe the bug**
There are a few typos in `docs/environment-variables.md` and `docs/quality-assurance-test-cases.md`.

Details can be found in:
https://github.com/anitab-org/mentorship-backend/pull/521

**To Reproduce**
Not Applicable

**Expected behavior**
Not Applicable

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**
Not Applicable

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
Not Applicable

### PR DESCRIPTION
**Pull request by hk-mp5a3**
### Description
Fix typos in documentation files such as `docs/environment-variables.md` and `docs/quality-assurance-test-cases.md`.

Fixes #522 

### Type of Change:
- Documentation

**Code/Quality Assurance Only**
Not Applicable

### How Has This Been Tested?
There is no code change. No test needed.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
Not Applicable

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Good work @yzhu01 👏 
Thank you for your contribution :)

**Review by foongminwong — APPROVED** [review]
Nice work and keep going @yzhu01 !

**Comment by isabelcosta** [comment]
@yzhu01 for future reference, I changed in the description of the PR, when you put the issue you fix, one cool thing is that GitHub recognizes this `Fixes #522` and puts the link automatically, so you don't need to do the markdown of a link. And if you leave it as `Fixes #522` GitHub will automatically close the issue you were trying to work on :)

**Comment by hk-mp5a3** [comment]
@isabelcosta Thank you, Isabel, for pointing out this to me!

**Pull request merged**
