### PR TITLE
Update README.md

### LINKED ISSUE #1100: Readme.md update
### Describe the bug
Making Meaningful sentence

### PR DESCRIPTION
**Pull request by keshavgbpecdelhi**
### Description

Fixes #1100 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by devkapilbansal** [comment]
@isabelcosta Although the change looks good, there is no issue for this.

**Comment by vj-codes** [comment]
@keshavgbpecdelhi hey the org has a specific workflow for contributors to follow  here on Github
Can you please create an issue regarding this change and comment to claim it, once it's assigned to you this PR can be reviewed .
Until then I'll put this on hold, if you have any questions about this do ask here :)

**Comment by devkapilbansal** [comment]
This PR deals with a single word change and I don't think that issue opening is required for this. Will ask @isabelcosta to mention this in `Issue LifeCycle` too

**Review by epicadk — APPROVED** [review]

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1:

**Comment by devkapilbansal** [comment]
Adding `Ready to Merge` since it is a documentation change

**Review by isabelcosta — APPROVED** [review]
Great! Thank you for contributing @keshavgbpecdelhi

**Pull request merged**
