### PR TITLE
feat: Add to List Users API the ability to filter users by location

### LINKED ISSUE #760: Add to List Users API the ability to filter users by location
## Description
As a member of the app,
I need be able to filter other members by their location,
so that I can choose the member I want to create a mentorship relation with.

APIs used to fetch Users, don't have an option to filter users by `location` attribute.

#### Note: This issue is labeled for Open Source Hack.
I can assign this issue to you on September 1st as the official opening date for Open Source Hack. Please free to check out other issues in the meantime. Program website: https://anitab-org.github.io/events/open-source-hack/

### Update [Required]
- [ ] Add a query parameter support to `GET /users` and `GET /users/verified`, to filter users by `location` attribute.
- [ ] Update Swagger UI documentation for this API.
- [ ] Write at least one test to prove your new feature is working.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[4] hours

### PR DESCRIPTION
**Pull request by ashokrayal**
### Description

Fixes #760 Add to List Users API the ability to filter users by location

### Type of Change:

- Code

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

I have updated location for few users then I tried to search from /users and /users/verified endpoints and It was giving expected results.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ashokrayal** [comment]
Hi @paritoshsinghrahar,

Can you please review my PR?

Thanks

**Comment by paritoshsinghrahar** [comment]
> Hi @paritoshsinghrahar,
> 
> Can you please review my PR?
> 
> Thanks

Sure. I'll get back to you.

**Comment by paritoshsinghrahar** [comment]
@Ashokrayal On an initial review looks good. Great Effort, though.

**Comment by ashokrayal** [comment]
Hi @paritoshsinghrahar  @isabelcosta, @vj-codes,
Can someone review this PR?

**Review by paritoshsinghrahar — DISMISSED** [review]
Reviewed it again. Seems legit and great. LGTM!! 
@isabelcosta, please review.

**Review by SanketDG — DISMISSED** [review]

**Comment by SanketDG** [comment]
@isabelcosta This looks good,

But before merging any of the filter PRs, I'd be willing to have a discussion on what the best approach is to implement this or refactor this later. Currently, the function and the parameters suffers from all kinds of code smell, so I am open to all kinds of ideas on how to implement filtering in a clean way.

**Comment by rpattath** [comment]
@isabelcosta @SanketDG does this PR need further discussion before being tested and merged?

**Comment by isabelcosta** [comment]
@SanketDG I agree with you. Will wait for the test and then merge.
But as part of this, can you create an issue for creating a cleaner way for filtering data? If not, I can, just let me know :)
Thank you so much for bringing this up!

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@Ashokrayal can you please solve the merge conflicts

**Comment by ashokrayal** [comment]
I will surely do it today

**Comment by SanketDG** [comment]
Here are some basic ideas to abstract away filtering into a common piece of code (so that it doesn't end up having 20 arguments in the function signature)

- Use `**kwargs` as a container for all filter operations.
- Loop through kwargs and check which "keys" are fields of `UserModel`.
- Do the standard filter query using these key value pairs from `**kwargs`

**Comment by vj-codes** [comment]
Putting on hold as the best approach is not decided yet

**Comment by isabelcosta** [comment]
@vj-codes could you create, in case it does not exist yet, an issue to implement filtering in a generic way.

**Review by vj-codes — COMMENTED** [review]
Closing due to inactivity, thank you for your contribution!
Follow up issue will be made.

**Pull request closed without merging**
