### PR TITLE
Added some type hints

### LINKED ISSUE #331: Type hints
**Is your feature request related to a problem? Please describe.**
Since Python 3.5 there's a very nice facilitation, so to say, that's really underused and underestimated in my opinion. This feature is called *type hints* and they are described in [PEP 484](https://www.python.org/dev/peps/pep-0484/).

### What are type hints?
Type hints are small thingies that are appended after declaring variable name and...they hint the type of the variable. Examples:
`age: int = 42`
`username: str = "iwonttellmyname"`
`relations: List[MentorshipRelationModel] = dao.list_relations()`

Their usage is totally optional, they don't have *any* impact on program flow during runtime. However, they're really helpful in the development phase. IDEs like PyCharm support type hints and notify developers when types don't match. It really improves the coding experience.

It's also noteworthy that type hints don't interfere with dynamic nature of Python. One can write
`age: int = "nope"` and the program will run the same as it would without the type hint.

**Describe the solution you'd like**
I'd like to add type hints wherever possible to our codebase. It will greatly improve quality of life

**Describe alternatives you've considered**
We can just continue to develop this project without type hints. Nothing really bad will happen.

### PR DESCRIPTION
**Pull request by bartekpacia**
### Description
I added type hints to (files listed in commit message). I have a few questions though:
- do we want type hints on every single method? Like, make it required?
- if method returns `None`, should it also be typehinted?

Also, I'm not sure how should I typehint objects returned by [TasksListModel.find_by_id()](https://github.com/systers/mentorship-backend/blob/develop/app/database/models/tasks_list.py#L109-L110).

When a mentors accepts proposed changes and answers questions listed above, I'll be very happy to typehint whole codebase :)

Fixes #331  (as of now, partly)

### Type of Change:
- Code
- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors))

### How Has This Been Tested?
Type hints don't have runtime impact, but just to make sure I run all the tests. And CI is passing, too.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bartekpacia** [comment]
@isabelcosta Could I get some feedback and answer to my questions? I'd really like to add those type hints :D

**Comment by isabelcosta** [comment]
> @isabelcosta Could I get some feedback and answer to my questions? I'd really like to add those type hints :D

You can submit the PR with that :) I haven't received any response either, and couldn't bring this to a Community Open Session either. Once I get the chance I'll ask about the community standards, where they stand.

**Comment by bartekpacia** [comment]
That's great! Thanks for a fast response :)

**Comment by isabelcosta** [comment]
@bartekpacia as I am catching up on PRs, I noticed this very important issue. I got [more informed about this Python feature](https://www.python.org/dev/peps/pep-0484/) that I was not aware of and think it would be a great addition to the project.

Since this has so many merge conflicts, would you like to fix them or leave this issue for other contributors? I was thinking of creating sub-issues per file or per feature or per domain, to make this change into type hints easier to manage and review.

What do you think? I am totally fine if you choose not to continue with this and then I'll create smaller issue to make this transition.

**Comment by bartekpacia** [comment]
@isabelcosta I'll try to fix the conflicts in this PR. You can then open some issues requesting to add type hints to the rest of the project.

**Comment by isabelcosta** [comment]
Oki! Sounds good @bartekpacia , let me know once you fix it so I can review this :) And then I'll create type hint  issues for what is missing.

**Comment by bartekpacia** [comment]
@isabelcosta Resolved conflicts :)

**Comment by isabelcosta** [comment]
thank you so much @bartekpacia

**Review by ramitsawhney27 — APPROVED** [review]
Very nice, thank you for this, learned something new here!

**Review by isabelcosta — APPROVED** [review]
Looks good :) Thank you so much for proposing this enhancement in the app and implementing part of it here in the PR @bartekpacia 🎉

**Pull request merged**
