### PR TITLE
style: fix typo on line 11 of deploy.sh

### LINKED ISSUE #231: Fix typo in deploy.sh script
## Description

As a developer of the backend,
I need to avoid misspelling,
so that I can make sure everyone has a good experience reading the code.

This issue is about fixing a small typo on the deploy.sh file, on line 11, on the "publishing" word.

_this issue is intended for the Google Code-in participants, it can be released after the program ends on January 23rd_

### Update [Required]
- [ ] Fix type on line 11

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by JustAnIndianGuy**
### Description 
Fixed the typo on line 11 of deploy.sh: "publising" to "publishing" 

Fixes #231

 ### Type of Change:
 - Code 

**Code/Quality Assurance Only** 

- Bug fix (non-breaking change which fixes an issue) 

### Checklist: 
- [ ] My PR follows the style guidelines of this project 
- [ ] I have performed a self-review of my own code or materials 

**Code/Quality Assurance Only** 
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by sara-02** [comment]
@JustAnIndianGuy Can you please fix a Typo in the PR description, there should be no space `Fixes # 231` between `#<Issue Number>`. So it should be `Fixes #231`

**Review by sara-02 — CHANGES_REQUESTED** [review]
The PR is looks good, issue in the PR description, putting on hold until then, will approve post that change.

**Comment by sara-02** [comment]
> @JustAnIndianGuy Can you please fix a Typo in the PR description, there should be no space `Fixes # 231` between `#<Issue Number>`. So it should be `Fixes #231`

I understand this is not a part of the task, but following correct guidelines and github workflow will help us all in the long run to avoid untagged PRs and issues.

**Review by annabauza — APPROVED** [review]
Well done! Thank you!

**Review by sara-02 — APPROVED** [review]

**Review by isabelcosta — APPROVED** [review]
Good job @JustAnIndianGuy !
Thank you for your contribution 🎉

**Comment by isabelcosta** [comment]
@JustAnIndianGuy  I edited the pull request (PR) description as @sara-02 mentioned, for the issue link. In the way ti is now, GitHub is able to reference the right issue, i.e., the PR will show up referenced on the issue #231 . Please keep this in mind for future PRs.

**Comment by isabelcosta** [comment]
Thank you for your contribution during GCI @JustAnIndianGuy !
I will close this due to #237 merge

**Pull request closed without merging**
