### PR TITLE
Set explicit timezone for cron jobs

### LINKED ISSUE #81: Set a timezone from the deployed server on the corn jobs
## Description

As a developer,
I need have control over the timezone used on the cron job used to complete a mentorship relation,
so that I can be sure in what time the cron job does the work of completing the job.

Current deployed server is in eu-central-1 Amazon's region.

### Update
- [ ] Set a timezone to the cron job that completes the mentorship relations instead of using a default

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by Conor0Callaghan**
### Description
Found issue #81 and saw that it had been open quite some time. I hope this is what you were looking for. 
Minor fix for #81, setting timezone in cron job to UTC

Fixes #81

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by isabelcosta** [comment]
@ivernus thank you for submitting this PR.
Can you please do the following:
- Follow our [Commit Message Style Guidelines](https://github.com/systers/mentorship-android/wiki/Commit-Message-Style-Guide) for your commit (squashed commit)
- Squash the 2 commits into one, following this ^^ guideline
- Update the name of the PR, to be more descriptive (e.g.: Set explicit timezone to cron job)

**Comment by m-murad** [comment]
@ivernus before sending a PR, make sure that you claim the issue.

**Comment by isabelcosta** [comment]
@ivernus if you have any trouble squashing commits here's a quick tutorial by GitHub on that -> https://help.github.com/articles/changing-a-commit-message/

**Comment by isabelcosta** [comment]
@ivernus I think you squashed one commit of another contributor by mistake :/ you have changes from another issue, previously committed, in here. Is that right?

**Comment by Conor0Callaghan** [comment]
Yep I'm afraid so @isabelcosta . Is that fixed now?

**Comment by isabelcosta** [comment]
@ivernus I'm sorry for the delay! I was a bit busy this week. I'm so happy you got to solve it!! 🎉 

Can you just change the commit message to follow the [Commit Message Style Guide](https://github.com/systers/mentorship-backend/wiki/Commit-Message-Style-Guide). Here's a suggestion: `feat: set timezone in cron job to UTC`

To do this you can just amend the message of the commit and push force to update the remote repository.

If you don't know how to do this, you can do the following:

```
git commit --amend -m "feat: set timezone in cron job to UTC"
```
 and then:
```
git push -f origin develop
```
After this change, I can approve and merge right away :D

Also for next times please create a specific branch for the issue you're working on.

**Comment by Conor0Callaghan** [comment]
> If you don't know how to do this, you can do the following:
> 
> ```
> git commit --amend -m "feat: set timezone in cron job to UTC"
> ```
> and then:
> 
> ```
> git push -f origin develop
> ```

It seems to do that amend it detached the head and I joined it back in, but that has messed up the single commit :man_facepalming:

**Comment by isabelcosta** [comment]
@ivernus 🤦‍♀️  git can be so frustrating sometimes!! The thing is that you had the right commit there in between. Can you look into undoing those commits, something like `git reset --soft (..........)` I'm not sure it depends on the situation. Can you take a look at that? I messed up git commits and heads a few times in the past as well 🤦‍♀️

**Comment by Conor0Callaghan** [comment]
Hopefully that does the trick @isabelcosta :sleepy:

**Comment by isabelcosta** [comment]
@ivernus thank you for your patience! that does the trick!

**Review by isabelcosta — APPROVED** [review]
@ivernus Thank you for your contribution and following our contribution guidelines 🎉

**Pull request merged**
