### PR TITLE
Added swagger.json

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
### Description

Beautified json file

Fixes # [ISSUE]
#840 

### Type of Change:

- Outreach

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by kritikaparmar-programmer** [comment]
Hey @Shivansh2407 did you wanted me to do these changes . Kindly review them ..

**Comment by Shivansh2407** [comment]
Not basically just to add the json file, I needed it in a tree view, with menus designed in HTML/CSS that are displayed on clicking the swagger.json link. The tree view is similar to one given in the ref link in the issue.

**Comment by SanketDG** [comment]
Any updates on this?

**Comment by kritikaparmar-programmer** [comment]
Hey @SanketDG , I'm facing some issues on this rn..😥

**Comment by Shivansh2407** [comment]
Please let us know the issues you're facing. Will be happy to help you out 👍

**Comment by kritikaparmar-programmer** [comment]
Hey @Shivansh2407 Actually I'm facing problem with how to interact on backend with that link of swagger.json
I also think that I've wasted your so much time..And if you want you can unassign me and assign others..
Really sorry for inconvenience..😓

**Comment by SanketDG** [comment]
I am not sure whether the issue itself has work that is suitable for OSH. It's a great idea, but the implementation is not supposed to be easy, considering that building a interactive json tree is not conventional at all, this is atleast work of 3-4 days even for an experienced frontend developer, with any framework.'

Also the fact, that it's way better if we just request this in `flask-restx`, instead of rolling our own.

**Comment by kritikaparmar-programmer** [comment]
So @Shivansh2407 and @SanketDG  what should I do now? :(

**Comment by Shivansh2407** [comment]
You can take up other issues till then . Keep Contributing ✨

**Pull request closed without merging**
