### PR TITLE
Dev: MS Backend server for BIT development purpose [DO NOT MERGE]

### LINKED ISSUE #667: DEV: Refactoring MS for BIT integration
**Is your feature request related to a problem? Please describe.**
To achieve the target of 2 REST APIs (MS and BIT APIs) with one database (bit_schema database), MS schema needs to be refactored to accommodate BIT.

**Describe the solution you'd like**
- [ ] Refactor one of the UserModel field from `organization` to `current_organization` to remove ambiguity with `Organization` table reference used in BridgeInTech schema.
- [ ] Refactor the use of Float to Numeric with precision "16,6" so to avoid precision mismatch from data store/retrieve from db.
- [ ] modify `.travis.yml` to employ postgresql as db for testing on travis build
- [ ] add pytest-cov dependency in requirements.txt

**Describe alternatives you've considered**
NA

**Additional context**
This is a cross-project issue between MS and BIT where improvement will be made gradually throughout GSoC 2020 period.

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
This PR is to prepare MS for BIT integration to achieve 2 REST APIs and one database architecture. This PR will be gradually improved throughout GSoC 2020 period. The decision on the best time to merge this PR to the `develop` branch will depend on **@anitab-org/bridgeintech-maintainers team** judgement.

Fixes #667 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- [ ] created `bit_schema` postgresql database as per instructions on [BIT wiki](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup) 
- [ ] run python unittest - result: all unittest passed (**note**: relevant tests alreeady modified to reflect the changes in the code)
- [ ] run the application on register and login as a new user with succesful outcome.

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

**Additional Note**
`.travis.yml` and `requirements.txt` files are also modified to accommodate this integration.

### CODE REVIEW

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers . This is the PR for preparing MS and BIT integration. As you can see from the file changes, I only make few small adjustments to MS code base.
These adjustments are mainly:
- renaming `organization` field on UserModel to `current_organization` to avoid ambiguity to the Organization table of BIT schema.
- refactor the use of Float to Numeric with prescribed precision since the tests initially failed on these floating points (see screenshots below:

* before refactoring Float -> Numeric
Screen Shot 2020-07-15 at 2 49 58 pm

* after refactoring to Numeric
Screen Shot 2020-07-15 at 5 08 09 pm

I have tested Register and Login on MS Swagger UI coonnected too bit_schema database with successful outcome.

* Test Register

Screen Shot 2020-07-15 at 5 11 35 pm

* Test Login

Screen Shot 2020-07-15 at 5 11 54 pm

I haven't tested the whole existing functionalities of MS since this is a cross-project issue. It's open to anyone to tests them 😉. cc @anitab-org/coding-team and @anitab-org/qa-team

**Comment by epicadk** [comment]
Can you please mark this as a draft pr so it isn't accidently merged?

**Comment by mtreacy002** [comment]
> Can you please mark this as a draft pr so it isn't accidently merged?

@epicadk , done 😉

**Comment by mtreacy002** [comment]
Closing this issue as we've decided to move ahead with a full integration of BIT backend to MS backend instead of partial integration attempted on this issue. cc @isabelcosta, @vj-codes and @epicadk

**Pull request closed without merging**
