### PR TITLE
Update email_confirmation.html

### PR DESCRIPTION
**Pull request by vanditkhurana**
Completed the required changes.

### Description

Fixes # [ISSUE]

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by vanditkhurana** [comment]
@vj-codes Please open #795 as it was updated. I forgot to close the brackets properly in #794.

**Comment by vanditkhurana** [comment]
@vj-codes Please open the issue #795 for review as i made a mistake in #794.

**Comment by vj-codes** [comment]
@vanditkhurana done

**Comment by vj-codes** [comment]
Closing as per authors request

**Comment by vanditkhurana** [comment]
Thanks @vj-codes

**Pull request closed without merging**
