### PR TITLE
Update email_confirmation.html

### LINKED ISSUE #728: Change email confirmation signature to AnitaB.org Open Source
**Describe the bug**

Since we have migrated our apps from Systers account to AnitaB.org when a new user creates an account for the Mentorship System the email confirmation signature should show **AnitaB.org Open Source** instead of Systers Open Source.

**To Reproduce**

1. Go to '/templates/email_confirmation.html'
2. Scroll down to line 11 or the email signature
3. See error
[Edit this file](https://github.com/anitab-org/mentorship-backend/blob/develop/templates/email_confirmation.html)

**Expected behavior**

1. Change 'Systers Open Source' to 'AnitaB.org Open Source'
2. Change link in anchor tag to "https://anitab-org.github.io/"

**Screenshots**

image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by vanditkhurana**
Completed the required changes.

### Description

Updated the email confirmation signature to AnitaB.org Open Source

Fixes #728 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by vj-codes** [comment]
@vanditkhurana #794 is a duplicate of this PR.Which one would you like to close?

**Comment by vanditkhurana** [comment]
@vj-codes #795. This one.

**Comment by vj-codes** [comment]
> @vj-codes #795. This one.

Closing since duplicate of #794

**Comment by vanditkhurana** [comment]
@vj-codes Can i go for other issues or i have to wait until it gets reviewed?

**Comment by vj-codes** [comment]
@vanditkhurana go for others!

**Comment by gaurivn** [comment]
@vanditkhurana, pls reference issue no. in the PR description.

**Comment by vanditkhurana** [comment]
@gaurivn Done the same.

**Comment by devkapilbansal** [comment]
Hi @vanditkhurana can you please rebase your branch with develop

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: Thanks @vanditkhurana for this

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Comment by devkapilbansal** [comment]
@vj-codes this PR doesn't needs testing 🤔

**Comment by vj-codes** [comment]
Adding label ready to merge since it's a  documentation change

**Comment by devkapilbansal** [comment]
@isabelcosta needs your input here

**Comment by vj-codes** [comment]
@devkapilbansal all Systers references shall be updated to AnitaB.org, the same is being done in the Android repo to and if you check the issue Isabel is present in the discussion as well .

**Comment by vj-codes** [comment]
@devkapilbansal but I guess there were issues about redesigning the email templates and if it's going to be done soon , this PR shall be closed
Will add this in agenda of mentorship sync up session :)

**Comment by isabelcosta** [comment]
We can still merge this as it is a very small change and easy to check. But you are correct @vj-codes , let's sync up about these designs, and have a standard, so it can be followed and the only thing that we can change later is the content.
Thank you @devkapilbansal and @vj-codes for helping to triage this 🙏🏾 you help sooo much

Thank you @vanditkhurana for contributing!

**Pull request merged**
