### PR TITLE
fix: renamed slack_username to zulip_username

### LINKED ISSUE #872: Deprecate 'slack_username' field in Mentorship System API
## Description
As a member of the app,
I need be able to find members on Zulip Chat,
so that I can talk to the member.

Currently, it's labelled as field `slack_username`. We have moved to Zulip. I want you to depreciate the field as it serves no purpose anymore across all instances of the REST API.

## Mocks
image

### Update [Required]
- [ ] Depreciate `slack_username` field across all instances of the REST APIs.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[4] hours

### PR DESCRIPTION
**Pull request by priyanshuone6**
### Description
 Renamed `slack_username` to `zulip_username`

Fixes #872 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by SanketDG — DISMISSED** [review]
Clean and straight, looks good!

This would break things on the android and flutter, pinging @isabelcosta on how these things were dealt with in the past.

**Review by vj-codes — DISMISSED** [review]
@priyanshuone6 LGTM 🎉

**Review by paritoshsinghrahar — DISMISSED** [review]

**Review by isabelcosta — COMMENTED** [review]
@priyanshuone6 this PR is very well accomplished :) 
However, because we already have this field in our dev database, to change the column name we need a migration script along with this. Do you know how to create a migration script? Here's a guide on it: https://alembic.sqlalchemy.org/en/latest/tutorial.html#create-a-migration-script

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@priyanshuone6 your commits are out of base. Please rebase it to current master. Also, squash your commits in one. 
You can do it by the steps mentioned below if you have problems. (As I saw that you make a pull request from anitab-org to your fork to update the changes)
```
git remote add upstream https://github.com/anitab-org/mentorship-backend.git
git fetch upstream develop
git rebase upstream/develop
git reset --soft HEAD~8
git commit
git push -f slack-zulip
```

**Comment by priyanshuone6** [comment]
@devkapilbansal I have done as you said, please look into it

**Comment by devkapilbansal** [comment]
@priyanshuone6 please look into @isabelcosta request above https://github.com/anitab-org/mentorship-backend/pull/887#pullrequestreview-506175087

Also, we have a commit message guideline too, please follow that

**Review by vj-codes — CHANGES_REQUESTED** [review]
@priyanshuone6 hey please solve the merge conflicts.Thanks!

**Comment by vj-codes** [comment]
@priyanshuone6 can you please add the migration script , without that the PR cannot be reviewed/approved further

**Comment by NenadPantelic** [comment]
@priyanshuone6 Are you working on this? Please, respond, so we can define the status of the PR/issue.

**Comment by devkapilbansal** [comment]
Closing due to inactivity. @priyanshuone6 feel free to comment if you want to continue

**Pull request closed without merging**
