### PR TITLE
Added Threshold outside loop

### LINKED ISSUE #978: Bug : Threshold is initialized inside the for loop
**Describe the bug**

Threshold is initialized multiple times.

**To Reproduce**

1. Go to https://github.com/anitab-org/mentorship-backend/blob/fffb4c39027b042f392d4edf0bb462e522cb7320/app/schedulers/delete_unverified_users_cron_job.py#L24

**Expected behavior**

Threshold can be initialized outside the for loop. 

**Additional context**

It would improve the performance.

### PR DESCRIPTION
**Pull request by Aayush-hub**
### Description

Initialized threshold outside for loop, to fasten excecution time

Fixes #978 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Locally by contributor

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by vj-codes — APPROVED** [review]
Congrats on your first contribution @Aayush-hub 
LGTM 🎉

**Comment by Aayush-hub** [comment]
@vj-codes Thank You. Looking forward for more contributions :)

**Review by epicadk — APPROVED** [review]
LGTM 👍

**Review by devkapilbansal — APPROVED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_  Testing delete unverified function
    _Expected Result_:  The function should be in working state even after removing threshold from the loop.
    _Actual Result_: Same as expected
  
2. Additional Comments: The function is also covered in unit tests. Therefore, unit tests passing also confirms that the function is working properly.

5. Status of PR Changed to: Ready to Merge.

**Pull request merged**
