### PR TITLE
Performed manual test and report of POST/login api

### LINKED ISSUE #753: Perform manual testing and report POST /login API
## Description

As a tester,
I need to test POST /login API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case (e.g.: login with a registered user correct username and password)
    - 1 negative case (e.g.: logging not registered user)

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#login](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#login)

### Update [Required]
- [ ] Test POST /login API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by vj-codes**
### Description
Tested step by step and added report for POST/login

Fixes #753

### Type of Change:

- Code- Quality Assurance
- Documentation

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by rpattath — APPROVED** [review]
Awesome work @vj-codes ! Make sure you open issue for the failed tests if there are no existing issues for them.

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@vj-codes it would be better if the images are uploaded to github cloud and then used here.

**Comment by devkapilbansal** [comment]
Hi @vj-codes please make the necessary changes

**Comment by vj-codes** [comment]
@devkapilbansal ahh I almost forgot about this PR, will close this later as I don't have the time as my exams are near would like to make the issue available for others rather than putting the PR on hold :)

**Comment by devkapilbansal** [comment]
Closing this PR and making the issue available

**Pull request closed without merging**
