### PR TITLE
Perform manual testing and report POST /register API

### LINKED ISSUE #766: Perform manual testing and report POST /register API
## Description

As a tester,
I need to test POST /register API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#register](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#register)

### Update [Required]
- [ ] Test POST /register API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by SHITIZ-AGGARWAL**
### Description

manual testing and reporting POST/register API

Fixes #766 

### Type of Change:

- Quality Assurance

**Code/Quality Assurance Only**

- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?

manually by entering data and testing on https://mentorship-backend-temp.herokuapp.com/

### Checklist:

- [x] at least one positive test
- [x] at least one negative test

### CODE REVIEW

**Comment by SHITIZ-AGGARWAL** [comment]
@gaurivn please tell if any changes are required or if I had made any mistake

**Comment by gaurivn** [comment]
@SHITIZ-AGGARWAL, could you pls squash the commits

**Comment by SHITIZ-AGGARWAL** [comment]
@gaurivn can you please tell if I made any mistake in squashing ?? 
this was my first time so i don't know how this works

**Comment by gaurivn** [comment]
@SHITIZ-AGGARWAL, you haven't squashed, just pull the latest changes, and then try squashing.

**Comment by SHITIZ-AGGARWAL** [comment]
@gaurivn I will update the commits in two three days, sorry for the delay , I am having some problem in squashing

**Pull request closed without merging**
