### PR TITLE
Update CONTRIBUTING.md

### LINKED ISSUE #1013: Remove .github/ISSUE_TEMPLATE folder
## Description

As a org admin / maintainer,
I need to maintain 1 version of issue templates used in the organization,
so that I can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Update [Required]
- [ ] Delete `.github/ISSUE_TEMPLATE`

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by Sejalcodes**
[#1013](https://github.com/anitab-org/mentorship-backend/issues/1013) Updated the link under bug_report in CONTRIBUTING.md

Fixes #1013 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Comment by vj-codes** [comment]
@Sejalcodes just a minor change in PR description -
Add the issue no next to fixes part like `Fixes #1013` so this PR gets linked with the issue and add a smal description about what changes you have made here under the `Description` title for this PR and the other one as well.
It helps to keep a better track :)

**Review by epicadk — APPROVED** [review]
💯

**Comment by epicadk** [comment]
Adding status ready to merge as it is a doc change. : )

**Comment by Sejalcodes** [comment]
> @Sejalcodes just a minor change in PR description -
> Add the issue no next to fixes part like `Fixes #1013` so this PR gets linked with the issue and add a smal description about what changes you have made here under the `Description` title for this PR and the other one as well.
> It helps to keep a better track :)

Oh okay, done, kindly check!

**Review by isabelcosta — APPROVED** [review]
Cool! Thank you for your contribution @Sejalcodes 🙌🏾

**Pull request merged**
