### PR TITLE
docs: update README to include commands to activate venv for windows …

### LINKED ISSUE #211: Activating virtual environment on Windows
**The issue**
In the README file for Mentorship System (backend) of Systers, where run.py is to be executed, the commands for activating the virtual environment (Step 2 under 'Run app') may not work on Windows computers.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have python 3 installed on a windows machine
2. Go to git bash (on windows) or Windows CMD
3. Create a virtual environment venv
5. If creating a virtual environment was successful, run `source ./venv/bin/activate`
4. See error saying no such directory

**Why it did not work**
On Windows machines, virtual environments do not have the bin folder under venv. That is the reason the error shows up.

**Solution**
For git bash users on windows:
Run the command `source ./venv/Scripts/activate` instead.
For windows cmd users:
`.\env\Scripts\activate`

**Screenshots**
image

Then complete the steps as provided in the README.

### PR DESCRIPTION
**Pull request by gowriprathap**
…users

### Description
Updated the README for activating venv for Windows users using Git Bash.

Fixes #211

### Type of Change:
- Documentation

### How Has This Been Tested?
The commands for windows successfully activates venv for windows users.

### Checklist:

- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by sumit-badsara** [comment]
@gowriprathap Even after you make a PR, and still if you continue to add stuff to the same branch, it still counts in that PR. So, the CMD command for windows is already added to this PR as you can see the latest commit. 
Also, mention the issue ID in the PR desciption as well which this PR solves. Like this
Fixes #211

**Review by sumit-badsara — CHANGES_REQUESTED** [review]
I guess individual installation of these packages isn't required. You must have faced some issues but these all packages are already present in requirements.txt

Also, Adding the code of activating in Step 2 as alternative for windows would be a better apporach. What do you think @isabelcosta  @gowriprathap ?

**Comment by gowriprathap** [comment]
> @gowriprathap Even after you make a PR, and still if you continue to add stuff to the same branch, it still counts in that PR. So, the CMD command for windows is already added to this PR as you can see the latest commit.
> Also, mention the issue ID in the PR desciption as well which this PR solves. Like this
> Fixes #211

Yes, I will do that, thank you!

**Comment by gowriprathap** [comment]
> I guess individual installation of these packages isn't required. You must have faced some issues but these all packages are already present in requirements.txt
> 
> Also, Adding the code of activating in Step 2 as alternative for windows would be a better apporach. What do you think @isabelcosta @gowriprathap ?

Yes, I think it's a good idea @BadduCoder , can I make that change and commit?

**Comment by sumit-badsara** [comment]
Yep, you can remove the individual package installation list from readme and commit.
But I'am not sure about the 2nd suggestion [Where to write windows command in readme], it would be great if @isabelcosta could approve this or tell an alternate approach to do so.

**Comment by gowriprathap** [comment]
> Yep, you can remove the individual package installation list from readme and commit.
> But I'am not sure about the 2nd suggestion [Where to write windows command in readme], it would be great if @isabelcosta could approve this or tell an alternate approach to do so.

Yes, sure @isabelcosta

**Comment by sumit-badsara** [comment]
@gowriprathap One last correction, you mentioned the PR's id which is 215 in Fixes.
But instead you need to mention the issue id. Which for this PR must be 211.
And there should be no gap between # and id.


Fixes : #215 ->Wrong, you need to mention issue which you solve.
Fixes : # 211 -> Wrong as space in between.
Fixes : #211 -> Correct, mentions the issue, and no space between ID and #

**Comment by gowriprathap** [comment]
> @gowriprathap One last correction, you mentioned the PR's id which is 215 in Fixes.
> But instead you need to mention the issue id. Which for this PR must be 211.
> And there should be no gap between # and id.
> 
> Fixes : #215 ->Wrong, you need to mention issue which you solve.
> Fixes : # 211 -> Wrong as space in between.
> Fixes : #211 -> Correct, mentions the issue, and no space between ID and #

Thank you so much for your help! I'm not really familiar with the process since this is my very first pull request :) I've made the change!

**Comment by sumit-badsara** [comment]
Congrats on your first PR! Yeah open source is all about helping out others while learning yourself.
Happy that I could somehow help you out in any way. Thanks! :smile:

**Comment by gowriprathap** [comment]
> Congrats on your first PR! Yeah open source is all about helping out others while learning yourself.
> Happy that I could somehow help you out in any way. Thanks! 😄

Thank you so much!! 😄😄

**Review by isabelcosta — CHANGES_REQUESTED** [review]
@gowriprathap I'm sorry for the delay in the response! It's great that this is your first PR :D
Can you please fix the merge conflicts, then I can approve and merge this :)

**Comment by gowriprathap** [comment]
> @gowriprathap I'm sorry for the delay in the response! It's great that this is your first PR :D
> Can you please fix the merge conflicts, then I can approve and merge this :)

Hi @isabelcosta I've fixed the merge conflicts, could you please verify if everything looks fine? You should be able to merge it to the main repository now! Thank you!

**Review by isabelcosta — APPROVED** [review]
Looks good @gowriprathap ! Thank you so much for your contribution :)
I would like someone that uses Windows environment to just double-check this. I will ping someone

**Comment by isabelcosta** [comment]
@rahulshah456 could you review this, since you also tried to add this to your PR :)

**Comment by gowriprathap** [comment]
> Looks good @gowriprathap ! Thank you so much for your contribution :)
> I would like someone that uses Windows environment to just double-check this. I will ping someone

Thank you so much! :)

**Comment by rahulshah456** [comment]
Yes, @isabelcosta  this is the same issue that I have encountered while working in the backend and the commands added by @gowriprathap works fine in the Windows environment. This is what I have done...

**Comment by isabelcosta** [comment]
@rahulshah456 you can review the PR if you wish and approve it :)

image

**Review by rahulshah456 — APPROVED** [review]
Everything looks fine!

**Comment by isabelcosta** [comment]
@rahulshah456 thank you for your review here 🎉 🙌

**Review by sumit-badsara — APPROVED** [review]

**Comment by isabelcosta** [comment]
@gowriprathap your PR was merged! thank you for your contribution and your patience throughout the long review process 🙌

**Comment by gowriprathap** [comment]
> @gowriprathap your PR was merged! thank you for your contribution and your patience throughout the long review process 🙌

Thank you so much for your help! @isabelcosta @BadduCoder @rahulshah456

**Pull request merged**
