### PR TITLE
feat: return user registration_time from get /users

### LINKED ISSUE #395: Return user's creation time from GET /users endpoints
**Is your feature request related to a problem? Please describe.**
I think that the API should include the user's creation date. The List of users returned now is already sorted by creation date in descending order, so why not include that information with the response?

**Describe the solution you'd like**
I'd like every `User` JSON objects returned from `GET /users` and `GET /users/verified` to have `creation_time` property, represented as timestamp integer.

**Describe alternatives you've considered**
I'm not aware of any viable alternatives.

**Additional context**
Encountered while doing [this task](https://codein.withgoogle.com/dashboard/task-instances/5998011734294528/).

### PR DESCRIPTION
**Pull request by diananova**
### Description

- added registration_date in get /users endpoint response

Fixes #395 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

- ran `python -m unittest discover tests` locally and all tests passed
- tested manually  (both GET /users and GET /users/verified)
Before:
image
After:
image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vj-codes** [comment]
Closing as the issue is not assigned to the author yet, if assigned later this PR will be reopened. 
Thank you for your contribution @diananova

**Review by vj-codes — CHANGES_REQUESTED** [review]
@diananova can you remove your changes from requirements.txt as they do not deal with the issue and add a screenshot showing changes in `How has this been tested ` part of description :)

**Comment by diananova** [comment]
@vj-codes I updated the comment with screenshots and made the requested changes.

**Review by vj-codes — APPROVED** [review]
Congratulations on your first PR to the repo @diananova 
LGTM 🎉

**Review by isabelcosta — APPROVED** [review]
Great work @diananova ! Thank you for this contribution 🤗

**Comment by isabelcosta** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Use GET /users/verified API to see the registration date as a field_  
      * logged with a user of mine
      * called GET /users/verfied using the account I logged in with
      * saw the new field
    _Screenshot/gif_:  
image
    _Expected Result_:  See registration timestamp being exposed in the GET /users/verified response
    _Actual Result_: See the new field exposed in user individual response
    
4. Additional Comments: Tested using https://ms-backend-review-pr-943.herokuapp.com/

5. Status of PR Changed to: Ready to Merge.

**Pull request merged**
