### PR TITLE
Create UI_for_relation_request_email.md

### LINKED ISSUE #770: Design UI for Mentorship relation request
## Description
As a developer,
I need to design a specific UI for Mentorship request sent,
so that I can improve the current UI.

### Context
When user A sends a mentorship relation request to user B, the latter receives an email conveying the same ([current template](https://github.com/anitab-org/mentorship-backend/blob/develop/templates/email_relation_request.html)). This UI should be designed following [AnitaB.org Branding Guidelines](https://drive.google.com/file/d/1QyQrNfGMa5e-3D0obDAGnkHZ1u7nhZ87/view).

## Mocks
Current mentorship relation request email
mrelationreq

### Update [Required]
- [ ] Design a specific UI for mentorship relation request

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by titiksha01**
### Description

Added a mock so that i can get the reviews and proceed to code.

Fixes #770

### Type of Change:

- User Interface

## Mock

RelationRequestUI

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

### CODE REVIEW

**Review by gaurivn — CHANGES_REQUESTED** [review]
The note sent by the mentee in this case is only Hi and export the figma design to png and place just the screenshot here instead of the figma link. And the "Take Action" button is not necessarily needed. Just button for "Login" would do so the mentor can see the notification and act accordingly.

**Comment by titiksha01** [comment]
> The note sent by the mentee in this case is only Hi and export the figma design to png and place just the screenshot here instead of the figma link. And the "Take Action" button is not necessarily needed. Just button for "Login" would do so the mentor can see the notification and act accordingly.

Okay i'll make the necessary changes.  Do i have to upload the png separately or in the md file itself ?

**Comment by titiksha01** [comment]
@gaurivn Pls see if it's correct now and guide me...

**Review by gaurivn — APPROVED** [review]
LGTM, Thank you, I'll ask @isabelcosta for review/ more insight.

**Comment by isabelcosta** [comment]
@titiksha01 thank you for contributing for OSH!
We will close the issue as we're going discuss designs with new community design ambassadors. I will add this PR to our Wiki :)

**Pull request closed without merging**
