### PR TITLE
fix: Swagger documentation HTTP code display

### LINKED ISSUE #1128: fix: Swagger documentation HTTP code display
### Describe the bug
In some places in the swagger documentation, the HTTP error codes values aren't being displayed and instead the variables are being displayed.

### To Reproduce
1. Go to [https://mentorship-backend-temp.herokuapp.com/](https://mentorship-backend-temp.herokuapp.com/) and check under Mentorship Relation. This is just an example. There are many such instances across the project.

### Expected behavior
The error codes need to be displayed. Ex : 400 , 403 etc instead of HTTPStatus.NOT_FOUND

### Screenshots

Screenshot (174)

### Desktop:
 - OS: [Windows]
 - Browser [ chrome]

### PR DESCRIPTION
**Pull request by RiddhiAthreya**
### Description

Changed the swagger documentation to display the error codes for all the endpoints 

Fixes #1128 

### Type of Change:

- Documentation

### How Has This Been Tested?

An example of the change
Screenshot (182)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by epicadk — DISMISSED** [review]
Looks good. Thanks : ).

**Comment by epicadk** [comment]
@isabelcosta please approve the workflow run.

**Review by isabelcosta — DISMISSED** [review]

**Comment by isabelcosta** [comment]
@RiddhiAthreya amazing work fixing the HTTP code rendering on swagger 👏🏾 🎉 🙌🏾 
Just one comment, I see the lint is failing. Could you just run lint on the files you changed. Here are the instructions on how to pip install and run black lint tool 👉🏾 https://github.com/anitab-org/mentorship-backend#auto-formatting-with-black

**Comment by RiddhiAthreya** [comment]
@isabelcosta thanks! done!

**Review by epicadk — APPROVED** [review]

**Review by isabelcosta — APPROVED** [review]
Thank you for contributing @RiddhiAthreya  🙌🏾 🎉

**Comment by isabelcosta** [comment]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

   * Opened and verified `PUT /task_comment` 
     _Screenshot/gif_:  
     right HTTP code are showing on Swagger

     _Expected Result_:  values show as numeric values instead of displaying the name of the enum being used
     _Actual Result_: HTTP values show as numeric
  
3. Additional Comments: I tested via a Review App of Heroku: https://dashboard.heroku.com/pipelines/6ca457ca-1598-4fcd-b4bd-7ac5d70f6dde

5. Status of PR Changed to: Ready to Merge.

**Comment by isabelcosta** [comment]
Thank you for your contribution @RiddhiAthreya 🤗

**Pull request merged**
