### PR TITLE
Add environment variables documentation

### LINKED ISSUE #484: Add environment variables documentation from wiki to docs folder
## Description

As a developer,
I need know what every environment variable means and what is it used for,
so that I can properly set them up.

The idea is to add the documentation about the [environment variables](https://github.com/anitab-org/mentorship-backend/wiki/Environment-Variables) on the repo itself instead of just the Wiki, so that is can be modified by contributors easily.

### Update [Required]
- [ ] Add Environment variables doc to `/docs` folder.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
10 min

### PR DESCRIPTION
**Pull request by isabelcosta**
### Description

Added environment variables according to what is on Wiki, so that contributors can help to maintain that documentation. I don't think it needs much reviewing, because if things can be fixed, they can be as part of usual open source contributions.

Fixes #484 

### Type of Change:

- Documentation

### How Has This Been Tested?

Checked the preview of [here](https://github.com/isabelcosta/mentorship-backend/blob/484-add-env-variables-doc/docs/environment-variables.md).

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Postman API at /docs folder
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by ramitsawhney27 — APPROVED** [review]
Looks very good and extremely helpful. Wonderful initiative as always!

**Comment by isabelcosta** [comment]
Thank you so much @ramitsawhney27 🎉 
I am super happy you find this helpful for contributor 🙌
Now I just need one more approval @annabauza @mayburgos @sara-02 ;)

**Review by annabauza — APPROVED** [review]
@isabelcosta have you linked this file anywhere, like readme?

**Comment by isabelcosta** [comment]
@annabauza thank you so much!

**Pull request merged**
