### PR TITLE
[Program: GCI] [Part 2 of 2] Check for only pylint errors and ignore warnings,refactor,convention and fatal class messages (Backend)

### PR DESCRIPTION
**Pull request by asawesome07**
### Description
Added pylint to travis

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
The change doesn't require any testing.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by asawesome07** [comment]
I guess it is supposed to fail, as it is using pylint

**Review by Tlazypanda — APPROVED** [review]
@asawesome07 Approved :)

**Review by isabelcosta — COMMENTED** [review]
Thank you for your contribution @asawesome07 !

**Review by Tlazypanda — APPROVED** [review]
Approved :)

**Comment by isabelcosta** [comment]
Thank you for your contribution @asawesome07  !
We decided to close PRs related to this task so that we can have an issue, where a contributor can add this configuration and fix the problems that arise, from this new configuration.

**Pull request closed without merging**
