### PR TITLE
Testing and report POST /register API

### LINKED ISSUE #766: Perform manual testing and report POST /register API
## Description

As a tester,
I need to test POST /register API,
so that I can provide a test report on it.

You should create a markdown file inside `/docs/manual_tests` with the following content:
- Scenario tested step by step with dummy data you used (e.g.: username and password)
- Report it as:
```
   * _Test1 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:
   * _Test2 Description_  
     _Screenshot/gif_:  
     _Expected Result_:  
     _Actual Result_:  
     ... 
```
If you find a test that the expected result does not match the actual result then create an issue (following [Bug Report template](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)), and mention it in your markdown file.
- Make sure to test at least:
    - 1 positive case 
    - 1 negative case 

**Resources:**
- Deployed Backend: https://mentorship-backend-temp.herokuapp.com/
- Quality Assurance test cases: [/docs/quality-assurance-test-cases.md#register](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/quality-assurance-test-cases.md#register)

### Update [Required]
- [ ] Test POST /register API
- [ ] Create a markdown file under `/docs/manual_tests` with the content mentioned above (at least 2 tests).

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by SHITIZ-AGGARWAL**
### Description

Manually testing the user registration process and documenting it

Fixes #766 

### Type of Change:

- Quality Assurance

### How Has This Been Tested?

Manually by entering the data and documenting it

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Review by vj-codes — CHANGES_REQUESTED** [review]
@SHITIZ-AGGARWAL it's great! Can you please update` Expected Results` in terms of `success or fail `with the response message .Just this minor change and you are done!

**Comment by SHITIZ-AGGARWAL** [comment]
@vj-codes done 👍  , please tell if any other changes are required

**Comment by SHITIZ-AGGARWAL** [comment]
@vj-codes is this PR ready for OSH submission ??

**Comment by vj-codes** [comment]
@SHITIZ-AGGARWAL absolutely ! Final reviews and merging will happen after OSH , until then you can submit this and look for other issues too!

**Review by vj-codes — DISMISSED** [review]
@SHITIZ-AGGARWAL LGTM 🎉

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@SHITIZ-AGGARWAL the folder name should be `manual_tests` instead of `manual tests`. Also, can you please crop your images to show relevant information only.

Also, squash your commits in one and follow commit guidelines mentioned [here](https://github.com/anitab-org/portal/wiki/Commit-Message-Style-Guide).

**Comment by vj-codes** [comment]
@SHITIZ-AGGARWAL hey please update the requested changes

**Comment by SHITIZ-AGGARWAL** [comment]
sorry for the delay , my exams were going on, will update it as soon as possible

**Comment by SHITIZ-AGGARWAL** [comment]
@vj-codes I want to go back to  0a97f2e , will `git reset --hard 0a97f2e` work ?

**Comment by devkapilbansal** [comment]
> @vj-codes I want to go back to [0a97f2e](https://github.com/anitab-org/mentorship-backend/commit/0a97f2ebf1b576754ac53652f01489db13fabbd2) , will `git reset --hard 0a97f2e` work ?

Yes, @SHITIZ-AGGARWAL it will

**Comment by devkapilbansal** [comment]
@SHITIZ-AGGARWAL squash and rebase your commits too

**Comment by SHITIZ-AGGARWAL** [comment]
@devkapilbansal while rebasing ,some merge conflicts came ,please give time to resolve them
image

**Comment by devkapilbansal** [comment]
@SHITIZ-AGGARWAL use git rebase on your local and then open the file where merge conflict arises
Then remove
```
<<<<<Head line
Everything between ======== and >>>> line
```
Then git rebase --continue

**Comment by devkapilbansal** [comment]
In your case just remove the lines highlighted with light green and save your file, add it using git add and then git rebase --continue

**Comment by devkapilbansal** [comment]
Hi @SHITIZ-AGGARWAL can you please use this template in your file to follow same convention throughout
https://github.com/anitab-org/mentorship-backend/blob/develop/docs/test-pr-guide.md#template-to-report-pr-testing-results

**Comment by devkapilbansal** [comment]
Hi @SHITIZ-AGGARWAL please follow this template to follow same convention throughout
https://github.com/anitab-org/mentorship-backend/blob/develop/docs/test-pr-guide.md#template-to-report-pr-testing-results

**Comment by SHITIZ-AGGARWAL** [comment]
@devkapilbansal do I need to add  `Status of PR Changed to: Needs Review or Ready to Merge` ? Also there are no Additional testcases so can I remove that section?

**Comment by devkapilbansal** [comment]
No no you don't need to add that, also remove irrelevant sections you can take reference from other similar PRs that are merged or ready to merge

**Comment by SHITIZ-AGGARWAL** [comment]
okay , I  will check other pull requests and make the required changes

**Comment by vj-codes** [comment]
@SHITIZ-AGGARWAL hey any updates?

**Comment by devkapilbansal** [comment]
@SHITIZ-AGGARWAL are you working on this?

**Comment by SHITIZ-AGGARWAL** [comment]
Sorry for the delay , I will soon update it

**Comment by devkapilbansal** [comment]
> Sorry for the delay , I will soon update it

Okay @SHITIZ-AGGARWAL just tag once you are done

**Comment by SHITIZ-AGGARWAL** [comment]
My exams are going on , I will do the changes in some days

**Comment by vj-codes** [comment]
@SHITIZ-AGGARWAL any updates?

**Comment by vj-codes** [comment]
@SHITIZ-AGGARWAL closing due to inactivity 
Thank you for you contribution :)

**Pull request closed without merging**
