### PR TITLE
chore: change imports to flask_restx

### LINKED ISSUE #705: Tests are failing in the "Run Tests" check
**Describe the bug**

The tests are failing 😱 
This is the first time it failed: https://github.com/anitab-org/mentorship-backend/runs/935862710

**To Reproduce**

1. Go to https://github.com/anitab-org/mentorship-backend/runs/935862710
2. Click on 'Run Tests' build
3. Scroll down to tests failing
4. See errors

Run tests locally, and see if they work.

**Expected behavior**

Tests should not be failing.

### PR DESCRIPTION
**Pull request by nickinack**
Description
Fix failing tests

Fixes #705

- Code
- This change requires a documentation update (software upgrade on readme file)
- Update requirements.txt

### CODE REVIEW

**Review by SanketDG — APPROVED** [review]

**Comment by nickinack** [comment]
Can we merge this ?

**Review by vj-codes — APPROVED** [review]
@nickinack Congrats on your first contribution to this repository!!!
Just a suggestion, please don't send PRs from develop branch of your fork from next time.
Since this PR is already created , I'm approving it and the label 'status:needs review' has been updated to 'status:needs testing'.
After it's tested , PR can be merged.

**Review by isabelcosta — APPROVED** [review]
Thank you so much for fixing this bug in the tests @nickinack 🎉

**Comment by isabelcosta** [comment]
I will bypass "Needs Testing" phase, because this is a change in an automation test, which is being tested automatically by the "Run Tests" GitHub action check.

**Comment by isabelcosta** [comment]
@nickinack just one little thing, I see you didn't follow much of the Pull Request template. For next PRs please follow the template and avoid removing everything from it. The checklist is important to make sure you followed guidelines and completed action items for PRs submitted to this repository :) 
Thank you again!

**Comment by nickinack** [comment]
@isabelcosta , I'll make sure I'll follow the PR template from my next issues; thank you so much 😀

**Pull request merged**
