### PR TITLE
Docs: updated python badge in readme.md

### LINKED ISSUE #830: Update python badge in readme.md
## Description
As a contributor,
I need no contradictions in the README file,
so that I won't be doubtful of the dependencies.
Update badge in readme from Python 3.6 to Python3 as it was decided in #820 to keep all versions same.

### Acceptance Criteria

- [ ] Update [Required]
- [ ]  Update Python 3.6 badge to Python 3 badge

### Definition of Done
 

- [ ] All of the required items are completed.
- [ ]  Approval by 1 mentor.

### Estimation
0.1 hour

### PR DESCRIPTION
**Pull request by codesankalp**
# Description

changed the badge from python 3.6 to python 3.x to avoid any contradictions about the dependencies.

Fixes #830

## Type of Change:

* **docs** : updated readme of docs.

## How Has This Been Tested?

Tested manually by visiting and reviewing the svg of the badge.

## Checklist (Acceptance Criteria)

* [x] Update [Required]
* [x] Update Python 3.6 badge to Python 3.x badge

## Definition of Done (to be changed by mentor)

* [ ] All of the required items are completed.
* [ ] Approval by 1 mentor.

### CODE REVIEW

**Comment by PrashanthPuneriya** [comment]
@codesankalp Does the badge signify that the version is 3.0 or 3.x?

**Comment by PrashanthPuneriya** [comment]
Also, can you please edit the PR to follow the guidelines?

**Comment by codesankalp** [comment]
In the issue it's mentioned to make it python 3 without specifying version. 
I will change the pr according to guidelines.
Can you tell me what to change i.e. python 3.x or python 3.0
Thanks @PrashanthPuneriya

**Comment by PrashanthPuneriya** [comment]
By Python 3 what I meant was to not specify any version i.e. the project works on any version of Python 3. Are there any other badges which handles this case?

**Comment by codesankalp** [comment]
Now I have added a badge for python 3.x which I think is more accurate for viewers.

**Comment by codesankalp** [comment]
@PrashanthPuneriya  I have made the necessary changes.
I don't know but the checks are not successful even I have only changed the readme.

**Comment by PrashanthPuneriya** [comment]
> @PrashanthPuneriya I have made the necessary changes.
> I don't know but the checks are not successful even I have only changed the readme.

No problem! The PR LGTM!! Thanks for your contribution :)

**Review by PrashanthPuneriya — APPROVED** [review]

**Review by vj-codes — APPROVED** [review]
@codesankalp congrats on your first contribution to the repo 🎉 
LGTM, although I would suggest to checkout to any suitable branch and then commit changes while working on your next issues.

**Comment by codesankalp** [comment]
Thanks, @vj-codes @PrashanthPuneriya .

**Comment by Mahnoor123-Fatima** [comment]
can you assign this issue to me

**Comment by codesankalp** [comment]
> can you assign this issue to me

This is a pull request.

**Review by isabelcosta — APPROVED** [review]
Great work @codesankalp 👏 🎉

**Pull request merged**
