### PR TITLE
style: format comments of TaskCommentModel present in task_comment.py file

### LINKED ISSUE #669: Bug: Fix inconsistent format of comments present in task_comment.py file
**Describe the bug**

The comments of TaskCommentModel present in [task_comment.py](https://github.com/anitab-org/mentorship-backend/blob/develop/app/database/models/task_comment.py#L8) file are not formatted correctly.

**To Reproduce**

1. Go to [task_comment.py](https://github.com/anitab-org/mentorship-backend/blob/develop/app/database/models/task_comment.py) file
2. Scroll down to line no. 8
3. See the inconsistent format present from line no. 8 to line no. 17

**Expected behavior**

Line no. 10 to 17 should not have those extra 4 spaces as indentation.

### PR DESCRIPTION
**Pull request by PrashanthPuneriya**
## Description

Fixes #669 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

NA

### CODE REVIEW

**Comment by vj-codes** [comment]
Closing since issue is not assigned yet. @PrashanthPuneriya you can reopen it later:)

**Comment by PrashanthPuneriya** [comment]
@vj-codes How can I reopen this PR? It seems I don't have enough rights to reopen it. Should I create a new PR?

**Comment by vj-codes** [comment]
@PrashanthPuneriya reopened It!!

**Comment by PrashanthPuneriya** [comment]
@vj-codes How can I have the privileges to reopen PRs, add labels, request reviews, etc ?

**Comment by vj-codes** [comment]
@PrashanthPuneriya A person who's part of an open source ambassador team do it.There a 5-6 teams and to be a part of one you'll need to fill a form and other info like responsibilities of a member can be found on zulip.
But anyway everyone's welcome here to contribute:)

**Comment by PrashanthPuneriya** [comment]
@vj-codes Can you share the link to that form? Couldn't find it on zulip.

**Comment by vj-codes** [comment]
> @vj-codes Can you share the link to that form? Couldn't find it on zulip.

When I find it, I'll tag you on zulip @PrashanthPuneriya

**Comment by isabelcosta** [comment]
Thank you @vj-codes for helping keeping the community guidelines in check!

**Review by isabelcosta — APPROVED** [review]
Looks good :) Thank you for your contribution!

**Review by SanketDG — APPROVED** [review]
LGTM!

Maybe we can someday enforce [PEP 257](https://www.python.org/dev/peps/pep-0257/) on the docstrings! :slightly_smiling_face:

**Comment by isabelcosta** [comment]
> Maybe we can someday enforce PEP 257 on the docstrings! 

@SanketDG if you'd like to create an issue about this, feel free to do so.

**Comment by isabelcosta** [comment]
@anitab-org/qa-team This PR does not involve feature changes, because of its change in the docstrings (documentation in python). So what could go wrong here would be the indentation, since the tests are passing I will assume this is okay to merge.

**Pull request merged**
