### PR TITLE
Fix lint errors, fix pep8 warnings and remove duplicates

### LINKED ISSUE #178: Refactor codebase according to PEP8 standards
## Description
As a developer,
I need the codebase to follow PEP8 standards,
so that I can read and maintain it with less effort.

### Update [Required]
- [ ] Refactor entire codebase to pass flake8 checks

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by ilyamaier**
### Description
- Fixed lint errors
- Fixed pep8 warnings
- Removed code duplicates (created new BaseTestCases or some functions like `mentorship_relation.py` in validations folder)
- Removed unused variables, imports, messages
- Updated dependencies
- Fixed some typos

Fixes #178 

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
The code was tested using existing tests and Swagger UI

# Screenshots:

**Before:**

Screenshot (124)
Screenshot (125)

**After:**

Screenshot (122)
Screenshot (123)

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged
- [x] Update requirements.txt

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by ilyamaier** [comment]
@annabauza @sara-02 @isabelcosta Hey! Hope you're having a good day :) Would you mind reviewing it if you have some free time? Thank you in advance!

**Comment by sara-02** [comment]
@IlyaMaier I Appreciate the hard work you have put in, but 68 files is a lot to review even for all of us combined.
Will it be possible to create a separate PR for each of the pointers in your Description?

**Comment by ilyamaier** [comment]
@sara-02 Thanks! Yeah I understand. I wi try to combine the changes logically and create some more smaller PRs

**Comment by ilyamaier** [comment]
@sara-02 @annabauza @isabelcosta I will create all the PRs in a few days, as quickly as possible. Here is the first one: [Update requirements.txt](https://github.com/systers/mentorship-backend/pull/416)

**Comment by isabelcosta** [comment]
Thank you for your contribution here @IlyaMaier during GCI contest ! I will close this because it has so many merge conflicts, I will leave this for a clean slate PR. doing some spring cleaning :)

**Pull request closed without merging**
