### PR TITLE
Change registration date type to Float (#48)

### LINKED ISSUE #48: Save registration date as a UNIX timestamp
## Description
As a developer,
I need receive in the API response the registration date as a UNIX timestamp,
so that I can properly parse the registration date.

Currently, the registration date of a user is saved as a `DateTime`.
Save it as a `Float`.

### Update
- [ ] Change the registration date data type from `DateTime` to `Float`.
- [ ] Add or Update tests for this
- [ ] Return UNIX timestamp in List Users API response (and others)
 
## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by bhawesh96**
### Description

Change the registration date type from DateTime to Float

Fixes #48 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
_Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test._

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Update Swagger documentation and the exported file at /docs folder

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by isabelcosta** [comment]
@bhawesh96 don't worry about sysbot closing this I'll help you fix (re open) this later today. No need to create other PRs

**Comment by isabelcosta** [comment]
@bhawesh96 you deleted this part which was necessary to follow the template:

`### How Has This Been Tested?`

Now I can review your PR ;)

**Review by isabelcosta — CHANGES_REQUESTED** [review]
@bhawesh96 thank you for following the Commit Style guideline :D
- Your changes unfortounatly are not enough. What we want is to save it as a float and fix all parts that use this. You can see how the flow works for a database model attribute and follow the example of MentorshipRelation model ([app/database/models/mentorship_relation.py](https://github.com/systers/mentorship-backend/blob/develop/app/database/models/mentorship_relation.py)). 
- Also this ^^^^ may be the reason why Travis CI failed tests.
- For now don't worry about Swagger thats something that is automatically generated.

Please tell me if you get stuck and need help on this ;)

**Comment by bhawesh96** [comment]
I'm kind of stuck here.
As per my understanding, I have changed the datatype of `registration_date` to `Float` from `DateTime` for all occurrences. Please tell me what else is required.

**Comment by isabelcosta** [comment]
@bhawesh96 no problem! This codebase is growing so it's normal if you get a bit lost.

- What comes now to my mind is that you have to change tests, that expect the `registration_date` to be of DateTime data type. 
- Also, you might have to change something in the middle, for example, you changed DataModel, but then will have DAO and then API Resources, make sure that flow is working.
- Try to create a user and see if anything goes wrong in the backend. (if you don't know how to use Swagger UI, [here's a quick tutorial on how to use it for login](https://github.com/systers/mentorship-backend/wiki/Using-Swagger-UI))

Let me know if you need a little more help ;)

**Comment by bhawesh96** [comment]
@isabelcosta , as per your last notes, I ran tests and also tried to create a new user. All worked without any error.

**Review by isabelcosta — APPROVED** [review]

**Comment by isabelcosta** [comment]
@bhawesh96 great job with this PR! Since you're working on the other PR #151  as well, I think I will merge this once you finish the other PR's work. Because every time we push something here to develop, the database is reset.

**Pull request merged**
