### PR TITLE
fix: Update http code values instead of expressions

### LINKED ISSUE #947: Use HTTPStatus code values instead of enum representation, in Users API in Swagger UI
**Describe the bug**

The values shown on Swagger UI of Users API should be in number format instead of Enum Representations of Status Codes. For example 200 instead of HTTPStatus.OK.

**To Reproduce**

1. Go to https://mentorship-backend-temp.herokuapp.com/
2. Scroll down to Users API
3. See enum representation.
image

**Expected behavior**

Use of Values of Status Codes instead of Enum Representations in Swagger UI

**Desktop (please complete the following information):**
 - OS: Ubuntu 20+ 
 - Browser: Firefox Web Browser
 - Version: --

### PR DESCRIPTION
**Pull request by surbhigoel191**
### Description

All enum expressions replaced with HTTPStatus code values in Users API in Swagger UI

Fixes #947 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Before
103191627-a8263700-48fb-11eb-9e00-c0576444777b

After
Screenshot (248)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by surbhigoel191** [comment]
Can someone tell me what's wrong here?

**Comment by vj-codes** [comment]
@surbhigoel191 it's failing coz of the errors thrown by Black tool used in formatting the code, the tests are successful though.
Run `black app/api/resources/user.py ` this command and the code will be reformatted , push the changes and the build shall pass.
If you have any question, do update:)

**Comment by surbhigoel191** [comment]
Done 😃 Please review it now. @vj-codes @isabelcosta

**Review by vj-codes — DISMISSED** [review]
Thank you for your contribution @surbhigoel191 
LGTM 🎉

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@surbhigoel191 there is a [commit message guideline](https://github.com/anitab-org/mentorship-backend/wiki/Commit-Message-Style-Guide) that you should use. Also, rebase your branch with current develop branch to ensure the test cases passed with latest changes.

**Comment by surbhigoel191** [comment]
@devkapilbansal Kindly review now.

**Review by isabelcosta — APPROVED** [review]
Great work @surbhigoel191 ! Thank you for your contribution 👏

**Comment by isabelcosta** [comment]
@surbhigoel191 it's not necessary to rebase your branch, if you are not sure of how to do it. I can squash and fix the merge commit message.
However, is good to have in mind that we will squash the commits and fix the commit to follow the commit message guideline. This is mentioned in our CONTRIBUTING.md.
cc @devkapilbansal

**Review by vj-codes — APPROVED** [review]

**Comment by isabelcosta** [comment]
The changes made in this PR were tested locally.
I tested via https://ms-backend-review-pr-953.herokuapp.com/

Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Open Login API definition and test it_  
    _Screenshot/gif_:  

image

_Expected Result_:  
_Actual Result_: When I tested the Login API I got the token, and Swagger UI did not show "Undocumented" message next to the response value. Also, the responses documentation no longer shows `HTTPStatus.OK` instead of `200` value. 🎉 

3. Additional comments: I checked the responses documentation section for each User related API to make sure none was still showing the HTTPStatus string.

4. Status of PR Changed to: Ready to Merge.

**Pull request merged**
