### PR TITLE
Setting relative paths to repository files on the README.md file.

### LINKED ISSUE #585: Setting relative paths to repository files on the README.md file.
## Description

Setting relative paths to repository files on the README,
so that I can see them properly on my fork README rendering.

On README the links to LICENSE, CONTRIBUTING.md, etc located within the repo, have absolute links to this organization repo, this causes to within our forks, it is linked to these files in the anitab-org organization files instead of on my fork's files.

## Acceptance Criteria

Turn paths to local files from absolute paths to relative paths on README

### PR DESCRIPTION
**Pull request by garimasingh128**
### Description

Setting relative paths to repository files on the README,
so that I can see them properly on my fork README rendering.

On README the links to LICENSE, CONTRIBUTING.md, etc located within the repo, have absolute links to this organization repo, this causes to within our forks, it is linked to these files in the anitab-org organization files instead of on my fork's files.

Fixes #585 

### Type of Change:

- Code
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by garimasingh128** [comment]
Kindly review and tell if any other changes are required.

**Review by SanketDG — APPROVED** [review]
LGTM!

**Review by isabelcosta — APPROVED** [review]
Looks good :) Great work @garimasingh128 👏 
Thank you for your contribution!

**Comment by isabelcosta** [comment]
Thank you @SanketDG for reviewing this :)
I will merge this since this is a change to documentation with not production code change

**Pull request merged**
