### PR TITLE
Removed some pep8 warnings

### LINKED ISSUE #261: Remove pycodestyle warnings from app/api
**Describe the bug**
The codebase doesn't conform to the rules of [pycodestyle](http://pycodestyle.pycqa.org/en/latest)

**To Reproduce**
1. Open command line in project's root directory
2. Run `pycodestyle app/api`
3. See lots of code style warnings being reported

**Expected behavior**
Output of `pycodestyle app/api` should return no output.

### PR DESCRIPTION
**Pull request by bartekpacia**
### Description
All pep8/pycodestyle warnings fixed in `app/api`.

Fixes #261 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Run test suite which passes successfully.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by isabelcosta** [comment]
I will close this PR, since a lot as changed since the GCI. We need to find a way to fix this and run the pylint at the same way 🤔 I am just doing a spring cleaning.

Thank you so much for your @bartekpacia contribution during GCI contest 🙌

**Comment by bartekpacia** [comment]
Sure @isabelcosta. Modern IDE like PyCharm is able to automatically scan through whole codebase and fix many lint warnings, so it shouldn't require a lot of time :)

**Comment by isabelcosta** [comment]
@bartekpacia its just because I am thinking about having an issue that runs the pylint or something similar and also fixes the issues with pep something, so we don't have the pipeline failing at some point. Do you still want to do this then? Won't the PR become ginormous ?  Do you have any suggestions on how to manage this and fix it once for all ⚔️ ?

**Comment by bartekpacia** [comment]
i think it *will* be ginormous (new word for me🧐) but it'll be worth it
Also, some checks on the CI would be great to enforce that code style once we get rid of all warnings

Also, I'm okay with somebody else claiming it👀

**Comment by isabelcosta** [comment]
I'm also okay with you claiming it 👀 🙃 you already have a lot on your plate, I will leave it for someone else then @bartekpacia

**Pull request closed without merging**
