### PR TITLE
F strings for users folder

### LINKED ISSUE #743: Use f-strings in users folder test files
## Description
As a developer,
I need change strings interpolation in users folder test files,
so that I can make that file follow Coding Standards.

Format strings using f-strings when appropriate for `tests/users/*` files.

## Mocks
As an example, here:
https://github.com/anitab-org/mentorship-backend/blob/9102175e85302a04ad4d3bc4d1f89f30f840b0f9/tests/users/test_api_resources.py#L49-L50
We can use f-strings such as:
```
f"POST /register failed to register Testing User! with error code = {response.status_code}" 
```
### Update [Required]
- [ ] Update all string instances to use f-string, when applicable for all such files present in `tests/users` folder.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.25 hour

### PR DESCRIPTION
**Pull request by priyanshurohilla**
### Description

Fixed f strings
Fixes #743 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

local tests have been performed
### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

### CODE REVIEW

**Review by PrashanthPuneriya — APPROVED** [review]
Great start @priyanshurohilla. I apologise for the late review. I hope you don't mind it :)

**Comment by vj-codes** [comment]
@PrashanthPuneriya only one file that you mentioned in issue is changed , so is it supposed to be like that or all strings in `tests/users` ?

**Comment by PrashanthPuneriya** [comment]
Yes @vj-codes. There was only this file which required changes all other files of `tests/users/` don't require any changes. This was a first-timer-only issue. Hence, very little work.

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Comment by vj-codes** [comment]
Adding label` ready to merge` as it's a documentation PR

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: 

Only one string found in test/users folder that needs to be changed and is changed successfully

**Review by isabelcosta — APPROVED** [review]
Thank you for your contribution @priyanshurohilla 🙌

**Pull request merged**
