### PR TITLE
fix: Password accepting empty spaces fixed

### LINKED ISSUE #918: Password accepting empty spaces.
**Describe the bug**

On the register endpoint the password accepts empty spaces. Where as on the Change password it does not.

**To Reproduce**

1. Go to 'register endpoint'
2. Click on 'create a new user with spaces in their password'
3. Scroll down to 'change password and try to change password to another password containing spaces'
4. See error saying no spaces allowed in the password

**Expected behavior**

Password validation should be same for both endpoints i.e. either allow spaces in both endpoints or for neither.

### PR DESCRIPTION
**Pull request by 17sushmita**
### Description

Register endpoint was accepting empty spaces in password while change password did not. This PR fixes the issue and now neither register endpoint nor change password accepts spaces in password.

Fixes #918 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Locally tested by running `python -m unittest discover tests`

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
@17sushmita please resolve the merge conflicts.Also, see that the test coverage is decreasing.

**Comment by 17sushmita** [comment]
I've added the tests and resolved conflicts. Please review @devkapilbansal @PrashanthPuneriya

**Review by devkapilbansal — APPROVED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

  * _Test1 Description_ 
    _Screenshot/gif_:  
Screenshot from 2020-12-01 05-19-09
    _Expected Result_:  In register endpoint, password should not contain spaces
    _Actual Result_: Passed doesn't contain spaces during registration

3. Additional testcases covered: Ran `python -m unittest discover tests` to ensure every test case passed

4. Additional Comments: New test cases as per requirement are included

Thanks @17sushmita for this. 
LGTM :+1:

**Comment by devkapilbansal** [comment]
Pinging @epicadk for review

**Review by isabelcosta — APPROVED** [review]
great work @17sushmita 👏 💪 Thank you so much for contributing to this project ❤️

**Pull request merged**
