### PR TITLE
chore:improved github actions

### LINKED ISSUE #1067: Improve Github actions
### Is your feature request related to a problem? Please describe.

Currently we have two separate workflows for lint and build/tests 

### Describe the solution you'd like

Have them in the same workflow. Run the lint check before the tests.

### PR DESCRIPTION
**Pull request by vj-codes**
### Description
Combined lint code with black and run tests into one workflow with multiple jobs and running test is dependent on lint code build.

Fixes #1067 

### Type of Change:

- Code
- Quality Assurance

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**

- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by epicadk** [comment]
Can you make a small change that would cause black to fail and then see if the Build test is canceled?

**Comment by vj-codes** [comment]
@epicadk yeah onto that
 I created this only to check if the build is triggered or not 👀

**Comment by vj-codes** [comment]
> Can you make a small change that would cause black to fail and then see if the Build test is canceled?

@epicadk I used `needs` to make them interrelated, do you want me to commit a small change to crosscheck it and then revert it?

**Comment by epicadk** [comment]
> > Can you make a small change that would cause black to fail and then see if the Build test is canceled?
> 
> @epicadk I used `needs` to make them interrelated, do you want me to commit a small change to crosscheck it and then revert it?

Yes please

**Comment by vj-codes** [comment]
@epicadk done , now the build was skipped as black failed ,is it alright now?

**Comment by epicadk** [comment]
> @epicadk done , now the build was skipped as black failed ,is it alright now?

Yup seems cool. I'm fine with this. 

You could try to improve it further if you want. For example, currently, the build test is completely skipped if the lint fails. Instead, both could run concurrently but if the lint fails then you can cancel the build test. although I am not 100% sure that it's possible

**Review by epicadk — DISMISSED** [review]
👍🏼

**Comment by epicadk** [comment]
@isabelcosta you can see both of them separately in the Checks section : ) so I guess you could approve this? ( with reference to [this](https://github.com/anitab-org/mentorship-backend/issues/1067#issuecomment-812879412))

**Comment by epicadk** [comment]
@vj-codes please revert the change it looks good.

**Review by epicadk — APPROVED** [review]

**Review by isabelcosta — APPROVED** [review]
Awesome 👏🏾 
Thank you for working on this @vj-codes 🤗

**Comment by isabelcosta** [comment]
Will merge since this is already tested by looking at the checks on this PR :)

**Pull request merged**
