### PR TITLE
style: typo fix on "user was created successfully"

### LINKED ISSUE #225: Fix typo in user creation success message
## Description

As a developer of the backend,
I need to deliver consistent response messages,
so that I can better code quality and readability.

This issue is about fixing a small typo in the `USER_WAS_CREATED_SUCCESSFULLY`, that has no space between the second and third sentences. 

### Update [Required]
- [ ] Add a space between second and third sentence of the `USER_WAS_CREATED_SUCCESSFULLY` message

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by bboomboom**
### Description
Here I edited the USER_WAS_CREATED_SUCCESSFULLY line, because it was missing a space.

Fixes #225

### Type of Change:
- User Interface

### How Has This Been Tested?
If I could be honest, i do not know how to test it. I only added a missing space.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Great job @bboomboom !
Thank you for your contribution 🎉

**Comment by isabelcosta** [comment]
@bboomboom I added the following, `Fixes #225` to the pull request (PR) description, so that GitHub will reference this PR in the proper issue. This PR now will be reflected on the issue, you can check it out. Please, keep this in mind for future contributions :)

**Comment by bboomboom** [comment]
@isabelcosta Thank you! I would only need to write the issue reference on the description right?

**Comment by isabelcosta** [comment]
Yes @bboomboom  :)

**Pull request merged**
