### PR TITLE
feat: add user.name and sent_by_me to GET /comments response

### LINKED ISSUE #685: Improve GET (...)/comments response to include user.name and sent_by_me
## Description
As a frontend developer,
I need to have more information about the user who commented on a task,
so that I can display information as the user's name.

The idea is to improve the response of POST (...)/comments API to provide user `name` and `sent_by_me` boolean.

## Mocks

Instead of having:
```
{
  "id": 0,
  "user_id": 0,
  "task_id": 0,
  "relation_id": 0,
  "creation_date": 0,
  "modification_date": 0,
  "comment": "string"
}
```
Have something like:
```
{
  "id": 0,
  "sent_by_me": true,
  "user": {
    "id": 0,
    "name": "string"
  },
  "task_id": 0,
  "relation_id": 0,
  "creation_date": 0,
  "modification_date": 0,
  "comment": "string"
}
```
where `author` is the person who commented.

### Update [Required]
- [ ] Update the response
- [ ] Update and write new unit tests

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by ashokrayal**
### Description

Fix #685 Improve GET (...)/comments response to include user.name and sent_by_me

### Type of Change:

- Code

**Code/Quality Assurance Only**

### How Has This Been Tested?

I created a task for a relationship and added a comment for the task. Then checked comments for both users for the same task. It was behaving as expected.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**

- [x] I have added (**updated**) tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ashokrayal** [comment]
Hi @isabelcosta,

Can you please review my PR?

Thanks

**Comment by techno-disaster** [comment]
@anitab-org/coding-team @anitab-org/mentorship-backend-maintainers can someone review this PR?

**Comment by ashokrayal** [comment]
> 
> 
> @anitab-org/coding-team @anitab-org/mentorship-backend-maintainers can someone review this PR?

Hi @Techno-Disaster,

Can you please assign my PR's for review? I have total 4 PR's ready for review but there is no progress. 

Thanks.

**Comment by isabelcosta** [comment]
@Ashokrayal don't be shy to post on Zulip that you need reviews. There are people who may be willing to help with reviews but are unaware of the PRs that are ready for reviews. I often post on #coding or #mentorship-system stream with PRs I need help with

**Comment by techno-disaster** [comment]
> @Ashokrayal don't be shy to post on Zulip that you need reviews. There are people who may be willing to help with reviews but are unaware of the PRs that are ready for reviews. I often post on #coding or #mentorship-system stream with PRs I need help with

Hey @isabelcosta could you change the title to a more relevant one? Thank you

**Comment by isabelcosta** [comment]
> > @Ashokrayal don't be shy to post on Zulip that you need reviews. There are people who may be willing to help with reviews but are unaware of the PRs that are ready for reviews. I often post on #coding or #mentorship-system stream with PRs I need help with
> 
> Hey @isabelcosta could you change the title to a more relevant one? Thank you

I can, but it's important to notice that @Ashokrayal can too :) So next time you can tag the contributor @Techno-Disaster

**Comment by ashokrayal** [comment]
Thanks. @isabelcosta, @Techno-Disaster ,

I have edited the title for other PR's and posted a message on zulip. 

Thanks for help.

**Comment by isabelcosta** [comment]
Awesome @Ashokrayal 👏

**Review by techno-disaster — APPROVED** [review]
LGTM sorry for the late review looks like i missed this notification

**Comment by NenadPantelic** [comment]
@Ashokrayal Please, solve the conflicts.

**Comment by vj-codes** [comment]
@Ashokrayal closing due to inacativity 
Thank you for your contribution :)

**Pull request closed without merging**
